### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by mdominguez** [verbb/navigation#10]
Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them. On xxx/verbb/navigation/src/elements/Node.php:122
[view screenshot](https://cl.ly/tBjy)

**Comment by engram-design** [comment]
Fixed as of [#6](https://github.com/verbb/navigation/pull/6), and will be rolled into the next release.

**Comment by clarknelson** [comment]
yay thanks :)

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/navigation/releases/tag/1.0.3)
