### ISSUE TITLE
FR: Option to add attributes to Custom Link

### ISSUE THREAD

**Issue by richhayler** [verbb/navigation#100]
It would be cool to be able to add link attributes when adding a custom link, e.g.

`data-toggle="smooth-scroll"`

While this can be applied in the template code to render the node having the option to add it via the control panel means it is easier for each link to have have a different data attribute or none at all.

**Comment by engram-design** [comment]
We'll look at adding a table field to manage attributes.

**Comment by engram-design** [comment]
Added in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0)
