### ISSUE TITLE
Bug: Multi-Site - Nav Links always point to Primary Site

### ISSUE THREAD

**Issue by richhayler** [verbb/navigation#101]
### Description
It appears there may be a bug introduced in 1.1.13 that causes navigation links to point to the primary site in a multi-site setup rather than the currently viewed site.

I'm using the standard navigation.render code in my template to render the nav but the links point to the primary site URL rather than the site the nav appears in.

`craft.navigation.render('navHandle')`

- Plugin version: 1.1.13
- Craft version: 3.2.6

**Comment by richhayler** [comment]
I uninstalled and then reinstalled the plugin and this resolved the issue. Links in site navs are now pointing to the current site.

**Comment by engram-design** [comment]
Some reason I missed this @richhayler but thanks for confirming!
