### ISSUE TITLE
Add config setting to enable/disable instantly saving nodes when changing their position in a nav

### ISSUE THREAD

**Issue by engram-design** [verbb/navigation#104]
Not sure how feasible this is to have this change in behaviour, as its quite different

**Comment by Saboteur777** [comment]
One of my client specifically asked for an authoring experience similar to entries: no instant changes on edits, have drafts, preview, etc. The usual stuff they accustomed to by using Craft. :D

**Comment by engram-design** [comment]
Out of interest, why not use Entries by creating a new structure, rather than use this plugin at all? I don't think we'll ever have draft support, or a live preview of an individual node. Having changes not save when editing a node would be tricky in its current form.

We'd have to change the interface altogether to work and function exactly like entries, which if it gets to that, begs the question whether it'd just be easier using entries natively.

**Comment by Saboteur777** [comment]
I was thinking about the same, but I did not want to be the guy with the hammer. :) Thanks, we will transition to Entries gradually then.

**Comment by engram-design** [comment]
Going to close this, as it's a bit of a massive undertaking, and probably not something we'll do in the long-run! **However** we have introduced the concepts of drafts for navigation nodes in [2.0.0-beta.4](https://github.com/verbb/navigation/releases/tag/2.0.0-beta.4) for Craft 4.

It's more the moving-in-structure behaviour will always be live - just like it is for entries. As soon as you move something in the structure, the URL is updated.
