### ISSUE TITLE
Ability to hook into the logic that determines whether a node is "active"

### ISSUE THREAD

**Issue by benface** [verbb/navigation#105]
Sometimes I want a nav item to appear active when the user is actually on an entry whose URL doesn't necessarily start with the same path. It would be nice if there was an event for when a node gets initialized or something, where we could manually set `active` to `true` or `false` based on the node's `element` and other things.

**Comment by engram-design** [comment]
Added in [1.1.14](https://github.com/verbb/navigation/releases/tag/1.1.14).

Also see https://verbb.io/craft-plugins/navigation/docs/developers/events#the-modifyNodeActive-event
