### ISSUE TITLE
Config setting to enable/disable node types

### ISSUE THREAD

**Issue by benface** [verbb/navigation#106]
I would like to hide the "Categories" and "Assets" dropdowns in the navigation editor, which I can do with custom CSS but it would be nice to have a config option for it.

**Comment by engram-design** [comment]
No problem, done! Please use the `disabledElements` config setting to exclude any elements from being selected. Added in [1.1.14](https://github.com/verbb/navigation/releases/tag/1.1.14)

Also see https://verbb.io/craft-plugins/navigation/docs/get-started/configuration#configuration-options
