### ISSUE TITLE
[Feature Request] Ability to add a URL fragment or query string to element nodes

### ISSUE THREAD

**Issue by benface** [verbb/navigation#107]
Basically, it would be nice to have a way to append things to the URL of node types other than "Custom URL", in order to direct the user to a specific target on the page (e.g. `#more-info`), or to pass some options (e.g. `?showAll=true`).

**Comment by engram-design** [comment]
I think we'll achieve this through additional attribute support https://github.com/verbb/navigation/issues/109

**Comment by engram-design** [comment]
Added in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0)
