### ISSUE TITLE
Ability to add custom data attributes to each of the Menus

### ISSUE THREAD

**Issue by godwinajit** [verbb/navigation#109]
### Description

It will be nice to have the ability to add custom data attributes to each menu items.

i.e ( From olivemenus ) If you want to use data attributes assignment to each menu item, you can add your data items in the following format in the Data JSON Field:

data-attr : value-1
Add a new line for each data attribute.

Ex: The output would be something similar to 

`<a class="customclass" href="/my-blog" id="menuid1" data-ga-event="home: clickMyBlog" data-ga-vis-type="button" data-ga-vis-location="Main menu My Blog">My Blog<a/>
`

[proposed Label] feature request [proposed Label]

**Comment by engram-design** [comment]
Yep, high on the todo list!

**Comment by engram-design** [comment]
Added in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0)
