### ISSUE TITLE
Version 1.1.14 is broken

### ISSUE THREAD

**Issue by nettum** [verbb/navigation#112]
Version 1.1.14 seems to have a dd in the source?  
https://github.com/verbb/navigation/commit/c61095c8dc9c08799de78496f7464b3b72774048#diff-33917edc5ccba21fbe13f1ed47b7a624R149 :thinking: 

![image](https://user-images.githubusercontent.com/798156/69723928-0db55c00-111b-11ea-95ba-91add000c493.png)

**Comment by PopaWeb** [comment]
Same thing here in CP and front-end

**Comment by engram-design** [comment]
Whoops, that's what I get for a late-night commit. Fixed in [1.1.14.1](https://github.com/verbb/navigation/releases/tag/1.1.14.1)
