### ISSUE TITLE
Question: How I can edit existed link?

### ISSUE THREAD

**Issue by umkasanki** [verbb/navigation#113]
Hello.
I wanted to change the file/url for the terms in the nav.
I click both the pencil as the wheel, but cant find how to change it. Am I missing something?
Thanks

![Schermafbeelding 2019-11-28 om 16 26 07](https://user-images.githubusercontent.com/496132/69818784-952fc780-120e-11ea-919c-b9c195dad424.png)

**Comment by engram-design** [comment]
Currently, you can't edit a navigation's element when its already been set. This has changed in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0), where you now can.
