### ISSUE TITLE
[Feature Request] Ability to create our own node types

### ISSUE THREAD

**Issue by benface** [verbb/navigation#114]
It would be nice if we could define custom node types, perhaps via an event (e.g. `Navs::EVENT_REGISTER_NODE_TYPES`). A use case would be to create a "group" node type that doesn't have a URL by itself, but that could be used to generate a dropdown on the front-end in which the children nodes would appear.

**Comment by engram-design** [comment]
Added in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0). See [docs](https://verbb.io/craft-plugins/navigation/docs/developers/extending-elements)
