### ISSUE TITLE
No order of element in the output of all and newParentId is null

### ISSUE THREAD

**Issue by christophstockinger** [verbb/navigation#116]
### Description
I'm using Verbb/Navigation as a plugin in CraftCMS and want to use the element API to output a stored navigation with the PHP functions and send it to my SPA frontend.
Unfortunately I have to state that it is not possible to access the children element of a parent element, because with the following command only all navigation elements are returned as objects in an array.
```php
$query = verbb\navigation\elements\Node::find();
$allItems = $query->all();
```
Furthermore, I noticed that the "newParentId" is always zero when outputting child elements. According to my understanding, however, the id of the parent element should be output there. Also in the database null is stored.

![image](https://user-images.githubusercontent.com/24808473/70355323-225bc780-1872-11ea-8565-2322f22c9d78.png)

Could this also be due to the test version?

### Steps to reproduce

1. Use code at the top for output in the Element API.

### Additional info

- Plugin version: 1.1.14.1
- Craft version: 3.3.17

**Comment by engram-design** [comment]
Firstly, `newParentId` should correctly be null most of the time. This is only set a value if there's a _new_ parent, so when its being moved in a structure. It should only be populated when you want to move it in your nav.

Regarding showing items in a nested fashion in element API - its a little tricky, but doable:
```
function getChildren($nodes) {
    foreach ($nodes as $node) {
        $items[] = [
            'title' => $node->title,
            'url' => $node->url,
            'children' => $node->hasDescendants ? getChildren($node->children) : [],
        ];
    }

    return $items;
}

return [
    'endpoints' => [
        'nodes.json' => function() {
            return [
                'elementType' => verbb\navigation\elements\Node::class,
                'criteria' => [
                    'handle' => 'mainMenu',
                    'orderBy' => 'lft asc',
                    'level' => 1,
                ],
                'transformer' => function(verbb\navigation\elements\Node $node) {
                    return [
                        'title' => $node->title,
                        'url' => $node->url,
                        'children' => $node->hasDescendants ? getChildren($node->children) : []
                    ];
                },
            ];
        },
    ]
];
```

Hope that helps!
