### ISSUE TITLE
Can't install - 500 error

### ISSUE THREAD

**Issue by ptlab-la** [verbb/navigation#118]
### Description

Used to work fine, perhaps an issue with a Craft update?

Get the following error when trying to install. Then it appears in Craft plugin as not installed. When you click install, it says "Cannot install plugin"

Status: Internal Server Error

Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
you@example.com and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>

### Steps to reproduce

1. Search plugin store
2. Install

### Additional info

- Plugin version: Latest
- Craft version: 3.1.5

**Comment by engram-design** [comment]
Hmmm, sounds like a timeout issue -  I imagine this is on a development server, locally? Installing other plugins works fine I take it?

Is devMode on? Are there any logs in `storage/logs/web.log` (search for `[error]`), which should provide some info as to why the plugin wasn't installed

**Comment by jsunsawyer** [comment]
Also having this issue. Here's my error in the logs.

```
[error][yii\base\ErrorException:1] yii\base\ErrorException: Allowed memory size of 268435456 bytes exhausted (tried to allocate 37748736 bytes) in ...
```

And here's the file it references if that helps (removed my local path)
... in `vendor/composer/composer/src/Composer/DependencyResolver/RuleSet.php:90`

It's trying to allocate less memory than my allowed size, so not sure what's up here.

**Comment by engram-design** [comment]
Are you installing via the plugin store, or via `composer require verbb/navigation`?

**Comment by jsunsawyer** [comment]
@engram-design The plugin store.

**Comment by jsunsawyer** [comment]
Here's what I get after trying to install via composer.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install craftcms/cms 3.4.2
    - Conclusion: don't install craftcms/cms 3.4.1
    - Conclusion: don't install craftcms/cms 3.4.0.2
    - Installation request for craftcms/cms (locked at 3.3.20, required as ^3.0.0) -> satisfiable by craftcms/cms[3.3.20].
    - Conclusion: don't install craftcms/cms 3.4.0.1
    - verbb/navigation 1.3.0 requires craftcms/cms ^3.4.0 -> satisfiable by craftcms/cms[3.4.0, 3.4.0.1, 3.4.0.2, 3.4.1, 3.4.2].
    - verbb/navigation 1.3.1 requires craftcms/cms ^3.4.0 -> satisfiable by craftcms/cms[3.4.0, 3.4.0.1, 3.4.0.2, 3.4.1, 3.4.2].
    - verbb/navigation 1.3.2 requires craftcms/cms ^3.4.0 -> satisfiable by craftcms/cms[3.4.0, 3.4.0.1, 3.4.0.2, 3.4.1, 3.4.2].
    - Conclusion: don't install craftcms/cms 3.4.0
    - Installation request for verbb/navigation ^1.3 -> satisfiable by verbb/navigation[1.3.0, 1.3.1, 1.3.2].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by engram-design** [comment]
Closing for now. Please let me know if this is still an issue.
