### ISSUE TITLE
Layout broken in Craft 3.4 Beta-4

### ISSUE THREAD

**Issue by mylesthedev** [verbb/navigation#119]
### Description
The layout is broken with Craft's new style in 3.4 (i'm using beta 4).
There are also javascript errors which might be the main cause for the broken layout.

![Screen Shot 2019-12-19 at 3 47 34 PM](https://user-images.githubusercontent.com/909749/71140981-ad2bc180-2277-11ea-8790-5f70665c0e43.png)

### Steps to reproduce

1. Install Craft CMS 3.4
2. Install Navigation

**Comment by benmeng-synnex** [comment]
i have this problem as well, is there anyone can answer this question?

**Comment by engram-design** [comment]
Yep, completely untested for Craft 3.4, and won't be for 1-2 weeks. Will be the next item on the list.

**Comment by ciarj** [comment]
I have the same problem. In addition to layout problem I am unable to edit my menus, or create any new elements within a menu. Does anyone have this problem?

**Comment by engram-design** [comment]
Fixed in [feature/craft-3.4](https://github.com/verbb/navigation/tree/feature/craft-3.4).

Update your `verbb/navigation` requirement in `composer.json` to `"^1.3.0-RC1"`, and then run `composer update`.

**Comment by mylesthedev** [comment]
Thanks for the speedy work @engram-design
