### ISSUE TITLE
Adding additional markup inside link

### ISSUE THREAD

**Issue by tyssen** [verbb/navigation#120]
If I wanted to do something like this:

    <a href>
        <h2>Heading</h2>
        <p>Subheading</p>
    </a>

would I be able to do that with this plugin?

**Comment by engram-design** [comment]
You can, but you'll need to render the nodes manually. You won't be able to use the `craft.navigation.render()` function. See the [docs](https://verbb.io/craft-plugins/navigation/docs/template-guides/rendering-nodes#craft-navigation-nodes)

**Comment by tyssen** [comment]
That describes how to handle the output, but what about the input? Can I enter those different headings via the plugin interface itself or would I have to create entries elsewhere in Craft?

**Comment by engram-design** [comment]
Ah, gotcha - nope, you can't add HTML with the input. From a client's point of view, this would be pretty risky to open up (I know you might know what you're doing, or have a tech-savvy client).

There's no plans for this, although the upcoming 1.2.0 release will include the ability to add additional custom fields to each node, so you can add things like heading and subheading intto custom fields. Would that work?

**Comment by tyssen** [comment]
Yep, custom fields would work. It would be handy if custom fields could be
assets too for adding images to mega menus.

**Comment by engram-design** [comment]
Yep, you can add as many custom fields as you like. Added in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0)

**Comment by tyssen** [comment]
Are the custom fields added with the attributes field?

**Comment by tyssen** [comment]
Nevermind, found it, all good. 👍
