### ISSUE TITLE
GraphQL - Entry Slugs being returned as "1" in all instances

### ISSUE THREAD

**Issue by davebeesley** [verbb/navigation#125]
### Description
When traversing a multi level navigation, Entry Slugs being returned as "1" in all instances.

### Steps to reproduce

1. Create a multi level navigation, in headless mode
2. Check the returned data (including slug) in GraphQL explorer

### Additional info

- Plugin version: 1.2.3
- Craft version: Pro 3.3.17

<img width="414" alt="Screenshot 2020-01-13 at 11 53 04" src="https://user-images.githubusercontent.com/20064772/72254323-9587f480-35fb-11ea-92e6-68c5e98abc22.png">
<img width="350" alt="Screenshot 2020-01-13 at 11 53 17" src="https://user-images.githubusercontent.com/20064772/72254324-9587f480-35fb-11ea-81ab-3459e957ed6b.png">

**Comment by engram-design** [comment]
This is expected behaviour, as Navigation Nodes don't have slugs. For instance, the ID, title, etc are all properties of the node, not the element its referring to.

I'll admit that we could make this a littler nicer so that its the element's slug, similar to how the URL is treated.

I have also just realised we're only exposing `elementId` and not `element`, otherwise you could do:
```
title,
element {
    title,
    slug,
}
```

**Comment by davebeesley** [comment]
Ah yeah.
I would have expected to be able to get certain attributes of the linked entry, as you describe there. 
Is that something easily added to the Plugin?

Similarly, the `url`/`uri` - `url` seems to either return null or the fully qualified domain of the cms, not ideal when we are using an api and therefore therefore likely on another domain.

**Comment by engram-design** [comment]
Yeah, I'll have that sorted for the next release in a day or so.

**Comment by davebeesley** [comment]
Awesome. Thanks

**Comment by engram-design** [comment]
Updated in [1.2.5](https://github.com/verbb/navigation/releases/tag/1.2.5). Please note that you need to use `elementSlug` to access this. We use the node's slug for something else (much more complicated).

**Comment by dguillory** [comment]
I'm using 1.2.5.1, and `elementSlug` and `element` aren't available via GraphQL, only `elementId`. Also, would it also be possible to make an `elementUri` available in GraphQL? We need to use URIs rather than fully qualified URLs, and they're not always equivalent to the element's slug.

**Comment by engram-design** [comment]
@dguillory This slipped my mind at the time, sorry. Updated in [1.2.6](https://github.com/verbb/navigation/releases/tag/1.2.6)

```
element {
  title,
  uri,
}
```

**Comment by stephanedemotte** [comment]
can you add `typeHandle` ?

```
element {
 typehandle
}
```

:)

**Comment by engram-design** [comment]
@stephanedemotte Refer to https://github.com/verbb/navigation/issues/131
