### ISSUE TITLE
Changes to navs not being synced with project config

### ISSUE THREAD

**Issue by tyssen** [verbb/navigation#126]
### Description

I'm trying to delete a nav on local and then have staging get the same changes after pushing/updating project config because `allowAdminChanges` is set to false on staging, but after updating, the deleted nav is still there on staging.

### Steps to reproduce

1. Delete nav from local, commit change to project.yaml, push to staging, run there and sync changes.
2. After staging is updated with the latest changes from project.yaml, the deleted nav is still there.

### Additional info

- Plugin version: 1.2.4
- Craft version: 3.3.19

**Comment by engram-design** [comment]
Tested this on a few different installs (with `allowAdminChanges = false` on staging, Craft 3.3.20.1), and seems to be working as it should. Can you run `./craft project-config/rebuild` to see if that helps?

Do you have your deleted nav still in `navigation_navs`? I imagine the `dateDeleted` column in null?

**Comment by tyssen** [comment]
Running `./craft project-config/rebuild` didn't change anything. Comparing DBs, it seems they've some how got right out of sync because the ones I'm concerned with have different `id`s and `structureId`s.

Is the only way forward to manually delete rows from the db? And if so, is it safe to delete the offending rows from `navigation_navs` and then any rows in `navigation_nodes` whose `navId` equals the `id` from `navigation_navs`?

**Comment by engram-design** [comment]
Hmm, interesting. You can delete those records, but it might be better to soft-delete them.

For each node in `navigation_nodes`, set the column `deletedWithNav = 1`

For the nav in `navigation_navs` set the `dateDeleted` column to be the current date

**Comment by tyssen** [comment]
I did that on both local and staging. Recreated the navs on local, pushed to staging, could see they were there in the dashboard, but when visiting the front-end now, I'm getting `Invalid navigation ID: 6`. 6 was one of the ones I soft deleted.

**Comment by tyssen** [comment]
I soft deleted four navs, all included in the same template partial. I recreated them with exactly the same names as before.

If I comment out three out of four of them, the error goes away. So one of them left in place doesn't bring down the site, but the other three do (different ID is reported as invalid depending on what's commented out).

**Comment by tyssen** [comment]
Changing the names of the navs eventually sorted this out but now I have a different problem but with the same error being reported. Except that this time, it's in the control panel when I'm trying to add an Assets image to an entry.

**Comment by przzz27** [comment]
Question, does the project config saves the navs and their items or just the navs?

**Comment by engram-design** [comment]
@przzz27 Only the navigation configuration is saved to project config. Navigation nodes, like other elements are content, so they can't be stored to project config.

**Comment by engram-design** [comment]
Closing for now, but let me know @tyssen if this continues to be an issue
