### ISSUE TITLE
Navigation node is re-eneabled after editing element

### ISSUE THREAD

**Issue by gglnx** [verbb/navigation#127]
### Description

The flag `enabled` of navigation node is linked to the value of the element (https://github.com/verbb/navigation/blob/craft-3/src/services/Nodes.php#L61). If you disabled a navigation node, and afterwards edit the element, which is still enabled, the navigation node will be re-enabled.

I would rather except that the navigation node `enabled` value will only be changed, if the value of `enabled` of the element has changed (e.g. disable node if element gets disabled).

### Steps to reproduce

1. Create enabled element
2. Create a navigation node for it
3. Disable the navigation node
4. Edit the element
5. The navigation node is re-eneabled

### Additional info

- Plugin version: 1.2.4
- Craft version: 3.3.19

**Comment by engram-design** [comment]
Agreed, and this now acts similar to the element's title.

Updated in [1.2.5](https://github.com/verbb/navigation/releases/tag/1.2.5)
