### ISSUE TITLE
Broken UI in 3.4

### ISSUE THREAD

**Issue by hatzipanis** [verbb/navigation#129]
### Description

Is anyone else facing issues with a broken UI in Craft 3.4?

<img width="1455" alt="Screen Shot 2020-01-29 at 7 07 53 PM" src="https://user-images.githubusercontent.com/1661180/73332125-ac506b80-42ca-11ea-92bd-deed8ac0b993.png">

### Steps to reproduce

1. Update Craft to 3.4

### Additional info

- Plugin version: 1.2.7
- Craft version: 3.4.0.2

**Comment by engram-design** [comment]
Refer to https://github.com/verbb/navigation/issues/119

Update your `verbb/navigation` requirement in `composer.json` to `"^1.3.0-RC1"`, and then run `composer update`.

A release will be out shortly once its been tested properly with 3.4

**Comment by hatzipanis** [comment]
Apologies @engram-design, I should have looked harder! Thanks.

**Comment by engram-design** [comment]
No problem, will leave open so other people know!

**Comment by engram-design** [comment]
@hatzipanis Refer to [1.3.0](https://github.com/verbb/navigation/releases/tag/1.3.0)
