### ISSUE TITLE
Sort menus by title in control panel.

### ISSUE THREAD

**Issue by johnniefp** [verbb/navigation#130]
We have a lot of menus, more than shown below. It would be nice to be able to alpha sort them by clicking **Name** or **Handle** table heading in the control panel listing.

![Verbb Nav](https://user-images.githubusercontent.com/93673/73392772-5ed7fc80-42d2-11ea-97ae-844604f8eaf2.png)

**Comment by engram-design** [comment]
You can at least manually order them at the moment. As we're using the core Craft Admin Table (now Vue-based in Craft 3.4) - I wonder if we should make this a feature request for all tables like this? Its not a massive priority to build my own table sort solution!

**Comment by johnniefp** [comment]
> I wonder if we should make this a feature request for all tables like this?

Good shout, would benefit all plugin devs though the request would carry more weight coming from you. ;)

> Its not a massive priority to build my own table sort solution!

Yeah, I get not many users have as many menus as us.

**Comment by engram-design** [comment]
@johnniefp We'll see how we go! https://github.com/craftcms/cms/issues/5545
