### ISSUE TITLE
Slash prepended to custom URLs beginning with different protocols

### ISSUE THREAD

**Issue by dguillory** [verbb/navigation#132]
### Description

Related to #128, custom URL nodes beginning with protocols like `mailto:` and `tel:` get a `/` prepended when saving.

### Steps to reproduce

1. Save a custom URL of `mailto:info@example.com`
2. Node contains `/mailto:info@example.com` and leads to a 404 error

### Additional info

- Plugin version: 1.2.7
- Craft version: 3.3.20.1

**Comment by engram-design** [comment]
Alright, I'm going to revert the behaviour introduced in https://github.com/verbb/navigation/issues/115 - there's just too many cases to take care of, and its becoming annoying.

Changed in [1.3.1](https://github.com/verbb/navigation/releases/tag/1.3.1) and [1.2.8](https://github.com/verbb/navigation/releases/tag/1.2.8)
