### ISSUE TITLE
Update not working.

### ISSUE THREAD

**Issue by Osze** [verbb/navigation#133]
### Description

Updated Craft and the Navigation Plugin to it's latest version.

Update crashed with info:

Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'navigation_nodes.urlSuffix' in 'field list'
The SQL being executed was: SELECT elements.id, elements.fieldLayoutId, elements.uid, elements.enabled, elements.archived, elements.dateCreated, elements.dateUpdated, elements_sites.slug, elements_sites.siteId, elements_sites.uri, elements_sites.enabled AS enabledForSite, navigation_nodes.id, navigation_nodes.elementId, navigation_nodes.navId, navigation_nodes.url, navigation_nodes.type, navigation_nodes.classes, navigation_nodes.urlSuffix, navigation_nodes.customAttributes, navigation_nodes.newWindow, element_item_sites.uri AS elementUrl, content.id AS contentId, content.title, structureelements.root, structureelements.lft, structureelements.rgt, structureelements.level, structureelements.structureId
FROM (SELECT elements.id AS elementsId, elements_sites.id AS elementsSitesId, content.id AS contentId, structureelements.structureId
FROM craft_elements elements
INNER JOIN craft_navigation_nodes navigation_nodes ON navigation_nodes.id = elements.id
INNER JOIN craft_navigation_navs navigation_navs ON navigation_nodes.navId = navigation_navs.id
INNER JOIN craft_elements_sites elements_sites ON elements_sites.elementId = elements.id
INNER JOIN craft_content content ON (content.elementId = elements.id) AND (content.siteId = elements_sites.siteId)
LEFT JOIN craft_structureelements structureelements ON (structureelements.elementId = elements.id) AND (EXISTS (SELECT *
FROM craft_structures
WHERE (id = structureelements.structureId) AND (dateDeleted IS NULL)))
WHERE (navigation_nodes.elementId='2') AND (navigation_nodes.type='craft\\elements\\Entry') AND (elements_sites.siteId='1') AND (elements.archived=FALSE) AND (elements.dateDeleted IS NULL) AND (elements_sites.slug='1') AND (elements_sites.enabled=TRUE) AND (elements.draftId IS NULL) AND (elements.revisionId IS NULL)
ORDER BY structureelements.lft, elements.dateCreated DESC) subquery
INNER JOIN craft_navigation_nodes navigation_nodes ON navigation_nodes.id = subquery.elementsId
INNER JOIN craft_elements elements ON elements.id = subquery.elementsId
INNER JOIN craft_elements_sites elements_sites ON elements_sites.id = subquery.elementsSitesId
INNER JOIN craft_content content ON content.id = subquery.contentId
LEFT JOIN craft_structureelements structureelements ON (structureelements.elementId = subquery.elementsId) AND (structureelements.structureId = subquery.structureId)
LEFT JOIN craft_elements_sites element_item_sites ON navigation_nodes.elementId = element_item_sites.elementId AND CAST(elements_sites.slug AS UNSIGNED) = element_item_sites.siteId
ORDER BY structureelements.lft, elements.dateCreated DESC

Migration: craft\migrations\m190913_152146_update_preview_targets

### Steps to reproduce

1. Updated all plugins and Craft to it's latest version.

### Additional info

- Plugin version:  1.1.14.1
- Craft version: 3.3.17

**Comment by engram-design** [comment]
Just to confirm you updated from:
Navigation 1.1.14.1 to 1.3.1
Craft 3.3.17 to 3.4.2

**Comment by Osze** [comment]
Yes.

**Comment by engram-design** [comment]
Can't seem to replicate it with those same versions and upgrading. Also seems like it might be related to a Craft core migration - `craft\migrations\m190913_152146_update_preview_targets`.

Any chance you could send through a database snapshot - even a cut-down version? If so, you can send through to web@verbb.io

**Comment by engram-design** [comment]
Should be fixed in [1.3.2](https://github.com/verbb/navigation/releases/tag/1.3.2), thanks so much for your assistance!

**Comment by tomdeleu** [comment]
This does not seem fixed when I try it.
Just tried updating 2 sites (with updates pending a couple of months), and I get the result above.

For example when updating one of the sites:
Craft CMS: "3.3.4.1" > "3.3.4.1"
Navigation: "1.1.13" > "1.2.8"

Any idea how to prevent it?

**Comment by johnwbaxter** [comment]
@engram-design Hi, I'm having the exact same issue today!
