### ISSUE TITLE
Enabled/Disabled indicator is incorrectly toggled when setting links to "Open in new window"

### ISSUE THREAD

**Issue by jsunsawyer** [verbb/navigation#134]
### Description
This is not a major issue, but might be confusing when managing a large nav.

Upon changing a nav item to open in a new window, the green (enabled) indicator turns red instead of adding the new window indicator.

![Screen Shot 2020-02-04 at 3 40 29 PM](https://user-images.githubusercontent.com/1007191/73797611-6a5d7480-4765-11ea-9307-0e4cf8a70026.png)

Refreshing the page resolves the issue.

![Screen Shot 2020-02-04 at 3 40 39 PM](https://user-images.githubusercontent.com/1007191/73797628-70535580-4765-11ea-8bd3-5664133d236e.png)

### Steps to reproduce

1. Set up a nav item
2. Toggle its "Open in new window" value

### Additional info

- Plugin version: 1.3.2.1
- Craft version: 3.4.3

**Comment by engram-design** [comment]
Fixed in [1.3.3](https://github.com/verbb/navigation/releases/tag/1.3.3)
