### ISSUE TITLE
Javascript error when editing node settings

### ISSUE THREAD

**Issue by davist11** [verbb/navigation#135]
### Description
When editing the settings of a node, there is a javascript error

```
navigation.js?v=1581093298:1 Uncaught TypeError: Cannot read property 'settings' of undefined
    at s.constructor.<anonymous> (navigation.js?v=1581093298:1)
    at i (jquery.js?v=1581089823:1)
```

### Steps to reproduce

1. Add a node to a navigation
2. Double click on the node (or click the node settings)
3. See javascript error

### Additional info

- Plugin version: 1.3.3
- Craft version: Craft Pro 3.4.4.1

**Comment by engram-design** [comment]
Fixed in [1.3.4](https://github.com/verbb/navigation/releases/tag/1.3.4)
