### ISSUE TITLE
Twig Template Loading Error

### ISSUE THREAD

**Issue by nixondesigndev** [verbb/navigation#136]
### Description

Unable to find the template “navigation/_svg/verbb-logo.svg” in "navigation/_layouts" at line 30.

### Steps to reproduce

1. Navigate to plugin in CP

### Additional info

- Plugin version: 1.3.3
- Craft version: Craft Pro 3.4.5

**Comment by engram-design** [comment]
Are you sure you're on 1.3.3? Browsing that file for that version is correct - https://github.com/verbb/navigation/blob/71b22aca63197483c4e7007dd141bd1e3b27aef7/src/templates/_layouts/index.html#L30

**Comment by nixondesigndev** [comment]
Just updated from 1.2.7 to 1.3.4 with no issues. 1.2.7 to 1.3.3 does error so not sure what's up.
