### ISSUE TITLE
Template menu inside the record

### ISSUE THREAD

**Issue by thefubon** [verbb/navigation#137]
<img width="806" alt="Снимок экрана 2020-02-11 в 18 52 10" src="https://user-images.githubusercontent.com/43171309/74253943-d3626080-4d00-11ea-9892-1593ea9bd009.png">

### Description

Please tell me how to display in the template menu the menu that is added inside the record

### Additional info

- Plugin version: 1.3.4
- Craft version: 3.4.5

**Comment by engram-design** [comment]
Refer to the documentation regarding this  https://verbb.io/craft-plugins/navigation/docs/template-guides/navigation-field

**Comment by thefubon** [comment]
I just tried it and it didn’t work out for me. Then I asked the question how to do it right

https://www.youtube.com/watch?v=agwFZfpdw9I
