### ISSUE TITLE
Hide 'Edit Settings' if the user doesn't have permissions to edit that navigation

### ISSUE THREAD

**Issue by jamiewade** [verbb/navigation#140]
![Screenshot_2020-02-27 Navigation - Southend-on-Sea Borough Council](https://user-images.githubusercontent.com/6672331/75464318-efac0180-597e-11ea-94b9-297d1ebf3231.png)

If a user doesn't have access to edit the settings for a navigation through the Craft User permissions, it might be a good idea to hide the "Edit Settings" link, instead of showing it and returning a user permissions error when they click it.

**Comment by engram-design** [comment]
This is currently already the case. Refer to the screenshot.

<img width="1042" alt="Screen Shot 2020-08-09 at 9 27 39 pm" src="https://user-images.githubusercontent.com/1221575/89731025-2e45fc00-da87-11ea-9e3c-5f8a092f8ad9.png">

Here, the user has permission to edit "Main Menu" and "Sites" navigations. However, they only have access to edit the settings of the "Sites" nav.
