### ISSUE TITLE
Triggering a webhook when the order of the navigation items change?

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/navigation#141]
### Description
What's the recommended way to fire a webhook event in the Pixel & Tonic [Webhooks](https://github.com/craftcms/webhooks) plugin when the order of the navigation changes?

### Steps to reproduce
N/A

### Additional info

- Plugin version: 1.3.5
- Craft version: 3.4.5

**Comment by engram-design** [comment]
I'm not overly familiar with the Webhook plugin, but can you listen to the node's element events? There's the usual before/after save events:

```
use verbb\navigation\elements\Node;
use craft\base\Element;
use craft\events\ModelEvent;
use yii\base\Event;

Event::on(Node::class, Element::EVENT_BEFORE_SAVE, function(ModelEvent $event) {

});

Event::on(Node::class, Element::EVENT_AFTER_SAVE, function(ModelEvent $event) {

});
```

Or, even the before/after move in structure events:

```
use verbb\navigation\elements\Node;
use craft\base\Element;
use craft\events\ElementStructureEvent;
use yii\base\Event;

Event::on(Node::class, Element::EVENT_BEFORE_MOVE_IN_STRUCTURE, function(ElementStructureEvent $event) {

});

Event::on(Node::class, Element::EVENT_AFTER_MOVE_IN_STRUCTURE, function(ElementStructureEvent $event) {

});
```

Would that work?

**Comment by jlachancekffein** [comment]
I confirm that it works
