### ISSUE TITLE
Editing Navigation drops custom order value

### ISSUE THREAD

**Issue by chadcrowell** [verbb/navigation#145]
### Description
I have several navs. When I edit one and save it, and am returned to the list of navs, the custom order of the navs I had previously created has changed - looking in the database, the nav I edited has dropped its sortOrder value and is null.

### Steps to reproduce

1. Create several navs
2. Drag them into a specific order
3. Edit one of them
4. Check the db sortOrder column

### Additional info

- Plugin version: 1.3.6
- Craft version: 3.4.11

**Comment by engram-design** [comment]
Fixed in [1.3.9](https://github.com/verbb/navigation/releases/tag/1.3.9)
