### ISSUE TITLE
URL Suffixs does not save

### ISSUE THREAD

**Issue by Slgoetz** [verbb/navigation#148]
### Description
URL Suffix for entry items are not being saved.  There is no error, but the suffix disappears  after you click save and re-open the edit box.

### Steps to reproduce

1. Add entry to a menu
2. Click edit on that entry and add a URL Suffix
3. Save the suffix
4. Re-open the entry edit and you will be missing the Suffix you just entered

### Additional info

- Plugin version: 1.3.8
- Craft version: Craft Pro 3.4.14

**Comment by engram-design** [comment]
Can't seem to replicate this on a few installs. Would you be able to check the `navigation_nodes` table to see if the `urlSuffix` column is actually being populated?

**Comment by Slgoetz** [comment]
the table is being populated but dumping the variable there is nothing there.  Will get you an screenshot and more details shortly.

**Comment by engram-design** [comment]
Refer to my test setup:

![Screen Shot 2020-04-17 at 8 45 10 am](https://user-images.githubusercontent.com/1221575/79513687-c9a20400-8087-11ea-8573-b55ea6a9d130.png)

```
{% nav node in nodes %}
    title = {{ node.title }}<br>
    urlSuffix = {{ node.urlSuffix }}<br>
{% endnav %}
```

Produces:
```
title = Homepage
urlSuffix = Suffix
```

**Comment by engram-design** [comment]
Closing for now, please let me know if this is still an issue.
