### ISSUE TITLE
Custom URL -> URL gets overwritten on edit if you choose an entry or asset

### ISSUE THREAD

**Issue by nettum** [verbb/navigation#149]
### Description
If editing a "Custom URL"-element the URL value is getting overwritten by the URL of the element selected in the entry / asset field. 

See attched video: https://i.imgur.com/qbM6IDE.mp4

### Steps to reproduce

1. Create either an entry or asset field
2. Create a navigation 
3. Add the field from 1. to the navigation created in 2.
4. Add a new "Custom URL" element.
5. Edit the "Custom URL" element and add an entry/image.
6. See that the URL is updated with the value from the entry/image.

I would expect that the URL is not updated since the navigation item is a "Custom URL" element. Or at least it should noe be updated if the URL input already have a value.

### Additional info

- Plugin version: 1.3.12
- Craft version: Craft Pro 3.4.16

**Comment by engram-design** [comment]
Interesting - if you have an element custom field on the node, that'll overwrite the URL.

Should be fixed in [1.3.13](https://github.com/verbb/navigation/releases/tag/1.3.13)
