### ISSUE TITLE
URL suffix breaks .getActiveNode queries

### ISSUE THREAD

**Issue by ghost** [verbb/navigation#154]
### Description

I'm running a custom query to get the active node. It works as expected as long as I don't use a URL suffix for that page. If I do, I get null as a result, where before I got the active node.

`{% set activeNode = craft.navigation.getActiveNode({ handle: 'main' }) %}`

In my case I use the suffix for a fragment identifier like `#el3`. 

Thank you very much for any clarification if I do anything wrong on my end.

### Steps to reproduce

1. Add an item to navigation
2. Navigate to the page of that item
3. See the result for the active node query (using above query)
4. Go back to the navigation item and add a URL suffix
5. Return back to the page and the query result is null

### Additional info

- Plugin version: 1.3.14
- Craft version: 3.4.18

**Comment by engram-design** [comment]
Fixed in [1.3.15](https://github.com/verbb/navigation/releases/tag/1.3.15), thanks for reporting!
