### ISSUE TITLE
Multi-site switches back to default/first site from list

### ISSUE THREAD

**Issue by mylesthedev** [verbb/navigation#156]
### Description
When managing a multi-site and clicking into the Navigation plugin it seems to always default to the primary/first site which can be quite confusing if you were in the context of editing another site (it's not that obvious that is changes).

### Steps to reproduce

1. Edit a entry in Site #2
2. Click into a Navigation Node
3. Your site will now be set to Site #1

### Additional info

- Plugin version: 1.3.14
- Craft version: 3.4.20

**Comment by engram-design** [comment]
Should be fixed in [1.3.16](https://github.com/verbb/navigation/releases/tag/1.3.16)
