### ISSUE TITLE
NodeQuery SQL oddity

### ISSUE THREAD

**Issue by rob-c-baker** [verbb/navigation#157]
### Description

In the `NodeQuery` class, there is SQL generated in the afterPrepare() function that in effect, adds this to the node query:

```sql
`LEFT JOIN `craft_elements_sites` `element_item_sites` ON `navigation_nodes`.`elementId` = `element_item_sites`.`elementId` AND CAST(`elements_sites`.`slug` AS UNSIGNED) = `element_item_sites`.`siteId`
```

I'm wondering what this part is for:

```sql
CAST(`elements_sites`.`slug` AS UNSIGNED) = `element_item_sites`.`siteId`
```

`CAST()` here is forcing the string based slug to a 64 bit INT and comparing it against siteId.

### Additional info

- Plugin version: 1.3.17
- Craft version: 3.4.10.1

**Comment by engram-design** [comment]
We use the slug to store the linked element's site ID. When you select an element to connect a node to, the node element itself has a site ID, but we also want to record the element ID and element site ID of the element we're connecting to. Its a slight hack situation, but saves us having to have another table to store node_sites.

**Comment by rob-c-baker** [comment]
Ah... OK, thanks for the explanation.
