### ISSUE TITLE
Showing "add products" when disable or uninstall "Commerce Plugin"

### ISSUE THREAD

**Issue by Longnd128** [verbb/navigation#158]
### Description

- Showing "add products" when disable or uninstall "Commerce Plugin"
- BadRequestHttpException if the request is not a post request

### Steps to reproduce

1.
2.

### Additional info

- Plugin version: 1.3.17
- Craft version: 3.4.22.1

**Comment by engram-design** [comment]
Fixed in [1.3.18](https://github.com/verbb/navigation/releases/tag/1.3.18)
