### ISSUE TITLE
defaultSite is empty

### ISSUE THREAD

**Issue by gglnx** [verbb/navigation#159]
### Description

This commit (https://github.com/verbb/navigation/commit/1475655b9ee76346e3ccf2650fa535dbac9de43e#diff-14ed29e19485bd5bc68d618b471f162a) add `defaultSite`. But the variable will be outputed empty and a JavaScript error occurs: "SyntaxError: expected expression, got ','"

<img width="362" alt="Bildschirmfoto 2020-06-05 um 19 52 26" src="https://user-images.githubusercontent.com/23519/83907670-1c359d80-a766-11ea-9dbc-813e588039bb.png">

### Additional info

- Plugin version: 1.3.18
- Craft version: Craft Pro 3.4.22.1

**Comment by engram-design** [comment]
Fixed in [1.3.19](https://github.com/verbb/navigation/releases/tag/1.3.19)
