### ISSUE TITLE
Custom URL not active

### ISSUE THREAD

**Issue by andrispraulitis** [verbb/navigation#16]
### Description
When adding Custom URL which is simply a template in craft does not set active.

### Steps to reproduce

1. Create template in craft 
2. Add that template url to navigation as Custom URL

### Additional info

- Plugin version: latest
- Craft version: latest

Example: I have created news template to list entries. I have added /news to navigation and want that to be active on both /news & /news/{entry-slug}. Basically if first segment is "news", is this possible?

**Comment by engram-design** [comment]
Should be fixed in [1.0.5](https://github.com/verbb/navigation/releases/tag/1.0.5)
