### ISSUE TITLE
Navigation not editable when switching between sites

### ISSUE THREAD

**Issue by knynkwl** [verbb/navigation#160]
### Description
Currently, it is not possible to edit navigation items when switching between sites. It looks like it's a JS error, the whole dashboard is frozen. Can't add/edit entries

### Steps to reproduce

1. Edit a Navigation Item
2. Switch between sites

### Additional info

- Plugin version: 1.3.18
- Craft version: 3.4.22.1

**Comment by engram-design** [comment]
Can you try on [1.3.19](https://github.com/verbb/navigation/releases/tag/1.3.19)?

**Comment by knynkwl** [comment]
This version fixed it, thanks!
