### ISSUE TITLE
Class 'craft\services\Gql' not found

### ISSUE THREAD

**Issue by knynkwl** [verbb/navigation#161]
### Description
Updating from 1.1.12 -> 1.2.9 produces this error:

I also update CraftCMS from 3.1.27 -> 3.1.34.3

```php
Exception 'Error' with message 'Class 'craft\services\Gql' not found'

in /vendor/verbb/navigation/src/Navigation.php:193
```

### Additional info

- Plugin version: 3.1.34.3
- Craft version: 1.2.9

**Comment by engram-design** [comment]
You'll need to update your composer.json requirements to `1.1.14.1`. The entire `1.2.x` versions include GraphQL support, but I plain forgot to update Craft's requirements to Craft 3.3. I don't think I can do anything now.

So, either:
- Update your composer.json to use `"verbb/navigation": "1.1.14.1",`
- Update to Craft 3.3.x+
