### ISSUE TITLE
Swapping from Entry to Custom URL, Custom URL not respected

### ISSUE THREAD

**Issue by Marcuzz** [verbb/navigation#164]
### Description

When changing a node from being an `entry` type to being a `Custom URL` it doesn't clear the `elementId` field in the database (which I can see being intentional) which causes the plugin to infer the type is still `entry` even though the `type` field is empty. Shouldn't it completely disregard the `elementId` column if `type` is empty, and default to `url` instead?

This seems to be identical to https://github.com/verbb/navigation/issues/149 but it does not appear to be fixed, at least not in GraphQL 😃 

### Steps to reproduce

1. Create a navigation node and make it an `entry` type. Assign it to an entry
2. Check that the URL points to the entry
3. Modify the navigation node and make it a custom URL type, input a URL
4. The url returned will still point to the entry instead of  your custom URL (it at least does in GraphQL)

### Additional info

- Plugin version: 1.3.20
- Craft version: Craft Pro 3.4.24

**Comment by engram-design** [comment]
Should be fixed properly now in [1.3.21](https://github.com/verbb/navigation/releases/tag/1.3.21)
