### ISSUE TITLE
Clicking on a navigation shows a "ghost" navigation by default on multisite

### ISSUE THREAD

**Issue by bartrylant** [verbb/navigation#167]
### Description
I have a multisite setup. When I click on "Navigation" in the left bar, then click on a menu I created, it goes to `admin/navigation/navs/build/1`. However, this is a "ghost" navigation. It cannot be used anywhere. It is not the navigation from the default site, although the default site is selected in the dropdown menu at the top. I have to click the dropdown and reselect the default site. Only at that moment, it loads the correct navigation. (`admin/navigation/navs/build/1/default`)

### Steps to reproduce

1. Have a multisite setup
2. Select the default site in entries view
3. Click on navigation
4. Click on a menu to edit the nodes
5. See the uri
6. Select the default site in the site dropdown box
7. Only now you see the correct menu (check uri)

### Additional info

- Plugin version: 1.3.21
- Craft version: Craft Pro 3.4.28.1

**Comment by engram-design** [comment]
I'm not sure what you mean by "ghost" navigation, but you're correct in that its selecting the first editable site, rather than the primary site when not specifying a specific site.

Fixed in [1.3.22](https://github.com/verbb/navigation/releases/tag/1.3.22)
