### ISSUE TITLE
NodeTypes with hasTitle() = false result in a validation error on save.

### ISSUE THREAD

**Issue by loweoj** [verbb/navigation#168]
### Description
I'm creating a custom NodeType with `hasTitle = false`. I'm using this NodeType as a placeholder for some dynamic content that the user can choose where in the navigation bar it should go. hasTitle() hasUrl() hasNewWindow() hasClasses() are all false.

Creating a new node in the interface results in a validation error:

```
[craft\services\Elements::_saveElementInternal] Element not saved due to validation error: Array
(
    [title] => Array
        (
            [0] => Title cannot be blank.
        )

)
```

I'd expect hasTitle = false to save without the validation error. I can work around this for now, by adding a title which I won't use in the template.

### Additional info

- Plugin version: 1.3.21
- Craft version: 3.4.28.1

**Comment by engram-design** [comment]
Fixed in [1.3.22](https://github.com/verbb/navigation/releases/tag/1.3.22)
