### ISSUE TITLE
NodeTypes with long displayName breaks the node type label in the navigation table UI

### ISSUE THREAD

**Issue by loweoj** [verbb/navigation#169]
### Description
Adding a custom node type with a long display name results in the node type label splitting over multiple lines which doesn't look great.

The issue is this css with a fixed width:
```
.nav-builder .node-type {
    float: right;
    width: 80px;
    font-size: 12px;
    text-transform: lowercase;
    padding: 6px 7px;
    cursor: default;
}
```

### Steps to reproduce

1. Create a new custom node type with a long displayName "This Node Type Has a Long Title"
2. Add a new Node of the custom node type and notice the multi-line label

### Additional info

- Plugin version:  1.3.21
- Craft version: 3.4.28.1

**Comment by engram-design** [comment]
Fixed in [1.3.22](https://github.com/verbb/navigation/releases/tag/1.3.22)
