### ISSUE TITLE
Use navigation structure as URL structure

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#172]
In case of navigation with multiple levels, it would be great if we could somehow use this structure as a URL structure of section or category group.

I tried pasting something like this in section URL settings, but it didn't work properly.

```
{{ craft.navigation.nodes().ancestorOf(craft.navigation.getActiveNode({ handle: 'test' })).ancestorDist(1).one().element.uri ?? null }}
```

edit:

turns out `getActiveNode` always returned `null` in context of URL settings of section. Using this did the trick:

```
{{ craft.navigation.nodes().ancestorOf( craft.navigation.nodes('test').all()|filter(x => x.element.id == id)|first.id ).ancestorDist(1).one().element.uri ?? null }}/{{slug}}
```

**Comment by engram-design** [comment]
I'm afraid I don't quite follow this one - can you explain your use-case for this, and the desired API and expected result might be?

**Comment by piotrpog** [comment]
Sure. We can right now use section of type "structure" as basis for URL structure of entries. If in structure specific entry has parent entry, we can have URL like this:

```
parent/child
```

What i propose is adding ability to use position of specific entry in navigation tree as basis for URL. So if our entry had some specifc parent within navigation, that would be represented in this entry URL.

**Comment by engram-design** [comment]
Going to close this one, as it's not on our roadmap to cate for something like this, as the source of truth for structure should be the section.
