### ISSUE TITLE
[Craft 3.5.x bug] Multi-site nav with 'Propagate nodes' disabled returns default site entries

### ISSUE THREAD

**Issue by sjcallender** [verbb/navigation#173]
### Description
With the "Propagate nodes" field disabled, we're expecting that we'd control each site's nav separately. This part works.

But we have two other problems:

1. When we add a non-default site entry to a non-default site nav, the related entry in the node is still from the default site.
2. When we add two entries to a non-default site nav, both entries return the same url.

### Steps to reproduce

Per issue:
1. Add non-default site entry as a node on a non-default site navigation menu.
Watch screen recording: https://ssdd.d.pr/GX2P0A
2. Add another non-default site entry as a node on the same nav and check the url result.
Watch screen recording: https://ssdd.d.pr/pwwrc7

### Additional info

- Plugin version: 1.3.22
- Craft version: 3.5.0-RC4 (though this happened in earlier versions)

**Comment by sjcallender** [comment]
We have another site on Craft 3.4.20 and Navigation 1.3.21 and this issue does not exist.

**Comment by sjcallender** [comment]
Hey @engram-design, this is a showstopper for us. Mind taking a look sooner than later?

**Comment by engram-design** [comment]
Looks like this is a 3.5 issue. Looking into it.

**Comment by engram-design** [comment]
Should be fixed in [1.3.23](https://github.com/verbb/navigation/releases/tag/1.3.23)

**Comment by sjcallender** [comment]
@engram-design Thanks man. It looks like that fixed it. 🍻
