### ISSUE TITLE
Query nodes by related element

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#176]
In order to query nodes by related element, i need to do this:

```
craft.navigation.nodes('test').all()|filter(x => x.element.id == someElement.id)|first
```

I this example, `someElement` is an element I want to query by.

It would be usefull if we had some more comfortable syntax, like:

```
craft.navigation.nodes('test').relatedElement(someElement)
```

ps: I also tried to use standard `relatedBy`, but it didn't worked.

**Comment by engram-design** [comment]
You should be able to achieve this with `elementId`?

```
{% set entry = craft.entries.id(123).one() %}
{% set nodes = craft.navigation.nodes({ handle: 'test', elementId: entry.id }).all() %}
```
