### ISSUE TITLE
The "edit" gear for navs shouldn't appear if admin changes are disabled

### ISSUE THREAD

**Issue by Mosnar** [verbb/navigation#181]
**Description**
There's a little "gear" icon that appears to the top right when you're editing the content of a menu. If I click this, I'm given the option to make changes to the menu, even though I have allowAdminChanges set to false.

**Additional info**
- Plugin version: 1.3.26
- Craft version: 3.5.5
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [1.3.27](https://github.com/verbb/navigation/releases/tag/1.3.27)
