### ISSUE TITLE
Navigation for default site editable even if user lacks permissions

### ISSUE THREAD

**Issue by gglnx** [verbb/navigation#184]
**Description**

If an user without permissions for the default site goes into the navigation nodes editor, the navigation for the default site will be shown and can be changed. The default site is not included in the site switcher, but still selected.

**Steps to reproduce**
1. Create a second site
2. Create an user with permissions only to this second site
3. Create a navigation
4. Try to edit the navigation with this new user

**Additional info**
- Plugin version: 1.3.27
- Craft version: 3.4.30
- Multi-site: Yes

**Comment by engram-design** [comment]
Should be fixed in [1.3.28](https://github.com/verbb/navigation/releases/tag/1.3.28)
