### ISSUE TITLE
Node is wrongly active (similar urls but not equal)

### ISSUE THREAD

**Issue by nflorentin** [verbb/navigation#185]
Hi,

I know that this issue is a duplicate of #69 but I'm still encountering this issue in the plugin version 1.3.27.

I have two pages "notre-mission" and "notre-mission-parcours-phd". When I am on the page "notre-mission-parcours-phd", the node of the page "notre-mission" is active.

I think that a node **/page-a** should be active if **/page-a/page-b** is active but that should not be the case for **/page-a** and **/page-a-xxxx**, isn't it ?

Thanks in advance for your help

**Additional info**

- Plugin version: 1.3.27
- Craft version: 3.5.5
- Multi-site: Yes

**Comment by engram-design** [comment]
Should be fixed in [1.3.28](https://github.com/verbb/navigation/releases/tag/1.3.28)

**Comment by nflorentin** [comment]
Awesome!

Thank you very much 👍
