### ISSUE TITLE
Max Levels value doesn't do anything

### ISSUE THREAD

**Issue by missmatsuko** [verbb/navigation#19]
### Description
I set a value in the Max Values field for the menu in the CMS, but I'm able to add any number of nested items to the menu.

### Steps to reproduce

1. Create a new navigation. Set `Max Levels` to 1.
2. Add items to the new navigation. Add children to the top-level items. Add children to the children items. 

### Additional info

- Plugin version: 1.0.5
- Craft version: 3.0.20

**Comment by engram-design** [comment]
Fixed in [1.0.6](https://github.com/verbb/navigation/releases/tag/1.0.6)
