### ISSUE TITLE
Add ability to eager load relational fields on element

### ISSUE THREAD

**Issue by nixondesigndev** [verbb/navigation#191]
**What are you trying to do?**

I'd like the ability to eager load relational fields on element nodes e.g. an Asset Field on the `node.element`. In my experimentation it doesn't look like this is possible as the element query already has been executed. 

**What's your proposed solution?**

Perhaps this could be done in a similar way Craft handles image transforms with the [`withTransforms`](https://craftcms.com/docs/3.x/assets.html#withtransforms) param and then pass that to the query the plugin executes in the background.

```
craft.navigation.nodes
  .navId(1)
  .level(1)
  .with(['children'])
  .withElementFields([
    'assetFieldHandle',
    'children.assetFieldHandle'
  ])
.all()
```

You'd then access the field via `node.element.assetField[0]`.

Ideally as we are dealing with an image in this scenario, transforms could also be eager loaded along with other nested relational fields.

```
craft.navigation.nodes
  .navId(1)
  .level(1)
  .with(['children'])
  .withElementFields(['assetFieldHandle', { withTransforms: [{ width: 100, height: 100 }] }])
.all()
```

**Comment by MattWilcox** [comment]
+1 on this. I have a menu design where the menu itself is graphical, and uses a "backgroundImage" which is stored as an Asset on the element itself... at the moment, loading that is expensive.

**Comment by engram-design** [comment]
After chatting with the Craft crew about this, it's not possible at the moment, although it'd be great! We'll need to wait for eager-loading to support querying multiple element types. At the moment, it's just not possible to eager-load the element related to a node. https://github.com/craftcms/cms/issues/1820#issuecomment-479188472

**Comment by engram-design** [comment]
I'll mention that you can eager-load element fields you set on a node. For example an entries field with multiple entries (with handle `entries`).

```twig
{% set nodes = craft.navigation.nodes()
    .handle('mainMenu')
    .level(1)
    .with(['entries'])
    .all() %}

<ul>
    {% for node in nodes %}
        <li>
            {{ node.link }} 

            {% for entry in node.entries %}
                {{ entry.link }}
            {% endfor %}
```

But as for eager loading things on _that_ element, that's not possible due to being unable to eager-load [different element types](https://github.com/verbb/navigation/issues/212#issuecomment-1113964552). We are waiting on Craft to make that possible.

**Comment by MattWilcox** [comment]
Yeah, that's unfortunate. Thanks for looking into it, but this is a pretty big "gotcha" for performance.

**Comment by engram-design** [comment]
Yep, I hear ya! I'll be pushing for it a bit more with Brandon after Craft 4 to see if we can get somewhere...

**Comment by samuelreichor** [comment]
Any updates on that? We would love to have eagerloading for elements :)

**Comment by engram-design** [comment]
No update, sorry. Still waiting on Craft for this to be possible.
