### ISSUE TITLE
Add ability to disable editing navigation entirely for a site 

### ISSUE THREAD

**Issue by nixondesigndev** [verbb/navigation#192]
**What are you trying to do?**

We currently have a multisite site install where one of the navigations is shared across all sites so it doesn't make sense for the user to be able to edit the nodes per site / show the site menu. 

**What's your proposed solution?**

Much like how Sections work, Navigations should have the option to enable them per site. If a navigation is only enabled for one site, hide the site menu.

**Comment by engram-design** [comment]
Added in [1.4.0](https://github.com/verbb/navigation/releases/tag/1.4.0)
