### ISSUE TITLE
Homepage is always active on multisite 

### ISSUE THREAD

**Issue by nixondesigndev** [verbb/navigation#193]
**Description**

We have a multisite setup with the following URL structure:

- **Primary** example.com
- **Site A** example.com/site-a
- **Site B** example.com/site-b

We then have a navigation in Site A and Site B both of which have links to their respective homepage. We then output the nav for both Site A and Site B. So on Site A we show the nav for Site A and Site B. If on the homepage for Site A then `node.active` is true on both the homepage nodes for Site A and Site B.

**Steps to reproduce**

1. Set up 3 sites with URL structure above. 
2. Set up a Homepage single enabled across all three sites.
3. Set up a Global navigation.
4. For all three sites add a node for their respective homepages.
5. Set up template using below and navigation to homepage for site A.

Reduced test case

```
{% set nodesA = craft.navigation.nodes().navId(1).siteId(2).level(1).all() %}
{% set nodesB = craft.navigation.nodes().navId(1).siteId(3).level(1).all() %}

{% for node in nodesA %}
  {{ node.active ? 'Active' : 'Not active' }}
{% endfor %}

{% for node in nodesB %}
  {{ node.active ? 'Active' : 'Not active' }}
{% endfor %}
```

Both will show 'Active'.

**Additional info**
- Plugin version: 1.3.29
- Craft version: Craft Pro 3.5.10.1
- Multi-site: Yes 

**Additional context**

**Comment by engram-design** [comment]
Should be fixed in [1.3.30](https://github.com/verbb/navigation/releases/tag/1.3.30)
