### ISSUE TITLE
UrlHelper throws exceptions when URL is empty

### ISSUE THREAD

**Issue by gglnx** [verbb/navigation#194]
**Description**

If a navigation node has no URL `getActive()` throws an exceptions, because `UrlHelper::isRootRelativeUrl` only accepts strings, no null values.

**Steps to reproduce**
1. Create a manuel navigation node without URL
2. Check if current node is active.

**Additional info**
- Plugin version: 1.3.29
- Craft version: 3.5.11.1
- Multi-site: Yes

**Comment by engram-design** [comment]
Should be fixed in [1.3.30](https://github.com/verbb/navigation/releases/tag/1.3.30)
