### ISSUE TITLE
Ability for client to rename a heading for a menu

### ISSUE THREAD

**Issue by JayBox325** [verbb/navigation#196]
**What are you trying to do?**
We have a site with a four-column mega menu with their own mini-heading. We don't want to grant the client access to the Menu settings because they *could* edit the menu column, which would be problematic.

**What's your proposed solution?**
Adding a 'title' or 'menu heading' field for the client to edit would be great. But I think to go one further the ability to add custom fields at the Menu top level could be a great addition.

**Comment by engram-design** [comment]
I'm not sure I follow your request here sorry. What is a "mini-heading", just a manual node?

You could add your own [custom node type](https://verbb.io/craft-plugins/navigation/docs/developers/extending-elements#node-types) if you want them to be specialised? 

Maybe a screenshot or something to illustrate what you're thinking?

**Comment by JayBox325** [comment]
Thanks for getting back to me. I have a mega navigation, which as four columns of menu items. Below is an example from Adidas' website:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/13233809/94872010-5a587a80-0443-11eb-964f-49172545f988.png">

They have "Shoes", "Clothing" as column headings to title the list items below. We need headings to be added to our menus like this, but we don't want them to be links. They are headings only, so adding them as a node isn't working for our requirements. We'd like the option of adding a menu top-level field to give our menus titles.

It's a tricky one to describe!

**Comment by engram-design** [comment]
Ah, seems like a similar conversation to https://github.com/verbb/navigation/issues/183 where adding a "Heading" node type would be useful?

So normally, what we've done is have "Shoes", "Clothing", etc as a custom node type called "Heading" on the first level. Then, "Trainers", etc would be regular nodes (entry or otherwise) in the second level.

**Comment by JayBox325** [comment]
Yeah, I think a single 'heading' node type would be brilliant. Or the potential for a user to add custom fields to a Menu group. A menu might need a description or an image to accompany it, perhaps?

For now, I'm keen for just a 'heading' node type. If that isn't something that may happen soon, then I'll look at adding the custom node type as mentioned above. :)

**Comment by engram-design** [comment]
I suppose it depends what you consider a group - you mean the column in the above screenshot? If so, you can continue to use custom fields on your nodes, just like any other node. But custom fields aren't defined by type, so if you added a Plain Text field to your nodes, it'd be present on all nodes - Entries, Manual, etc. Probably not going to be a massive issue.

"Heading" is probably what I'm leaning a bit more towards, but you can 100% do this yourself right now with that link.

**Comment by JayBox325** [comment]
Cool. That's awesome that it's a consideration :) The site is going live at the end of October, so I'll probably set up a custom node for now. Thanks!

EDIT: Seen that I'll have to get to grips with file structures for creating/modifying craft with a module. 😂 Opportunities to learn always pop up when there's a deadline.

**Comment by engram-design** [comment]
Should be sorted with the "Passive" node in [1.4.0](https://github.com/verbb/navigation/releases/tag/1.4.0)
