### ISSUE TITLE
Cant change picture in linked assets

### ISSUE THREAD

**Issue by NickLanger1990** [verbb/navigation#197]
**Description**
If you want to change a picture of a linked asset you cant select a new image. Select is greyed out.
JS errors appear

` Uncaught TypeError: Cannot read property 'kind' of null`
`Uncaught TypeError: Cannot read property 'getSelectedElements' of null`

**Steps to reproduce**

1. Create a new entry of type assets.
2. Link a asset to it
3. Remove the linked asset and try to select a new one

**Additional info**
- Plugin version: 1.3.30
- Craft version: 3.5.11.1
- Multi-site: No

**Comment by engram-design** [comment]
I can't seem to replicate this, can you look at this video to ensure I'm replicating correctly? https://d.pr/v/zozDvQ

**Comment by NickLanger1990** [comment]
Not sure if there is much of a difference. Recorded mine as well.
https://www.youtube.com/watch?v=RM82AR57Zi4&feature=youtu.be

**Comment by engram-design** [comment]
Thanks for the video, very odd. I'll see what I can uncover...

**Comment by engram-design** [comment]
Closing due to age
