### ISSUE TITLE
hasDescendents or similar parameter for node

### ISSUE THREAD

**Issue by howells** [verbb/navigation#2]
It would be superb if there was way to identify whether a current node has any children, unless there is already?

**Comment by engram-design** [comment]
Sure, `hasDescendants` exists already:

```
<ul>
    {% for node in nodes %}
        <li>
            {{ node.link }}

            {% if node.hasDescendants %}
                <ul>
                    {% for subnode in node.children %}
                        <li>{{ node.link }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endfor %}
</ul>
```

Will update the docs accordingly.

**Comment by howells** [comment]
As I was using the nav tag - I should have been able to work that out ;-) 

Thanks.

**Comment by kojint** [comment]
It would be great if @engram-design 's answer was indeed added to the docs. This was also a solution to my needs, and seems like it might be fairly standard for anyone wanting to implement more detail on children that the {% children %} tag doesn't cater for.

**Comment by engram-design** [comment]
@kojint I've added this section to the main readme for clarity.
