### ISSUE TITLE
Sub-nav items containing the same first url segment both assigned as active

### ISSUE THREAD

**Issue by jamielaughton** [verbb/navigation#20]
### Description
Sub Nav items containing the same first url segment both get assigned as active when using {% if subnode.active %} e.g when 'seg-1/example-2' is active as is '/seg-1/example' it doesnt happen the other way around.

### Additional info

- Plugin version: 1.0.5
- Craft version: 3.0.20

**Comment by engram-design** [comment]
Should be fixed in [1.0.6](https://github.com/verbb/navigation/releases/tag/1.0.6)
