### ISSUE TITLE
special characters in target's slug

### ISSUE THREAD

**Issue by codedesign** [verbb/navigation#200]
- Plugin version: 1.3.31
- Craft version: 3.5.11.1

As soon as a target has a special character in it's slug the "active" state is lost for it self and it's parent nodes. For example:

Works fine and all "**active**" stats are correct:
**1. slug-a** 
1.1 slug-a-a
**1.2 slug-a-b**
1.2.1 slug-a-b-a
**1.2.2 slug-a-b-b**
1.2.3 slug-a-b-é
1.3 slug-a-c

All "**active**" stats are lost:
**1. slug-a** 
1.1 slug-a-a
**1.2 slug-a-b**
1.2.1 slug-a-b-a
1.2.2 slug-a-b-b
**1.2.3 slug-a-b-é**
1.3 slug-a-c

As soon as you change the target slug from slug-a-b-**é** to slug-a-b-**c** it would work fine. Let me know if you need any further explanation.

**Comment by engram-design** [comment]
Fixed in [1.4.0](https://github.com/verbb/navigation/releases/tag/1.4.0)

**Comment by HOMMinteractive** [comment]
Thank you!
