### ISSUE TITLE
Issues and bugs when creating/using new node types

### ISSUE THREAD

**Issue by terryupton** [verbb/navigation#202]
**Description**
Firstly, I am not sure if this is a 'bug' or a 'feature request'...This is the first time using Navigation plugin, so apologies if I have overlooked something.

I have followed along with the docs here:
https://verbb.io/craft-plugins/navigation/docs/developers/extending-elements#node-types
and this thread
https://github.com/verbb/navigation/issues/183
to create a new node type called Heading. I am using this for several navigations (mega menus and footer).

I followed along with the docs and have the ability now to add a heading node. However, I have noticed a few bugs as follows:

1. It defaults to 'Entry' when you click the settings icon for the node.
2. There are settings/options showing that should be excluded and that were excluded in the initial node creation if the modules file.
3. There is no label showing on the nodes, in the menu structure.

To cover these points in more detail with screenshots:

Points 1 and 2. 
<img width="449" alt="Screenshot 2020-10-14 at 16 18 48" src="https://user-images.githubusercontent.com/5698596/96010154-6710a180-0e39-11eb-8ff8-b2bdf2baeb03.png">
<img width="1572" alt="Screenshot 2020-10-14 at 16 06 40" src="https://user-images.githubusercontent.com/5698596/96010205-755ebd80-0e39-11eb-883a-22a979e9d42b.png">

When you click the cog on the node settings the settings dialogue box appears. this reverts back to 'Entry' as the default option. I am also seeing settings for the URL, the classes, open in new window and attributes (maybe this should remain).  
I think that these shouldn't appear based on the settings I have set for the new node type.

Point 3. 
<img width="1572" alt="Screenshot 2020-10-14 at 16 06 40" src="https://user-images.githubusercontent.com/5698596/96010205-755ebd80-0e39-11eb-883a-22a979e9d42b.png">
It looks like this is related to the point 1 and if you edit the node and re-choose 'Heading' then this updates on the structure as you will see from the screenshot above. One is blank and one is correct.

Perhaps, I have not added the code correctly, and TBF my php and module understand is minimal, so I am not sure if these are bugs or I need to add some more code? 

```
<?php

namespace modules;

use verbb\navigation\base\NodeType;
use verbb\navigation\services\NodeTypes;
use verbb\navigation\events\RegisterNodeTypeEvent;
use yii\base\Event;

class NavigationHeading extends NodeType
{
  public static function displayName(): string
  {
    return 'Heading';
  }

  public static function hasUrl(): bool
  {
    return false;
  }
}

Event::on(NodeTypes::class, NodeTypes::EVENT_REGISTER_NODE_TYPES, function (RegisterNodeTypeEvent $event) {
  $event->types[] = NavigationHeading::class;
});
```

**Comment by engram-design** [comment]
This is a known bug/issue for sure, so nothing you're doing wrong. It really comes down to better handling of toggling field options depending on what node type you're picking. I just haven't had the opportunity to improve this, so there's a lack of conditional handling here.

I'll double check your point 1. though, this might just be an issue with resolving custom node types.

I'll keep you posted!

**Comment by engram-design** [comment]
Firstly, a Passive node type has been added in [1.4.0](https://github.com/verbb/navigation/releases/tag/1.4.0), and your other issues should be fixed as well. Let me know if not, but I also tested with your exact setup (which is fine), and working well for me.
