### ISSUE TITLE
Entries not keeping the order they are picked/selected when adding multiple entries

### ISSUE THREAD

**Issue by terryupton** [verbb/navigation#203]
**Description**
As the description says. I choose entries in a certain order, but these are not keeping this order when actually been populated and added to the navigation, so then i have to re-order the items again into the correct order.

This seems to work ok for any native picking of entries etc.

**Steps to reproduce**
1. Add Entry
2. Choose multiple entries in a certain order
3. The order of the items added to the navigation changes.

**Additional info**
- PHP Version: 7.3.23
- Plugin version: 	1.3.31
- Craft version: Craft Pro 3.5.11.1
- Multi-site:  N
- Propagate nodes: No

**Comment by engram-design** [comment]
I myself have noticed this happen on a few occasions, but couldn't quite reproduce it effectively. I'll look into it again.

**Comment by engram-design** [comment]
Should be fixed in [1.4.0](https://github.com/verbb/navigation/releases/tag/1.4.0). You should also notice a performance boost when adding new nodes.
