### ISSUE TITLE
Nodes not reflecting the correct order on the front-end as per the backend order

### ISSUE THREAD

**Issue by terryupton** [verbb/navigation#204]
**Description**
Nodes getting mixed up and not reflective on the front-end as per the structure in the back-end.
I have not figured out any pattern to this. I cannot get it to update. Even changing the order doesn't update it.
The only way I have found it will work is to add each item one at a time and to remove the node and start again, by adding each item one at a time.

**Front-end**
<img width="1679" alt="Screenshot 2020-10-15 at 13 07 12" src="https://user-images.githubusercontent.com/5698596/96121253-b9100080-0ee7-11eb-9e1c-ab1956ed102a.png">
<img width="1662" alt="Screenshot 2020-10-15 at 13 07 16" src="https://user-images.githubusercontent.com/5698596/96121259-bb725a80-0ee7-11eb-833f-eddb5578bada.png">
<img width="1662" alt="Screenshot 2020-10-15 at 13 07 26" src="https://user-images.githubusercontent.com/5698596/96121261-bca38780-0ee7-11eb-9e3f-8d36da26185b.png">

**Backend**
<img width="1081" alt="Screenshot 2020-10-15 at 13 08 55" src="https://user-images.githubusercontent.com/5698596/96121268-bf05e180-0ee7-11eb-8ac6-a827fe9e28e5.png">
<img width="1086" alt="Screenshot 2020-10-15 at 13 09 07" src="https://user-images.githubusercontent.com/5698596/96121308-ce852a80-0ee7-11eb-8fc0-d69eaa67e564.png">

**Steps to reproduce**
1. Added entries and ordered them into a specific order
2. Not reflecting the same on the front-end

**Comment by terryupton** [comment]
Further to this @engram-design - I think this is very much related to the previous bug #203 with the nodes added in a random order. it seems that this is then fixing this order for the menu and nothing can undo it.
I bypassed this by creating the whole mega menu again from scratch adding one item at a time and moving down the levels.

**Comment by engram-design** [comment]
That's pretty odd behaviour. I don't suppose you refreshed the page in between just to ensure it's not something odd with the JS? I'm reasonably confident this should be fixed in [1.4.0](https://github.com/verbb/navigation/releases/tag/1.4.0) though.
