### ISSUE TITLE
Child items come back in the wrong order in GraphQL

### ISSUE THREAD

**Issue by clowerweb** [verbb/navigation#206]
**Description**
We (Foster Commerce) found an issue where item children are not coming back in the order they were placed in Craft admin, when the results are coming from GraphQL.

![preview-full-image](https://user-images.githubusercontent.com/885727/96508881-3e1d5180-1229-11eb-86cf-3a5229d437db.png)
![preview-full-image (1)](https://user-images.githubusercontent.com/885727/96508888-407fab80-1229-11eb-9a2c-628109df32d5.png)

**Steps to reproduce**
1. Create a navigation with an item that has children (those children may also have children in our case)
2. Arrange the children in a custom order
3. Query the navigation with GQL and ensure the order of the child items is retained

**Additional info**
- Plugin version: 1.3.31
- Craft version: 3.5.13.2
- Multi-site: Yes
- Propagate nodes: Yes or No (unsure - how do I check this?)

**Additional context**
Here is our query:
```
nodes(site: "${site}", navHandle: "maxonPrimaryNavigation", level: 1) {
	id,
	title,
	url,
	newWindow,
	children {
		id,
		title,
		url,
		newWindow,
		children {
			id,
			title,
			url,
			newWindow
		}
	}
}
```

**Comment by clowerweb** [comment]
Edited to add additional context about the query.

**Comment by clowerweb** [comment]
This actually ended up being related to a GQL cache issue after the client had rearranged the order of the items in the sub-menu.

**Comment by engram-design** [comment]
Thanks for the investigation here, and good to know. I'll investigate what we can do, if anything to prevent that.

**Comment by clowerweb** [comment]
> Thanks for the investigation here, and good to know. I'll investigate what we can do, if anything to prevent that.

Thanks Josh! Is there a way you can invalidate the GQL cache when the order of the items is updated?

**Comment by engram-design** [comment]
It's more than even if there's a way, it has to be _just_ for the navigation plugin, or the navigation in question. Clearing the entire GQL cache each time you update a node seems pretty heavy-handed, and something I'd rather avoid.

**Comment by mikeebee** [comment]
@clowerweb @engram-design I'm having the same issue here, the children come out in order of the IDs from what I can see.

I have invalidated GraphQL queries and template caches as well as cleared all the other caches but I'm still not seeing the order output as expected. Any tips?

Plugin version: 1.3.31 (Same as @clowerweb)
Craft version: 3.5.13.2

**Comment by engram-design** [comment]
Hmmm, my first comment might be to update to Craft 3.5.15.1 (or later), but I can't guarantee that'll fix anything, as I don't see anything in the changelog.

I've tried for almost an hour to get it to _not_ work for me. Each time I re-order items, no matter what level (I've tested 4-levels deep), the correct order is output.

I am testing using the GQL API Explorer in Craft itself. I'm not sure if you're testing in a real-world scenario? I'm not sure if calling form the CP causes it's cache to act differently. I would suggest so, as each time I change the order of items, there seems to be a delay returning the query (the result being re-queried I suppose).

I might have a chat to @andris-sevcenko to see if there's anything obvious.

**Comment by andris-sevcenko** [comment]
@engram-design 

> It's more than even if there's a way, it has to be _just_ for the navigation plugin, or the navigation in question. Clearing the entire GQL cache each time you update a node seems pretty heavy-handed, and something I'd rather avoid.

Navigation items are not element queries, so element query tag caching cannot be applied here. This means, that the query results will get cached (if caching is enabled) until the cache gets flushed. So.

So,
a) flush GQL caches after modifying nav item order
b) roll your own caching solutions by listening to [EVENT_BEFORE_EXECUTE_GQL_QUERY](https://github.com/craftcms/cms/blob/develop/src/services/Gql.php#L441-L453) and then setting the `result` property.
c) 
  - Listen to EVENT_BEFORE_EXECUTE_GQL_QUERY
  - disable caching, if they are querying navigation items
  - listen to `EVENT_AFTER_EXECUTE_GQL_QUERY` and turn caching back on, if it was enabled before.

**Comment by engram-design** [comment]
@andris-sevcenko Navigation nodes _are_ elements though (not element queries I suppose), does that matter?

But thanks, I'll give that a go to see if it'll help anyone.

**Comment by andris-sevcenko** [comment]
@engram-design Ah, then Craft's element tag caching should apply here. If you've tested this with GraphQL caching enabled and reordering the navigation nodes also updates the query result, then it's likely to be environmental.

**Comment by mikeebee** [comment]
Thanks for looking into this for me, I've verified that it's working fine from GraphQL Playground hooked to the API so it must be something to do with my environment. As such, I can't really expect for you to try and replicate to fix this but if you think there is an angle that can be explored then great :)

Just FYI I'm using [NextJS with SSR](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation).

If I recreate the child navs it works ok but re-ordering is still a no go.

**Comment by engram-design** [comment]
Hmmm, I might try and spin up an example, or get a colleague to give me a hand with this. @andris-sevcenko does this make any difference, or comes down to something with the NextJS setup somehow not realising the content has changed?

**Comment by andris-sevcenko** [comment]
According to @mikeebee it sounds like NextJS is just caching more aggressively than it ought to - especially if the results are correct when querying the content directly.

**Comment by cyponthemic** [comment]
Hello, I can reproduce the error with Appollo + nuxt.js. Weird caching issues that seems to be only occurring with the latest version of Craft. I don't exactly when it started to happened but two of my sites on 3.5.16 are having the issues.

Goes beyond reordering in my case, adding items, deleting the whole nav... changes are not coming through in the frontend but they come out perfectly in the explorer. 

Do you have any idea what it could be? Let me know if I should add a new issue. 

In advance thanks,
Alex Chavet

**Comment by cyponthemic** [comment]
Fix by the latest version thanks
