### ISSUE TITLE
Add node types based on every element that has title and URL

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#208]
Example use case:
I recently installed "commerce bundles" plugin, but there was no separate "bundles" node type in Verbb nav. So I assume that element-based nodes are hardcoded and I would need to write a plugin to add a new "bundle" node type.
How about just checking for all additional elements added by plugins and automatically adding new node type for each element that has URL and Title?

**Comment by engram-design** [comment]
Potentially, but this could get pretty out of hand on large sites. Might require some UI adjustments.

**Comment by piotrpog** [comment]
@engram-design 
To prevent such issues, there might be global plugin settings that would enable/disable these additional nodes. And by default additional nodes would be all disabled.

**Comment by engram-design** [comment]
Added in [1.4.2](https://github.com/verbb/navigation/releases/tag/1.4.2)

**Comment by piotrpog** [comment]
@engram-design thanks!
