### ISSUE TITLE
Issue with Icon Picker overflow

### ISSUE THREAD

**Issue by engram-design** [verbb/navigation#209]
![Screen Shot 2020-10-21 at 11 39 28 am](https://user-images.githubusercontent.com/1221575/96659629-206bfb80-1393-11eb-8eb1-6cda7187a8aa.png)

**Comment by engram-design** [comment]
Can't actually reproduce this anymore, see 
<img width="414" alt="Screen Shot 2020-11-03 at 8 41 28 pm" src="https://user-images.githubusercontent.com/1221575/97970048-0ad7e680-1e15-11eb-97e6-67f19f352470.png">

**Comment by proimage** [comment]
It's happening to me... 🤷‍♂️

**Comment by engram-design** [comment]
Fixed in [1.4.20](https://github.com/verbb/navigation/releases/tag/1.4.20)
