### ISSUE TITLE
Add getActiveNode Method

### ISSUE THREAD

**Issue by NixonGit** [verbb/navigation#21]
This method would be helpful when outputting a secondary level of navigation that isn't within the main navigation loop, for example top level navigation in the header and sidebar would show the children of the currently active parent.

```
{% set nodes = craft.navigation.getActiveNode() %

{% nav nodes in nodes %}
   {{ node.link }}	
{% endnav %}
```

**Comment by engram-design** [comment]
Added in [1.0.6](https://github.com/verbb/navigation/releases/tag/1.0.6). Please note the following syntax:

{# Represents a Node element #}
{% set activeNode = craft.navigation.getActiveNode() %}

<ul>
    {% nav node in craft.navigation.nodes({ descendantOf: activeNode }).all() %}
        <li>
            {{ node.link }}

            {% ifchildren %}
                <ul>
                    {% children %}
                </ul>
            {% endifchildren %}
        </li>
    {% endnav %}
</ul>
