### ISSUE TITLE
Show URL in backend for entries, etc

### ISSUE THREAD

**Issue by proimage** [verbb/navigation#210]
**What are you trying to do?**
When creating or editing a Navigation, it would be handy to be able to see the actual URL (or URI) that will be generated for each node. For example, if I have a couple of entries with similar titles, but the context is entirely different (eg. different parent entries in a Structure), there's no way to tell which one to pick or if I picked the right one.

**What's your proposed solution?**
If the URL/URI for each node was shown in the list when editing navigations, it would entirely solve the issue for me.

**Additional context**
![image](https://user-images.githubusercontent.com/1027523/97001100-7c27b780-1540-11eb-9775-45834b8938a7.png)

**Comment by engram-design** [comment]
This will require more of a layout re-work to deal with nested nodes and long titles of nodes. There's plenty of room on your example due to a large screen.

The other option could include hovering over node, or showing the resulting URL/URI in the edit modal window. Currently, you can only see the linked entry, not the URL it's using.

**Comment by proimage** [comment]
Either (any?) of those solutions works for me; the exact UI isn't the point, but the information presented therein. ;) Heck, even showing the URI "appended" to the end of the title (on hover or permanent, doesn't matter), in a lighter grey or something, would be great. 👍

**Comment by engram-design** [comment]
Added in [1.4.2](https://github.com/verbb/navigation/releases/tag/1.4.2). You can hover over the "entry" text on the right, or see it in the modal when editing a node.
