### ISSUE TITLE
All elements have a `class=" "` attribute even if empty

### ISSUE THREAD

**Issue by proimage** [verbb/navigation#211]
**Description**
Using the basic render code `{{ craft.navigation.render('nav_name') }}`, the generated content shows the `ul`, `li`, and `a` elements all with empty `class="  "` elements:

```
<ul class="" ><li class=" " ><a  class=" " >...</a></li></ul>
```

**Steps to reproduce**
1. Render any navigation using `craft.navigation.render()`
2. Look at the generated code.

**Additional info**
- Plugin version: 1.4.1
- Craft version:  3.5.12.1
- Multi-site: No
- Propagate nodes: Not sure. Guessing this is irrelevant for this issue?

**Comment by engram-design** [comment]
Fixed in [1.4.2](https://github.com/verbb/navigation/releases/tag/1.4.2)
