### ISSUE TITLE
Add support for gatsby-source-craft

### ISSUE THREAD

**Issue by alexhillel** [verbb/navigation#214]
**What are you trying to do?**
To be able to access navigation data through the new [gatsby-source-craft](https://github.com/craftcms/gatsby-source-craft) plugin.

**What's your proposed solution?**
I'm not sure, but Andris referenced [this](https://github.com/craftcms/gatsby-helper/blob/main/src/services/SourceNodes.php#L34-L55) in Discord, and also said "the issue with Navigation is that one field it exposes over GraphQL returns ElementInterface... In Navigation's specific case my recommendation would be think about how to limit that to a union of several types".

**Comment by engram-design** [comment]
I'll have to look into this and report back!

**Comment by engram-design** [comment]
@andris-sevcenko might like to chime in on this one.

**Comment by engram-design** [comment]
Added in [1.4.12](https://github.com/verbb/navigation/releases/tag/1.4.12)
