### ISSUE TITLE
Requirements feed-me

### ISSUE THREAD

**Issue by hhhc** [verbb/navigation#215]
Hi,

just wanted to update to the latest version and I always got an error.
Exception 'Error' with message 'Class 'craft\feedme\services\Elements' not found'

I found out that I had to manually do

composer require craftcms/feed-me

but I guess you could require that automatically.

**Comment by engram-design** [comment]
There are checks in place to ensure that Feed Me related code is only run if Feed Me is installed and enabled. Feed Me isn't a requirement for the Navigation plugin. My tests show on a fresh install (without Feed Me installed) I don't receive this error.

**Comment by hhhc** [comment]
That is weird because I did not have that installed and I could not upgrade without it. Well, feedme does not hurt and so I keep that installed.

**Comment by engram-design** [comment]
Hmmm, I'll keep an eye on this, as I'd rather not have this issue, yet no other reports of it just yet.

**Comment by engram-design** [comment]
Should be properly fixed in [1.4.5](https://github.com/verbb/navigation/releases/tag/1.4.5)
