### ISSUE TITLE
Configuration Permissions not working correctly on version 1.4.2

### ISSUE THREAD

**Issue by jlachancekffein** [verbb/navigation#217]
**Description**
In the configuration of a navigation item, saving permissions does not work correctly.

We had created the navigations with the version of the plugin 1.3.x.

Now after the update we no longer had access to edit the related sites. So, I noticed that we now had to configure the sites used by the navigation. This works fine.

However, we no longer have the option of adding entrees as a menu type. So in the setup I check the lightswitch Show Entries. No error is showing. On the other hand, the modifications are not saved. The entries are not displayed in the navigation management and when I return to the permissions configuration, the option is not checked.

So, we no longer have access to manage navigation properly.

I tried to revert to version 1.3.x of the plugin, but the navigation management returns an error. So no way to go back.

I tried to create a new navigation item and the problem persists.

**Steps to reproduce**
1. Create a navigation item with the 1.3.x plugin version
2. Update plugin to version 1.4.2
3. Click on Edit Settings of the navigation item menu
4. Click on Permissions tab
5. Enable Show Entries lightswitch
6. Save the settings
7. Return on settings page
8. Validate that the options are saved correctly

**Additional info**
- Plugin version: 1.4.2
- Craft version: 3.5.15
- Multi-site: Yes
- Propagate nodes: Yes

**Additional context**
After additionnal research, I dump the bodyparam request of the settings.

```php
    'craft\\elements\\Entry' => [
        'enabled' => ''
        'permissions' => '*'
    ]
    'craft\\elements\\Category' => [
        'enabled' => ''
        'permissions' => '*'
    ]
    'craft\\elements\\Asset' => [
        'enabled' => '1'
        'permissions' => '*'
    ]
    'craft\\elements\\Tag' => [
        'enabled' => ''
        'permissions' => '*'
    ]
    'verbb\\navigation\\nodetypes\\PassiveType' => [
        'enabled' => '1'
    ]
    'verbb\\navigation\\nodetypes\\SiteType' => [
        'enabled' => '1'
    ]
    'custom' => [
        'enabled' => '1'
    ]
]
```

I delete /storage/runtime folder but with no luck.

**Comment by engram-design** [comment]
> On the other hand, the modifications are not saved

Can you clarify this? As in, you go to the Permissions of a navigation, toggle the "Show Entries" lightswitch, save, and when returning, the value isn't persisted?

Are you able to check your `config/project/navigation/navs/` folder for any changes? There should be a section for `permissions`.

Do you have any other node types to pick from like categories? Is this just effecting entries, or other elements too?

When you first went to check the permission settings for the navigation, can you recall if the lightswitch was on or off?

The update from 1.3.x to 1.4.x was supposed to be backwards-compatible, so that Entries/Categories/etc would already be enabled. The same goes for the site settings.

**Comment by engram-design** [comment]
Just saw your latest addition, where you mention dumping the bodyparam. Can you point be to where you added this?

**Comment by engram-design** [comment]
Out of interest, do you see the following when toggling the lightswitch, while inspecting? https://d.pr/v/DZtbQE

It seems strange the data isn't containing the values for enabled.

**Comment by jlachancekffein** [comment]
> Can you clarify this? As in, you go to the Permissions of a navigation, toggle the "Show Entries" lightswitch, save, and when returning, the value isn't persisted?

Exactly

> Are you able to check your config/project/navigation/navs/ folder for any changes? There should be a section for permissions.

Here what's it look like
```php
handle: footer_right
instructions: ''
maxNodes: ''
name: 'Footer (droite)'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: ''
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagateNodes: false
siteSettings:
  8b18c442-984e-495c-9456-02ab36e11474:
    enabled: '1'
  96bbd2e1-0e9f-4e6e-b875-8a5fd0d65167:
    enabled: '1'
sortOrder: 3
structure:
  maxLevels: '1'
  uid: 9d222442-0fed-4db5-9bac-bc767cfbeda2
```

> Do you have any other node types to pick from like categories? Is this just effecting entries, or other elements too?

We not need the categories, but it not saved correctly too.


> When you first went to check the permission settings for the navigation, can you recall if the lightswitch was on or off?

Not 100% sure but think it was off.

**Comment by jlachancekffein** [comment]
> Just saw your latest addition, where you mention dumping the bodyparam. Can you point be to where you added this?

/vendor/verbb/navigation/src/controllers/NavsController.php
actionSaveNav()

**Comment by engram-design** [comment]
Do you see the following when toggling the lightswitch, while inspecting? https://d.pr/v/DZtbQE

**Comment by jlachancekffein** [comment]
> Out of interest, do you see the following when toggling the lightswitch, while inspecting? https://d.pr/v/DZtbQE
It seems strange the data isn't containing the values for enabled.

It's really weird because I see exactly what you mean in the DOM. The value is updated to 1 when I enabled the lightswitch. But, when I dump the data, the value stay empty string.

But i succeeded to fix my problem with the information you give me with the project-config.

I edit directly the value of the navigation/navs to replace the empty string for 1 and ./craft project-config/apply --force.

Now it work. I really don't know why. I suspect something somewhere in our code.

But I want to thank you for your help. It is really appreciated.

**Comment by jlachancekffein** [comment]
Wow. Now I understand. The settings are duplicate. Here :

![image](https://user-images.githubusercontent.com/24896469/98822425-d65cbf80-23fe-11eb-945d-d49773e28e7c.png)

```<input type="hidden" name="permissions[craft\elements\Entry][enabled]" value="">``` is here two time.

So the last one is always empty.
