### ISSUE TITLE
Ability to add active class to render function

### ISSUE THREAD

**Issue by mediabeastnz** [verbb/navigation#22]
### Description
It would be amazing if you could simply pass an additional class name to the render function to handle the current page/active links.

e.g.
```
{{ craft.navigation.render('navHandle', {
    ulClass: 'nav-items',
    liClass: 'nav-item',
    aClass: 'nav-link',
    activeClass: 'nav-active',
}) }}
```

**Comment by engram-design** [comment]
Sure thing, added in [1.0.6](https://github.com/verbb/navigation/releases/tag/1.0.6)
