### ISSUE TITLE
Field Overrides from Craft 3.5 Not Displaying

### ISSUE THREAD

**Issue by bfopma** [verbb/navigation#221]
**Description**
Craft 3.5 introduced the ability to override the default field labels and instructions:

![image](https://user-images.githubusercontent.com/6729531/100261227-0c766500-2f10-11eb-96c7-627194794df3.png)

However, the default instructions are being displayed to the author:

![image](https://user-images.githubusercontent.com/6729531/100261394-4ba4b600-2f10-11eb-85fe-628a157cddfe.png)

**Steps to reproduce**
1. Add custom field instructions to one or more fields under the Node Fields -> Field Layout section
2. View the custom field from within the Navigation entry

**Additional info**
- Plugin version: 1.4.3
- Craft version: 3.5.16
- Multi-site: Yes
- Propagate nodes: Yes

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.4.4](https://github.com/verbb/navigation/releases/tag/1.4.4)
