### ISSUE TITLE
Disabled node types are shown in HUD 

### ISSUE THREAD

**Issue by gglnx** [verbb/navigation#223]
**Description**

When editing a navigation node, the type dropdown in the HUD shows all types including disabled ones.

<img width="239" alt="Bildschirmfoto 2020-11-30 um 14 15 06" src="https://user-images.githubusercontent.com/23519/100614998-446a1780-3317-11eb-9f01-02aa6e19818c.png">

**Steps to reproduce**
1. Disable some types
2. Edit a navigation node

**Additional info**
- Plugin version: 1.4.4
- Craft version: 3.5.16
- Multi-site: Yes
- Propagate nodes: No

**Comment by engram-design** [comment]
Fixed in [1.4.5](https://github.com/verbb/navigation/releases/tag/1.4.5)
