### ISSUE TITLE
Editing a Custom URL nav item sets value of dropdown automatically to Entries

### ISSUE THREAD

**Issue by frontedbe** [verbb/navigation#225]
**Description**
Editing a Custom URL nav item sets value of dropdown automatically to Entries
[view screenshot](https://share.getcloudapp.com/8LunJYJZ)

**Additional info**
- Plugin version: 1.4.5
- Craft version: 3.5.16
- Multi-site: Yes
- Propagate nodes: Yes

**Comment by engram-design** [comment]
Duplicate of https://github.com/verbb/navigation/issues/226
