### ISSUE TITLE
Site permissions are ignored

### ISSUE THREAD

**Issue by gglnx** [verbb/navigation#227]
**Description**

`getEditableSites()` (in `src/Models/Nav.php`) should use `Craft::$app->getSites()->getEditableSites()` instead of `Craft::$app->getSites()->getAllSites()` to respect site permissions per user.

**Steps to reproduce**
1. Create two sites, a navigation and an user which has only access to the second site.
2. Open a navigation, all sites can be seen and edited

**Additional info**
- Plugin version: 1.4.7
- Craft version: 3.5.16
- Multi-site: Yes
- Propagate nodes: No

**Comment by engram-design** [comment]
Should be fixed in [1.4.8](https://github.com/verbb/navigation/releases/tag/1.4.8)
