### ISSUE TITLE
Release 1.4.6 requires craftcms/cms ^3.5.0

### ISSUE THREAD

**Issue by bgrrtt** [verbb/navigation#229]
**Description**

Navigation 1.4.6 uses `EVENT_REGISTER_GQL_SCHEMA_COMPONENTS`, which was added in Craft CMS 3.5.0. 

https://github.com/craftcms/cms/blob/3.5/src/services/Gql.php#L190:L195

**Steps to reproduce**
1. Bump `"verbb/navigation": "1.4.5",` to `"verbb/navigation": "1.4.6",` in composer.json
2. Run `composer update`
3. Visit CP

<img width="1062" alt="Screen Shot 2020-12-09 at 1 58 50 PM" src="https://user-images.githubusercontent.com/13173779/101674856-05c71200-3a27-11eb-897a-8482d3b62ad1.png">

**Additional info**
- Plugin version: 1.4.5 -> 1.4.6
- Craft version: 3.4.30
- Multi-site: No

**Additional context**

https://github.com/verbb/navigation/compare/1.4.5...1.4.6

**Comment by engram-design** [comment]
Completely slipped past me on this plugin, as I was updating a number of out other plugins at the same time. Fixed in [1.4.8](https://github.com/verbb/navigation/releases/tag/1.4.8)
