### ISSUE TITLE
Allow nodes without URLs

### ISSUE THREAD

**Issue by timkelty** [verbb/navigation#23]
A nav may have a level of hierarchy only for display/grouping, with no actual URL to reflect.

Possible Approaches:

- un-require `url` from the "Custom" type
- make a new node type of "Group" (or something similar) that has no URL field.

**Comment by engram-design** [comment]
There's no notion of link types just yet other than element or not (there might be soon). Gone with the simple route of un-requiring the url. You could also always use a dummy character like `#`.

Changed in [1.0.6](https://github.com/verbb/navigation/releases/tag/1.0.6)

**Comment by timkelty** [comment]
Thanks!
