### ISSUE TITLE
New nodes are always saved to all sites

### ISSUE THREAD

**Issue by gglnx** [verbb/navigation#231]
**Description**

This [commit](https://github.com/verbb/navigation/commit/07d73cd636a31e889c44212f85f1c44ce3cb4764#diff-9ced2e33eb929c9682104678a1b5027317c59713e065c244ce19b4e2d93918d4R430) overwrites always `$siteIds` :(

**Steps to reproduce**
1. Create a navigation with disabled propagation
2. Create a new node, it will be saved to every site

**Additional info**
- Plugin version: 1.4.9
- Craft version: 3.5.17.1
- Multi-site: Yes
- Propagate nodes: No

**Comment by engram-design** [comment]
Ah, silly mistake on my part. Should be fixed in [1.4.10](https://github.com/verbb/navigation/releases/tag/1.4.10)
