### ISSUE TITLE
Node Editor 500 Error

### ISSUE THREAD

**Issue by jarheadcore** [verbb/navigation#232]
**Description**
500 Error when trying to edit node

**Steps to reproduce**
1. Add entry to navigation
2. Click on "gear icon" trying to open the editor

**Additional info**
- Plugin version: 1.4.9 / latest
- Craft version: 3.4.30
- Multi-site: No
- Propagate nodes: No

**Additional context**

![image](https://user-images.githubusercontent.com/11466445/102629998-3fe19380-414c-11eb-9aea-149e132c7ee1.png)

**Comment by engram-design** [comment]
Are you able to click on the POST request (above that line), which should take you to the Network tab in your developer tools. You should then click on the Preview tab with the request highlighted. That should give us a bit more information on the specific error.

**Comment by engram-design** [comment]
Closing due to age.
