### ISSUE TITLE
If first site is disabled, navigation page cannot be opened

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#233]
I have multiple sites on my craft install. First one was disabled in control panel. This caused this error appearing when i try to enter control panel page of navigation which is not enabled/disabled on any specific site:

```
Undefined offset: 0
```

Errors appears in file `vendor/verbb/navigation/src/controllers/NavsController.php` on line 76.

**Comment by engram-design** [comment]
What version are you on? This line number doesn't correspond with the [latest branch](https://github.com/verbb/navigation/blob/craft-3/src/controllers/NavsController.php#L76).

I would say it refers to https://github.com/verbb/navigation/blob/craft-3/src/controllers/NavsController.php#L87 which shouldn't be an issue.
