### ISSUE TITLE
Multisite propagation to sites in group only

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/navigation#236]
Right now there is only an option to propagate nodes to all enabled sites or don't propagate. 

Like sections it would be handy to have the option to propagate to enabled sites in the same group.

**Comment by maxstrebel** [comment]
I'd like to add my +1.

As Craft's localization is supposed to be Site Group A -> de / en / es / ... this would be the way to have separate navigations for separate sites but localized navigation in the group.

Or is there a better way to get localized navs in a multi-site setup?

**Comment by engram-design** [comment]
Added the ability to set the "Propagation Method" on navigations for the next release, similar to sections. To get this early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by maxstrebel** [comment]
Hey @engram-design, starting christmas two months early, but I celebrate it ❤️

**Comment by engram-design** [comment]
Added in [2.0.9](https://github.com/verbb/navigation/releases/tag/2.0.9)
