### ISSUE TITLE
Clear nodes removing from wrong site

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/navigation#237]
**Description**
When using the "Clear nodes" option it removes from the primary site, not the selected site.

**Steps to reproduce**
1. Have a multi site
2. Select a no primary site
3. Use the Settings -> Clear nodes button
4. All primary site nodes are gone, but the actually selected site still has all the nodes

**Additional info**
- Plugin version: 1.4.10
- Craft version: 3.5.17.1
- Multi-site: Yes
- Propagate nodes: No

**Comment by engram-design** [comment]
Fixed in [1.4.12](https://github.com/verbb/navigation/releases/tag/1.4.12)
