### ISSUE TITLE
Disabling propagation clears navigation sub levels

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/navigation#238]
**Description**
When disabling the propagation in a navigation with multiple levels it resets all sub levels to the root.

**Steps to reproduce**
1. Navigation with propagation enabled
2. Add some sub level nodes
3. Disable propagation
4. All sub levels are now resaved to root

**Additional info**
- Plugin version: 1.4.10
- Craft version: 3.5.17.1
- Multi-site: Yes
- Propagate nodes: Yes and No

**Comment by engram-design** [comment]
Fixed in [1.4.12](https://github.com/verbb/navigation/releases/tag/1.4.12)
