### ISSUE TITLE
Feed Me Support for Children

### ISSUE THREAD

**Issue by tekstrand** [verbb/navigation#243]
**What are you trying to do?**
Currently, creating node elements via FeedMe is only possible for level 0 nodes. This feature would add the ability to process children.

**What's your proposed solution?**
The two options I see are
#### Relate by reference
This requires the feed source to have relational data of some type. This could be a configurable field when creating the field. 
An example would be `Parent Field` = `Title` or `id` etc and then `relationData` = `parentTitle` or `parentId`

The data source may look like
```
[
  {
    id: 1,
    title: 'Item'
  },
  {
    id: 2,
    title: 'Item 2',
    parentId: 1
  }
]
```

#### Relate by structure
Ingestion of a more traditional JSON structure
```
[
  {
    id: 1,
    title: 'Item',
    children: [
        {
          id: 2,
          title: 'Item 2'
        }
    ]
  }
]
```

**Additional context**
N/A

**Comment by engram-design** [comment]
Yep, this might be tricky without some serious changes to Feed Me. It doesn't really support nested element imports very well (at all). As such, I think this might be much more of a Feed Me issue.

But my preference has always been the "Relate by structure" approach, as the "reference" can get a bit tricky. But I'm almost certain that Feed Me doesn't support these mechanisms.

**Comment by tekstrand** [comment]
That's possible. I know there is support today for parent/child relationships when importing categories, but I have not attempted this yet with other element types.

**Comment by engram-design** [comment]
Hmm, I'll have to have a look into it further then.

**Comment by engram-design** [comment]
Added for the next release. To get the fix early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.0-beta.4",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.0-beta.5](https://github.com/verbb/navigation/releases/tag/2.0.0-beta.5)
