### ISSUE TITLE
`nodeUri` contains absolute url in multilang setup

### ISSUE THREAD

**Issue by denisyilmaz** [verbb/navigation#244]
when querying the nodes via GraphQL in a language other then English the `nodeUri` contains the same absolute URL as in the field 

result for "en" (correct):
```json
{
  "title": "Example Page",
  "nodeUri": "subpage",
  "url": "http://example.test/en/subpage",
  "language": "en",
}
```

result for "de" (incorrect):
```json
{
  "title": "Example Page",
  "nodeUri": "http://example.test/de/subpage",
  "url": "http://example.test/de/subpage",
  "language": "de",
}
```

here is the query I'm using:

query:
```graphql
{
  nodes(navHandle: "main", site: "en", level: 1) {
    title
    nodeUri
    url
    language
  }
}
```

**Additional info**
- Plugin version: 1.4.13
- Craft version: 3.6.2
- Multi-site: Yes
- Propagate nodes: Yes

**Comment by engram-design** [comment]
Should be fixed for the next release. To get the fix early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-3 as 1.4.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.4.14](https://github.com/verbb/navigation/releases/tag/1.4.14)

**Comment by davidhellmann** [comment]
Run into this in craft4 today. Latest Version (craft / navigation)
Primary Site is fine. Just for the other sites I get this

![CleanShot 2022-09-24 at 12 10 51](https://user-images.githubusercontent.com/764292/192092424-da13769f-40d7-4b50-8a3d-8975db70aacc.png)

**Comment by engram-design** [comment]
I'm not seeing this, sorry. The `nodeUri` should never be the absolute URL.

What are you navigation settings (the propagation settings mainly).

What is your site's Base URL settings? `http://localhost:3000/fr/`?
