### ISSUE TITLE
Changes to source Elements are not reflected in Nodes

### ISSUE THREAD

**Issue by MattWilcox** [verbb/navigation#248]
Once a Navigation has been made, and its linking to various Entries etc, I would expect that changes to the Entry would be reflected in the Navigation node too. At the moment, if Entries get moved around in a Structure, or edited, you can end up with anchors output via Navigation without href values.

Can this be fixed? Unsure if this is a "feature" or "bug"

**Comment by engram-design** [comment]
Whenever a linked element (entry, category, etc) is modified, Navigation will update the Title of the node to reflect an updated on the element.

Not _quite_ sure what you mean about the entry being moved around in the structure, or if it's edited generally. The navigation node should be referencing that element still, and no matter where it sits in your section structure, it shouldn't have anything to do with how it sits in your navigation structure.

Can you give a specific, reproducible example of what you're seeing and I'll double check on my end?

**Comment by MattWilcox** [comment]
Have asked the dev who was having the issue to contribute to this thread when he's able... Cheers!

**Comment by engram-design** [comment]
Any further news on this one?

**Comment by MattWilcox** [comment]
No, I think we can close this. Unfortunately the dev who reported the issue hasn't added a comment... I'll nudge them and see if they have more info

**Comment by engram-design** [comment]
No problem we'll keep an eye on it!
