### ISSUE TITLE
Show Entries: All doesn't show newly-added Sections when deployed via Project Config

### ISSUE THREAD

**Issue by proimage** [verbb/navigation#249]
**Description**

EDIT: None of this was the issue - see next comment.

~~I have a typical site setup where I do local dev and deploy to a remote staging site (where project config changes are prohibited) via git & project config. I had a Navigation for the main menu that was set to Show Entries: true and the Entries multi-checkbox simply had "All" checked. I deployed that to the server and all was well.~~

~~Then I added a couple of new Sections locally, and deployed them to the new server. Locally, I can see those sections in Navigation (I can link a node to entries therein), but on the staging server, they aren't shown at all in Navigation.~~

~~I'm not sure if it's relevant, but this is a multi-site (2 sites) setup, as well.~~

**Steps to reproduce**
I can't guarantee this _will_ reproduce the issue.
1. Create a few Sections locally.
2. Create a Navigation, set to show "All" sections.
3. Deploy to another server where project config changes are prohibited via git & project config.
4. Add a couple of new Sections locally, with some entries.
5. Deploy to other server.
6. Check if other server's Navigation can select entries from those newly-added Sections.
~~
**Additional info**
- Plugin version: 1.4.13
- Craft version: Craft Pro 3.6.7
- Multi-site: Yes (2 sites)
- Propagate nodes: No

**Additional context**
Uh... I just woke up and it's cold here? :no_mouth:

**Comment by proimage** [comment]
Hmm, I think I found the problem. It's related to multi-site.

When viewing the node tree for a certain site (`/admin/navigation/navs/build/{id}/{siteId}`), editing a node and choosing to select an Entry to link to doesn't necessarily show you entries from the site whose node tree you were just viewing, but those of (apparently?) the default site.

I think that it would make a lot more sense if the initial entries shown were those of the site whose node tree you were just viewing. :-/

**Comment by engram-design** [comment]
Should be fixed in [1.4.14](https://github.com/verbb/navigation/releases/tag/1.4.14)

**Comment by proimage** [comment]
Wow, super-quick fix! Thank you!!
