### ISSUE TITLE
Children configuration

### ISSUE THREAD

**Issue by lucosius** [verbb/navigation#251]
Hey,

I'm pretty bad at programming and I need some help with this plugin. I use code from Documentation under "Custom rendering" section and everything is great but... I need more customization under children items since they don't use <li> elements as parent do. How can I do that?

In short words, I want to set entire styling for children and don't take it from parent.

**Comment by engram-design** [comment]
Refer to the [docs](https://verbb.io/craft-plugins/navigation/docs/template-guides/rendering-nodes#craft-navigation-nodes).

> If you'd rather not use the {% nav %} functionality, you can create your own recursive macro to loop through nodes.

You can't really control output using the `{% nav %}` tag, so you'll need to loop through items. You can either create nested loops, or a recursive macro. Personally, I would suggest you use nested loops until you're comfy with it working.

```
{% set nodes = craft.navigation.nodes()
    .handle('mainMenu')
    .level(1)
    .all() %}

<ul>
    {% for node in nodes %}
        <li>
            <a href="{{ node.url }}">{{ node.title }}</a>

            {% if node.hasDescendants %}
                <ul>
                    {% for subnode in node.children %}
                        <li>
                            <a href="{{ subnode.url }}">{{ subnode.title }}</a>

                            {% if subnode.hasDescendants %}
                                <ul>
                                    {% for subsubnode in subnode.children %}
                                        <a href="{{ subsubnode.url }}">{{ subsubnode.title }}</a>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endfor %}
</ul>
```

**Comment by lucosius** [comment]
Thank you! It's working for me
