### ISSUE TITLE
Switching from a entry type to a passive renders nav innaccessible in admin

### ISSUE THREAD

**Issue by jamie-l-robertson** [verbb/navigation#252]
Hi,

When switching a nav item from an entry type to a passive type, it causes the navigation to error and is no longer accessible. 

After investigation it looks like elementID's are being set when an entry but not removed when switched to passive which causes it, nullifying  the element id's on the db fixes the issue.

**Steps to reproduce**
1. Create a new navigation
2. Add an entry to the navigation and save
3. Change the entry to a passive type and save
4. Return to dashboard then click on Navigation > your nav name.

**Additional info**
- Plugin version: 1.4.14
- Craft version: 3.6.10
- Multi-site: Yes
- Propagate nodes: No

**Comment by engram-design** [comment]
Fixed in [1.4.15](https://github.com/verbb/navigation/releases/tag/1.4.15)
