### ISSUE TITLE
Queue: Argument 1 passed to craft\services\Elements::getElementById() must be of the type int, null given

### ISSUE THREAD

**Issue by ammannbe** [verbb/navigation#253]
**Description**

If there is a navigation node with the type "Entries", but no Entry is chosen, the queue manager fails on creating new sites.

**Steps to reproduce**

1. Create a new node with Type "Entries" but none selected
2. Create a new site in Settings > Sites > + New Site

**Additional info**
- Plugin version: 1.4.13
- Craft version: Craft Pro 3.6.6
- Multi-site: Yes
- Propagate nodes: Yes

**Additional context**

The mentioned node was created by a customer some time ago, so I am not 100% sure what exactly happened.
The error already appeared creating a new site, so it's more kind of a general error if you leave the entry empty.

**Comment by engram-design** [comment]
Fixed in [1.4.16](https://github.com/verbb/navigation/releases/tag/1.4.16)
