### ISSUE TITLE
editing siteType node and No node with the ID x error

### ISSUE THREAD

**Issue by vnali** [verbb/navigation#254]
editing siteType node throws a server error 'Class 'verbb\navigation\controllers\Exception' not found'. after fixing Exception class, error is 'No node with the ID x error'

**Steps to reproduce**
1.  the nav setting is set to no propagation but the nav is enabled for site1 and site2
2.  on site1, add a site type node but set target to site2 and save it
3. edit that node and save it without any change.
4. there is a server error -  Class 'verbb\navigation\controllers\Exception' not found-
5. if i add yii\base\Exception to NodeController, there is an error "No node with the ID x error" - passed siteIds on this request is site1 id and site2 id -

**Additional info**
Plugin version: 1.4.15
Craft version: Craft 3.6.10
Multi-site: Yes
Propagate nodes: No

**Comment by engram-design** [comment]
Fixed in [1.4.16](https://github.com/verbb/navigation/releases/tag/1.4.16)
