### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by havardlj** [verbb/navigation#256]
**Description**

I get a "Can't install plugin"-error when trying to install Navigation. I have found the following error in the logs:
`create table {{%navigation_nodes}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_navigation_nodes' already exists
The SQL being executed was: CREATE TABLE 'craft_navigation_nodes' (`
I have tried to manually remove this from the database, but I end up with the same problem. If I reset everything and try to install Navigation, the installation process in Craft doesn't run into any problems, but the plugin only gets added, and not installed. I got it working with a local version of the site with all of the same updates, but when I try to add it to the current database, it fails.

**Additional info**
- Plugin version: 1.4.15
- Craft version: 3.6.12
- Multi-site: Yes
- Propagate nodes: No

**Additional context**

**Comment by engram-design** [comment]
How are you installing this plugin, from composer or the plugin store?

The error points to you having installed Navigation at some point, not not uninstalling it - which removes all `navigation_*` tables. I would recommend removing all those database tables, and installing via whichever means you prefer. So long as those tables don't exist, there shouldn't be an issue installing the plugin.

**Comment by havardlj** [comment]
It seems like rebuilding the project.yaml-file did the trick
