### ISSUE TITLE
Slow navigation nodes edit page

### ISSUE THREAD

**Issue by jripmeester** [verbb/navigation#262]
**Description**
Our navigation implementation on admin site became really slow after the last update. The navigation edit page with all nodes on it takes about 6 seconds to load en has about 60 nodes on it. So it is kind of a big navigation but my gut feeling is that there's a N+1 issue somewhere. I hoped the latest 1.4.17 would fix this but unfortunatly it didn't.

**Steps to reproduce**
I think it's a specific issue with our data setup but we aren't doing anything custom. Please contact me and i'll share our DB with composer file with you to test this.

**Additional info**
- Plugin version: 1.4.17
- Craft version: 3.6.15
- Multi-site: Yes
- Propagate nodes: No

**Additional context**

**Comment by engram-design** [comment]
Out of interest, is this an issue on the 1.4.16 release? As in, was that the version you were on previously?

**Comment by jripmeester** [comment]
Yes, before the update to 1.4.17 the plugin was on 1.4.16 and was slow as well.

**Comment by engram-design** [comment]
Hmmm, if you're willing and able to send your database, composer files and project.yaml files to `web at verbb.io` I'll see if I can replicate it on my end. Almost all of my testing navigations perform pretty well.

**Comment by engram-design** [comment]
Looks like this was an issue with [Expanded Singles](https://github.com/verbb/expanded-singles) and isolated to the control panel.

See [Expanded Singles 1.1.4](https://github.com/verbb/expanded-singles/releases/tag/1.1.4) which should fix this performance issue.
