### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by frontedbe** [verbb/navigation#269]
**Description**

Getting the following error when saving a new navigation:
[screenshot](https://share.getcloudapp.com/4gun8Eo4)

**Steps to reproduce**
1. create new navigation
2. fill in 1 for max levels
3. propagate yes
4. save

**Additional info**
- Plugin version: 1.4.18
- Craft version: 3.6.17
- Multi-site: Yes
- Propagate nodes: Yes

**Additional context**

**Comment by engram-design** [comment]
Fixed in [1.4.19](https://github.com/verbb/navigation/releases/tag/1.4.19)
