### ISSUE TITLE
Multisite: Nodes are not bubbling to newly created site if navigation exists already

### ISSUE THREAD

**Issue by divyan** [verbb/navigation#27]
### Description
If you have a navigation and add a site afterwards, the nodes are not bubbling.
Quick fix is to save every node in the previous existing site where you created the navigation. Then the node bubbles through the new site.

### Steps to reproduce

1. Create a multisite and add a navigation
2. Then create a new site (now you have 2 or 3 sites)
3. Switch to the navigation, then you'll see the nodes created in the navigation don't exist in the new site.

**Comment by engram-design** [comment]
What was the reason this was closed for by the way?

**Comment by divyan** [comment]
I thought is was solved at the time I created the this ticket (node propagation fix etc.), but looking closer at it, I did my tests the wrong way (with a existing site instead of a new one), so I think it isn't solved yet. Sorry for the close, I'll reopen it.

**Comment by engram-design** [comment]
This should be fixed in [1.0.11](https://github.com/verbb/navigation/releases/tag/1.0.11).
