### ISSUE TITLE
Updating Navigation nodes trigger Gatsby incremental build, but doesn't actually update data upon completion

### ISSUE THREAD

**Issue by emson-digital** [verbb/navigation#270]
**Description**
We are utilizing Gatsby & Gatsby Cloud's incremental build functionality with [gatsby-source-craft](https://github.com/craftcms/gatsby-source-craft) & [Gatsby Helper](https://github.com/craftcms/gatsby-helper) plugin from P&T. For example, when an entry is updated and saved in Craft, Gatsby Cloud will "see" that change via webhook and rebuild only the updated content, greatly reducing build time from 3-5 minutes to 20-40 seconds.

When we make changes to our Navigation nodes and save, an incremental/webhook build is indeed triggered in Gatsby cloud as we expect, however the data itself remains unchanged after build is "completed" successfully. If we "Clear Cache and Manually Rebuild" then the node does pull in the newest data from Navigation as expected, but requires additional interaction from dev team by having to go into Gatsby to trigger this each time Navigation content is updated. Ideally, an update to Navigation content by site editors can be fully automated without the need for a manual rebuild.

**Steps to reproduce**
1. Make Navigation changes and save in a Gatsby connected installation which takes advantage of incremental builds.
2. Wait 20-40 seconds for Gatsby to complete incremental build.

**Additional info**
- Plugin version: 1.4.21
- Craft version: 3.7.16
- Multi-site: Yes (but only one site is active currently)
- Propagate nodes: No

**Additional context**
Navigation is the only plugin we've noticed this behavior, which is why it is suspected to be a possible issue with the plugin itself rather than a problem with Craft or Gatsby.

**Comment by engram-design** [comment]
I'm certainly not an expect when it comes to Gatsby, so I'll try and get in touch with @andris-sevcenko to see if there's anything incredibly obvious I'm missing in our integration with the Gatsby Helper plugin.

**Comment by andris-sevcenko** [comment]
Gatsby Helper plugin looks at element update time in the `elements` table. If, for some reason, the navigation nodes get updated, but that value does not, Gatsbyu Helper will not pick up those elements as "changed since such-and-such time".

**Comment by engram-design** [comment]
@andris-sevcenko Cheers! So yep, that's exactly what's happening, at least for my tests. 

I'm not sure @emson-digital if it's worth comparing on your end on the `dateUpdated` column for a `verbb\navigation\elements\Node` you can test making a change on to verify the date is changing?

Anything else I can do for debugging?

**Comment by emson-digital** [comment]
Nope all good! The issue is resolved :) Thank you!
