### ISSUE TITLE
Add support for limiting nodes per level.

### ISSUE THREAD

**Issue by bengreenbank** [verbb/navigation#276]
**What are you trying to do?**
Add a limit so that there can only be 10 top-level nodes (for example), but have no limit (or a different limit) on sub-items. Currently if I want to limit top level nav items but then add a child nav item, it tells me I've hit the limit.

**What's your proposed solution?**
New field on Settings panel for each nav menu which allows a limit per level of nav items. Maybe only add fields when a max level has been defined.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.9](https://github.com/verbb/navigation/releases/tag/2.0.9)
