### ISSUE TITLE
Odd behaviour when different nodes at different levels refer to the same Entry/URL

### ISSUE THREAD

**Issue by peteeveleigh** [verbb/navigation#278]
When outputting child nodes from a navigation that has the same node repeated in different places it seems that the first instance is "cached". This means subsequent uses of the node may not include its child nodes.

**Steps to reproduce**
Consider the following nav structure
```
About us
    Visit us
Visit Us
   Branch finder  
   Address
   Map
```

The following code can be used to get the child nodes from the current active node

```
	{% set activeNode = craft.navigation.getActiveNode({ handle: 'primaryNavigation', siteId : 1 }, true) %}

	{% set mosaicNav = craft.navigation.nodes()
        .descendantOf(activeNode)
		.descendantDist(1)
        .all() %} {# get children #}
 ```
 
 However, when on the top level Visit Us node, no child nodes are not available.
 
 If I move the Visit Us section ABOVE the About us section then the child nodes are available.
 
 ```
Visit Us
   Branch finder  
   Address
   Map
About us
   Visit us
```
 
 I appreciate this is probably something to do with URLs and perhaps not a "bug" as such, but it does seem like unexpected behaviour.

**Additional info**
- Plugin version: 1.4.24
- Craft version: 3.7.30.1
- Multi-site: Yes
- Propagate nodes:  No

99.9% sure this isn't a multi site issue. We have completely distinct navigations for each site. Nodes do not propagate between.

**Comment by engram-design** [comment]
So this behaviour is sort of expected, in that it'll find the _first_ active node that matches, not _all_ occurrences of the node that's active. Otherwise, `activeNode` would be an array of your 2 "Visit Us" nodes, which are two different things.

What would you expect to happen in this instance? Depending on what you're trying to achieve on your site, we might be able to do another approach?

**Comment by peteeveleigh** [comment]
I guess I can see the rationale there and perhaps it can be done a different way. 
I did try using `activeNode.children()` but that runs into the same problem in as much as `activeNode` is the instance of "Visit Us" that doesn't have the child nodes.

I can show you the precise use case but I don't want to post the link here so I'll ping you on Discord.

**Comment by engram-design** [comment]
Closing for now, but let me know if we need to continue hashing this one out.
