### ISSUE TITLE
yii\base\UnknownPropertyException

### ISSUE THREAD

**Issue by maxstrebel** [verbb/navigation#28]
### Description

Hi, sorry but I get an Error when I try to create a new Navigation. Clean Craft Install, fresh Navigation Install. I tried it in two different projects. Error as follows:

`yii\base\UnknownPropertyException: Setting unknown property: verbb\navigation\records\Nav::propagateNodes in /Users/max/Sites/project/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/max/Sites/project/vendor/yiisoft/yii2/db/BaseActiveRecord.php(322): yii\base\Component->__set('propagateNodes', '1')
#1 /Users/max/Sites/project/vendor/verbb/navigation/src/services/Navs.php(115): yii\db\BaseActiveRecord->__set('propagateNodes', '1')
#2 /Users/max/Sites/project/vendor/verbb/navigation/src/controllers/NavsController.php(98): verbb\navigation\services\Navs->saveNav(Object(verbb\navigation\models\Nav))
#3 [internal function]: verbb\navigation\controllers\NavsController->actionSaveNav()
#4 /Users/max/Sites/project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /Users/max/Sites/project/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /Users/max/Sites/project/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-nav', Array)
#7 /Users/max/Sites/project/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-nav', Array)
#8 /Users/max/Sites/project/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('navigation/navs...', Array)
#9 /Users/max/Sites/project/vendor/craftcms/cms/src/web/Application.php(538): craft\web\Application->runAction('navigation/navs...', Array)
#10 /Users/max/Sites/project/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#11 /Users/max/Sites/project/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /Users/max/Sites/project/web/index.php(21): yii\base\Application->run()
#13 {main}
Copy Stacktrace Search Stackoverflow Search Google Exception
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: verbb\navigation\records\Nav::propagateNodes`

### Steps to reproduce

1. Install Navigate on Craft 3.0.22 (or 3.0.21) through Plugin Store
2. Go to Navigation Tab
3. Create new Navigation (tried different options)

### Additional info

- Plugin version: 1.0.8
- Craft version: 3.0.22

**Comment by engram-design** [comment]
Can you try installing 1.0.9 (you might need to uninstall and reinstall)?

**Comment by maxstrebel** [comment]
Hi @engram-design, that solved it. I'm closing this. Thank you for the fast support.
