### ISSUE TITLE
Node is active when url is similar to the actual current node

### ISSUE THREAD

**Issue by mrwijsman** [verbb/navigation#284]
I have two entries with similar urls, when I visit URL 2 both of the nodes in the side navigation appear to be active. When you visit URL 1 this is not the case, also when I change the rvc to rvx in URL 2 the issue dissappears.

URL 1: https://optimix.beeldr.nl/over-optimix/rvc
URL 2: https://optimix.beeldr.nl/over-optimix/rvc-fondsen

PHP version	7.4.28
OS version	Linux 3.10.0-1160.11.1.el7.x86_64
Database driver & version	MySQL 5.5.5
Craft edition & version	Craft Pro 3.7.37
Yii version	2.0.45
Twig version	v2.14.11
Guzzle version	7.4.2

Plugin
Navigation	1.4.24

Modules
verbb-base	verbb\base\Base

**Comment by Antimated** [comment]
Having the same issue here. Any ETA on a fix yet? @engram-design

**Comment by engram-design** [comment]
Fixed in [1.4.27](https://github.com/verbb/navigation/releases/tag/1.4.27) and [2.0.3](https://github.com/verbb/navigation/releases/tag/2.0.3)
