### ISSUE TITLE
Install of Plugin Fails if the site had the plugin installed previously

### ISSUE THREAD

**Issue by JonGoldmanPlaybill** [verbb/navigation#285]
We did some testing with the Plugin early on and then deferred implementation until later.  This meant we installed and then uninstalled from the Craft CP.  On uninstall it failed to drop the tables `craft_navigation_nodes` & `craft_navigation_navs` from the database.  This had the effect of erroring on an attempt to reinstall the plugin from the CP as the Plugin fails to check if the tables exist before attempting the schema modify to add them.

**Steps to reproduce**
1. Install the plugin
2. Uninstall the plugin (from the Craft CP->Settings->Plugins
3. Attempt to reinstall the plugin (from the Craft CP->Settings->Plugins

**Additional info**
- Plugin version: 1.4.x
- Craft version: 3.7.x
- Multi-site: No

**Expected Behavior/Suggested Resolution**
Drop the tables on uninstall and have a check upon reinstall to see if the tables exist before attempting to create.

**Comment by engram-design** [comment]
Tables should be dropped [on uninstall](https://github.com/verbb/navigation/blob/craft-3/src/migrations/Install.php#L27-L33), and as for checking whether the tables already exist in plugins that's tricky. We could remove the tables for you, but then that's content that's being lost. We can't rely on existing tables being correct and up-to-date to use, as you've mentioned they could be quite old, so the only real option is to re-create them from scratch.

So the option will be likely to archive (rename) the existing tables and re-create them.

This is certainly one that's affected me, even on other plugins where uninstalls have gone wrong.

We're also following what Pixel & Tonic do with their other plugins, not checking for existing tables. But maybe that's just being overly optimistic! We'll either include this in our plugin or submit a PR to Craft itself so other plugins can make use of this for guarded behaviour.

**Comment by engram-design** [comment]
Added for the next release. To get the fix early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.0-beta.4",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.0-beta.5](https://github.com/verbb/navigation/releases/tag/2.0.0-beta.5)
