### ISSUE TITLE
Add `download` toggle for Asset nodes

### ISSUE THREAD

**Issue by acalvino4** [verbb/navigation#286]
**What are you trying to do?**

When configuring a node you can toggle "open in new window", which adds `target=_blank` to the link attributes.

I want to propose something similar for allowing assets links to be downloadable - a toggle which has the effect of adding the `download` attribute to the link attributes for that asset.

**Comment by engram-design** [comment]
Sure thing! At the moment you can add that attribute yourself, if that helps in the meantime. 

![image](https://user-images.githubusercontent.com/1221575/160218142-d99d93ea-1b58-4ccd-a07b-65fa90e20ecf.png)

**Comment by engram-design** [comment]
Just to keep things lean, I'm going to recommend people use the attributes to handle this. If you want to add this yourself, you can also add a custom field for a lightswitch, for you to add this for your users.
