### ISSUE TITLE
Twig Runtime Error – Key "activeClass" does not exist as the array is empty.

### ISSUE THREAD

**Issue by daltonrooney** [verbb/navigation#29]
If I use just the render tag with no arguments, I get the following error whenever I visit a page that's included in the navigation:

> Twig_Error_Runtime: Key "activeClass" does not exist as the array is empty. in /app/vendor/verbb/navigation/src/templates/_special/render.html:6
`<a href="{{ node.url }}" class="{% if node.active %}{{ options.activeClass ?: 'active' }}{% endif %}{% if options.aClass is defined %} {{ options.aClass }}{% endif %}"{% if node.newWindow %}`

If I add an activeClass value to the render tag, the page loads correctly. I tried uninstalling and re-installing the plugin with no luck.

### Additional info

- Plugin version: 1.09
- Craft version: 3.0.21

**Comment by juddlyon** [comment]
Same issue for me:
- Plugin version: 1.09
- Craft version: 3.0.22

**Comment by engram-design** [comment]
This is fixed in the [1.0.10](https://github.com/verbb/navigation/releases/tag/1.0.10) release.
