### ISSUE TITLE
GraphQL error when a category exists but GQL schema doesn't allow access to categories

### ISSUE THREAD

**Issue by tremby** [verbb/navigation#290]
**Description**

I came across an error while evaluating the plugin. It looks to me like there is a check missing.

**Steps to reproduce**
1. Add a navigation node which points to a category
2. In your GQL schema, disallow access to that category
3. Query the GQL endpoint for the nodes of this navigation menu

```
{
  "errors": [
    {
      "debugMessage": "Tried to load an unregistered type \"testCategory_Category\". This can indicate both a typo in the query or an issue with the schema used.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "trace": [
        {
          "file": "/srv/my-project/vendor/webonyx/graphql-php/src/Type/Schema.php",
          "line": 350,
          "call": "craft\\gql\\TypeLoader::loadType('testCategory_Category')"
        },
        {
          "file": "/srv/my-project/vendor/webonyx/graphql-php/src/Type/Schema.php",
          "line": 326,
          "call": "GraphQL\\Type\\Schema::loadType('testCategory_Category')"
        },
        {
          "file": "/srv/my-project/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1267,
          "call": "GraphQL\\Type\\Schema::getType('testCategory_Category')"
        },
...
```

I'm not sure what the correct behaviour should be, but there shouldn't be an error. Perhaps it's possible to get all the data needed for the link to the category, the error just needs to be sidestepped. Or perhaps nodes would be missing, or nulled out.

If I edit the schema to allow access to that category group, there is no longer an error.

**Additional info**
- Plugin version: dev-craft-4 at f8827cc
- Craft version: 4.0.x-dev at a59b90e
- Multi-site: Yes
- Propagate nodes: Yes or No whatever is default

**Additional context**
Headless mode

**Comment by engram-design** [comment]
Hmmm, that certainly raises an interesting point on the expected behaviour. I'm not sure how possible this is to skip over. I should note that for basic queries, this shouldn't be an issue:

```
{
    nodes (navHandle: "mainMenu", level: 1) {
        title
        url
    }
}
```

So long as you're not trying to access the linked element. But if you start requesting things about the linked element, that'll throw the error:

```
{
    nodes (navHandle: "mainMenu", level: 1) {
        element
            id
    }
}
```

So that would be expected behaviour in my mind. Just like if you tried to query that categories directly, with a schema that doesn't allow it:

```
{
  categories(group: "testCategories") {
    id
  }
}


{
  "errors": [
    {
      "message": "Cannot query field \"testCategories\" on type \"Query\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

**Comment by tremby** [comment]
Elsewhere in the GQL API, the fields you're not allowed access to because of restrictive settings for your token don't even appear in the schema. For example, if I remove the permission to read navigation nodes, `navigationNodes` doesn't even appear as an available field on the query schema.

If the field is generic, i.e. "element" might point to something you do or do not have access to, I think if there's no permission it'd make most sense to get a null if it's a non-list field, or for the entry to be absent if it's part of a list (i.e. the list may be empty, or contain all the allowed items but not the disallowed; no nulls).

**Comment by engram-design** [comment]
Added graceful error handling for the next release. To get this early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.9](https://github.com/verbb/navigation/releases/tag/2.0.9)
