### ISSUE TITLE
GraphQL "type" field returns null on custom/manual menu items

### ISSUE THREAD

**Issue by tremby** [verbb/navigation#291]
**Description**

The `type` field of each node gives a different string, except for "custom URL"/"manual" items, which give `null`.

**Steps to reproduce**
1. Make a navigation with nodes of various kinds including some "custom URL"
2. Query for the type of each node via GraphQL
3. See output. See `null` where I'd expect some string which indicates a custom URL.

```graphql
{
  nodes(navHandle: "mainNavigation") {
    type
  }
}
```

```json
{
  "data": {
    "nodes": [
      {
        "type": "craft\\elements\\Entry"
      },
      {
        "type": "craft\\elements\\Entry"
      },
      {
        "type": "craft\\elements\\Entry"
      },
      {
        "type": "craft\\elements\\Entry"
      },
      {
        "type": null
      },
      {
        "type": "verbb\\navigation\\nodetypes\\SiteType"
      },
      {
        "type": "verbb\\navigation\\nodetypes\\PassiveType"
      },
      {
        "type": "craft\\elements\\Asset"
      },
      {
        "type": null
      },
      {
        "type": "craft\\elements\\Entry"
      },
      {
        "type": "craft\\elements\\Entry"
      },
      {
        "type": "craft\\elements\\Category"
      }
    ]
  }
}
```

**Additional info**
- Plugin version: dev-craft-4 at f8827cc
- Craft version: 4.0.x-dev at a59b90e
- Multi-site: Yes
- Propagate nodes: Yes or No whatever is default

**Additional context**
Headless mode

**Comment by engram-design** [comment]
While this is _technically_ correct that manual nodes don't have a type (this was before we introduced the concept of node types), this will now return `custom` for manual nodes, inline with the `Node::getNodeType()` function.

**Comment by engram-design** [comment]
Fixed in the latest `craft-4` branch!

**Comment by tremby** [comment]
This is less confusing -- thanks!
