### ISSUE TITLE
GraphQL return null on url field for customURL nodes

### ISSUE THREAD

**Issue by aodihis** [verbb/navigation#294]
**Description**
When quering GraphQL for custom URL nodes always return null, even there already a value in the url.

**Steps to reproduce**
1. Crate a node with custom url type
2. Add the value for the url
3. Query through graphQL.

**Additional info**
- Plugin version: 2.0.0-beta.4
- Craft version: 4.0.0-rc2
- Multi-site: No
- Propagate nodes: No

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.5](https://github.com/verbb/navigation/releases/tag/2.0.0-beta.5)
