### ISSUE TITLE
Duplicate navigation

### ISSUE THREAD

**Issue by toddarmstrong** [verbb/navigation#295]
Is there anyway to easily duplicate a navigation?

I am wanting to duplicate one, change a couple of the nodes and then at some point switch the navigations in template.
Wanting to avoid having to recreate the whole navigation, or editing the nodes one-by-one while the navigation is live.

Thanks.

**Comment by engram-design** [comment]
Not at the moment, but great idea! I'll add it to our list to include

**Comment by toddarmstrong** [comment]
Ah yeah it didn't seem like there was this functionality based on looking through docs and exploring it.

Thanks for the reply, and looking forward to this feature in the future.

**Comment by engram-design** [comment]
Will keep this open for us to implement!

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [2.0.9](https://github.com/verbb/navigation/releases/tag/2.0.9)
