### ISSUE TITLE
Navigation instructions no longer show

### ISSUE THREAD

**Issue by danjrichardson** [verbb/navigation#297]
**Description**
Navigation instructions in Craft 4 version of Verbb Navigation, no longer show on the build page.
On Craft 3 version instructions were rendered on the page - https://github.com/verbb/navigation/blob/craft-3/src/templates/navs/_build.html#L230

**Steps to reproduce**
1. Create a new navigation 
2. Add instructions in the instructions field
3. Save navigation
4. Navigate to the navigation build mode.

**Additional info**
- Plugin version: 2.0
- Craft version: 4.0.2
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get the fix early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by danjrichardson** [comment]
Thanks @engram-design I can confirm that I'm now seeing the expected instructions on the build page with this update.
