### ISSUE TITLE
Using hasActiveChild always returns true

### ISSUE THREAD

**Issue by danjrichardson** [verbb/navigation#299]
**Description**
Using `hasActiveChild` on an item always returns true. This shouldn't really return true and is a deviation from the previous version for Craft 3.
https://github.com/verbb/navigation/blob/fb998c7553bf5dfe9fc5bdd3eaf422d21c840bda/src/elements/Node.php#L389

In code there is a provisional check if there are descendants, and if so they are checked for their active status.
If one is found true, then the node `getActive()` is called with it's returned value, immediately returned from the method.

However if there are no active descendants or not even any descendants, `true` is also returned.
Currently, this method doesn't really achieve anything other than trigger an `EVENT_NODE_ACTIVE` event if there is an active descendant.

As a workaround for now you can do this in a template which I believe is the correct intention of `hasActiveChild`:
```
{% set hasActiveChild = item.children|length and item.children|filter(subitem => subitem.active)|length %}
```

Unless I'm missing something major here?

**Steps to reproduce**
1. Add a menu, adding some items with and some without children
2. Output template on the page with a query to `hasActiveChild`

**Additional info**
- Plugin version: 2.0
- Craft version: 4.0.2
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get the fix early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by danjrichardson** [comment]
Thanks @engram-design that update has resolved my issue.
Calling `item.hasActiveChild` in the template now results in the expected behaviour.
