### ISSUE TITLE
Element nodes are saving URLs

### ISSUE THREAD

**Issue by billythekid** [verbb/navigation#3]
### Description

Firstly, thanks so much for this plugin. Every bit as good as the old AMNav one and nice work on giving them a credit.

The issue - When saving element nodes absolute URLs are being stored instead of NULL. This results in the URL output being an absolute/saved URL instead of getting the current element's URL. (Which can cause issues for example when moving between dev/staging on a shared DB) A cursory glance at the code it looks like if a node is an element that the url field should be NULL?

### Steps to reproduce

1. Select an entry as the navigation node and save
2. Check the output or database - the URL is saved - including the siteUrl part for whatever environment you are working in. 

### Additional info

Manually changing the element urls in the database table to NULL properly gives the element URL on the front end so output does seem to work properly, it's the saving part that appears to not work quite right.

- Plugin version: 1.0.0
- Craft version: 3.0.15

**Comment by engram-design** [comment]
Thanks! We've certainly loved A&M Nav up 'till now.

Well picked up, it looks like this was an issue when editing an existing element node, but was working as expected when adding it initially. This should be fixed in [1.0.1](https://github.com/verbb/navigation/releases/tag/1.0.1)
