### ISSUE TITLE
does not allow for an Emoji in a custom title

### ISSUE THREAD

**Issue by Joobs** [verbb/navigation#302]
**Description**
I have made a node that links to an entry. I want to customise the title (in the menu) by adding an emoji (💯). 
When I go to save I get an error of `[object Object]` at the top of the Craft control panel.
I can not save if there is an emoji in the title.

**Additional info**
- Plugin version: 1.4.26
- Craft version: 3.7.44

**Comment by engram-design** [comment]
I believe this is a [Craft limitation](https://github.com/craftcms/cms/issues/2513#issuecomment-369559835), more than anything else, as the Title for an element cannot contain an emoji.
