### ISSUE TITLE
Changing nav item type keeps old data

### ISSUE THREAD

**Issue by LinneaHarts** [verbb/navigation#305]
### Describe the bug

I have an issue where I change the navigation type from Entry to custom URL but the URL suffix remains, even if I delete it before making the change

### Steps to reproduce

1. Create an entry navigation node
2. Give it URL suffix
3. Save
4. Edit the navigation node and change it to a custom URL
5. Save
6. The custom url will have the URL suffix on it

This also does not work to fix it:
1. Create an entry navigation node
2. Give it URL suffix
3. Save
4. Remove the URL suffix
5. Edit the navigation node and change it to a custom URL
6. Save
7. The custom url will have the URL suffix on it

What does work is:
1. Create an entry navigation node
2. Give it URL suffix
3. Save
4. Remove the URL suffix
5. Save
6. Edit the navigation node and change it to a custom URL
7. Save
8. Now the custom URL will not have the old URL suffix

### Craft CMS version

3.7.44

### Plugin version

1.4.26

### Multi-site?

Yes, multilingual

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-3 as 1.4.29",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.4.30](https://github.com/verbb/navigation/releases/tag/1.4.30)
