### ISSUE TITLE
Is there a way to migrate the entire menu between environments(staging to production)?

### ISSUE THREAD

**Issue by mulraj208** [verbb/navigation#306]
### Question

Is there a way where we can configure the menu settings and add nodes to the same menu? (Basic database seeding)

If it's possible, Could you guide us?

**Comment by engram-design** [comment]
Not at the moment, sorry! That's because nodes are elements. We'll look at adding import/export functionality similar to [Formie](https://verbb.io/craft-plugins/formie/docs/feature-tour/import-export) which has a similar issue.

**Comment by engram-design** [comment]
Tracking in https://github.com/verbb/navigation/issues/280
