### ISSUE TITLE
new field is not showing on navigation node on staging.

### ISSUE THREAD

**Issue by NickLanger1990** [verbb/navigation#307]
### Describe the bug

new field is not showing on navigation node on staging.

### Steps to reproduce

1. create field and add it to navigation node on local. all works as expected.
2. push changes to staging.
3. new field is not added to navigation node.
4. only a project-config/rebuild and project-config/apply --force fixes the isse on the instance.
5. when pushing the changes to prod same behaviour.

### Craft CMS version

3.7.50

### Plugin version

1.4.28

### Multi-site?

Yes

### Additional context

Should work without force rebuild the project-config.

Normal project-config/apply should work.

**Comment by engram-design** [comment]
I'm not entirely sure this would be a Navigation plugin issue, but my testing shows I don't need to force the apply of project config for multiple environments. I wonder if doing the rebuild, then adding your field, then pushing to staging (and then just running non-forced apply) makes a difference?

Once you add the field locally, are there differences in your YAML files? I assume you're using Git, if you wouldn't mind sharing the diff to double check that all looks correct?
