### ISSUE TITLE
[C4][Multisite] 404 when going to a disabled navigation

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/navigation#308]
### Describe the bug

In Craft 4, the site you selected is now known through the whole control panel due to `?site=[siteHandle]`
When you go to a navigation which isn't available for that site, you get a 404 (which makes sense of course).

I believe we need the site selector on the overview page like entries, making visible only the navigations available for the selected site.

### Steps to reproduce

1. Have a multi site Craft 4 setup
2. Have a navigation which is enabled for site A but not for site B
3. Via entries, select site B (so the url will get `?site=site_b`
4. Try to open the navigation
5. Get a 404

### Craft CMS version

4.2.1.1

### Plugin version

2.0.3

### Multi-site?

Yes

**Comment by engram-design** [comment]
Added the site dropdown to the navigation index in [2.0.4](https://github.com/verbb/navigation/releases/tag/2.0.4)
