### ISSUE TITLE
Open in New Window

### ISSUE THREAD

**Issue by spAnser** [verbb/navigation#31]
### Description
Using `node.link` doesn't appear to add the `target="_blank"` when new window is checked on a node.

### Steps to reproduce

1. Create a node with new window checked
2. Output node using https://github.com/verbb/navigation#craftnavigationnodes

### Additional info

- Plugin version: 1.0.9
- Craft version: 3.0.23.1

**Comment by spAnser** [comment]
I imagine it has to do with this line not only outputting a link ignoring any possible classes or additional attributes. https://github.com/verbb/navigation/blob/e14a04cddf670871bc4d957e2ea02575ee71f343/src/elements/Node.php#L180
That line should probably have similar logic to https://github.com/verbb/navigation/blob/e14a04cddf670871bc4d957e2ea02575ee71f343/src/templates/_special/render.html#L6 yes?

**Comment by lazlo-bonin** [comment]
Having the same issue!

**Comment by engram-design** [comment]
This has been fixed and will be in the [1.0.10](https://github.com/verbb/navigation/releases/tag/1.0.10) release.
