### ISSUE TITLE
Conditional node fields based on link type

### ISSUE THREAD

**Issue by acalvino4** [verbb/navigation#310]
### What are you trying to do?

Craft 4 released conditional fields, but it seems that in Navigations node field configurator, they cannot be based on the type of field (passive, asset, entry, etc.)
![image](https://user-images.githubusercontent.com/43254861/186804737-800286df-156d-4d4a-ad19-ed8c9b4e7203.png)

### What's your proposed solution?

I'm not sure if this is a limitation on the craft side or what, nor do I know what the conditions for conditional fields are, so I'm not sure I have any thoughts on a solution.

**Comment by engram-design** [comment]
I'll also have to have a look at if this is possible, as I've yet to look into custom conditions.

**Comment by engram-design** [comment]
Added in [2.0.7](https://github.com/verbb/navigation/releases/tag/2.0.7)
