### ISSUE TITLE
Keep track of currently selected site from element index

### ISSUE THREAD

**Issue by Mosnar** [verbb/navigation#313]
### What are you trying to do?

Craft will keep track of your selected site in the element index by default; however, Navigation does not seem to take this into account. The UX would be more consistent for authors if Navigation followed that same behavior. For example, changing to Site B will ensure Site B is selected when changing between categories, entries, and globals.

### What's your proposed solution?

Pre-select current site

**Comment by engram-design** [comment]
What version are you on? This should’ve been addressed in https://github.com/verbb/navigation/issues/308 where we added support for the query string.

or maybe you’re referring to when you’re selecting an element for the node that it’s not using the current site?

**Comment by Mosnar** [comment]
You're right - I'm on the Craft 3 version, so I'm just behind!

**Comment by engram-design** [comment]
When I have a moment, I can backtrack this to Craft 3.
