### ISSUE TITLE
Open new window of Site type

### ISSUE THREAD

**Issue by aanimation** [verbb/navigation#317]
### Question

We found a something not expected but already solved by add new other for replacement,

at first time, we have add a menu item as Custom type and enabled Open New Window, then a few months later our client request to change the type into as site and not expected add Open New Window anymore, so ... as quick action we just change the type to Site and not found a checkbox to disable Open New Window anymore.
and after save, the item menu still have behaviour as open new window.

Another issue is changing Site type to Custom URL type not changing the interface of menu.

thanks

**Comment by engram-design** [comment]
You haven't specified what version of Craft or Navigation you're running.

In Craft 4 / Navigation 2 you can manage which of these extra settings are available on nodes. I can confirm that you can show the "New Window" setting with a Site node.

As for the lack of changing settings when changing type, something has changed on the Craft end about this, as it used to work, and it's related to the field layout form generation.
