### ISSUE TITLE
2.0.6 If breadcrumb node is an element it does NOT contain an element or elementType property.

### ISSUE THREAD

**Issue by Antimated** [verbb/navigation#321]
### Describe the bug

As per [the docs](https://verbb.io/craft-plugins/navigation/docs/template-guides/breadcrumbs#properties) there should be an `element` and an `elementType` property available. 

Logging a node of a breadcrumb query gives me the following available properties:

![Screenshot 2022-10-17 at 09 07 12](https://user-images.githubusercontent.com/2869409/196111130-a7f18c83-396b-471e-9921-3b47a3792bf2.png)

You can clearly see this **is** an element (by the `isElement` property) but still no element is being output. Meanwhile I fixed this by just fetching the correct page via the `elementId` but of course this issue should still be fixed.

### Steps to reproduce

Log out a node that is being output by a breadcrumb query

### Craft CMS version

4.2.7

### Plugin version

2.0.6

### Multi-site?

Yes

**Comment by engram-design** [comment]
This was only _just_ added to the `craft-4` branch. Now added in [2.0.7](https://github.com/verbb/navigation/releases/tag/2.0.7)
