### ISSUE TITLE
Unable to remove nodes

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/navigation#322]
### Describe the bug

Since the update to craft 4.3 the setting button to remove nodes isn't showing up anymore when selecting a node 
https://i.imgur.com/tGDQiDb.png
https://i.imgur.com/Xa9FQGz.png

### Steps to reproduce

1. update to craft 4.3

### Craft CMS version

4.3.0

### Plugin version

2.0.8

### Multi-site?

Yes

**Comment by robzor** [comment]
I also have this bug on the latest version.

**Comment by engram-design** [comment]
Fixed in [2.0.9](https://github.com/verbb/navigation/releases/tag/2.0.9)
