### ISSUE TITLE
When editing a field getting Exceeded maximum allowed nodes

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/navigation#327]
### Describe the bug

When editing a node (not adding one), I get an error saying `Exceeded maximum allowed nodes (3) for this nav.` while I'm just editing a node not adding one, so i'm not exceeding the limit, my guess it has something to do with the drafts?

### Steps to reproduce

1. Have a navigation with a node limit
2. Edit a node and try to save

### Craft CMS version

4.3.1

### Plugin version

2.0.10

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [2.0.11](https://github.com/verbb/navigation/releases/tag/2.0.11)
