### ISSUE TITLE
Make the entry select field in an 'add an entry' option required

### ISSUE THREAD

**Issue by JayBox325** [verbb/navigation#328]
### What are you trying to do?

When the client selects to add an entry, they shouldn't be able to save the item without selecting one.

To me, it's the sole aim of adding one of these items, so it should be required. I had it where a client added loads of nav items and the entries weren't selected, so the entire nav broke.

### What's your proposed solution?

Make the entry select field in the Entry nav item required.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.11",
  "...": "..."
}
```

**Comment by engram-design** [comment]
[2.0.12](https://github.com/verbb/navigation/releases/tag/2.0.12)
