### ISSUE TITLE
Disabling menu item for one site in a multisite

### ISSUE THREAD

**Issue by AndrewMac** [verbb/navigation#33]
This might not be a common kind of need, but I also think it might be :-)

I have a simple multiple language site where some entries in one of the languages need to be disabled in the menu, but still may be needed at a later time. This is also something that could come up quite often if people are using the option to propagate menu items across all sites and some pages are not yet live, or will not be needed in one site.

I realise that we could delete that navigation entry from the menu for one of the sites and add it in again when it needs to go live, but that just opens up more chances for human error, and we would also like the disabled state to be a visual reminder that we will eventually need to get that page enabled again in that language.

Do you think there might be any value in adding a setting to Navigation that replicates the default Craft enabled states? That is, a system-wide enabled option for the entry, with separate site-specific options as well. It would add a lot of value to the plugin and (to me, at least) make it work in a more intuitive way.

Anyway, thanks for listening ... 

### Steps to reproduce

1. Add the same entry to all languages in a multisite project
2. Disable the navigation item in one language
3. Check the other language, where the same entry will also be disabled

### Additional info

- Plugin version: 1.0.9
- Craft version: Craft Pro 3.0.24

**Comment by engram-design** [comment]
Thanks for the suggestion, this has been added in the [1.0.10](https://github.com/verbb/navigation/releases/tag/1.0.10) release.

**Comment by AndrewMac** [comment]
That’s great news. Thanks so much!
