### ISSUE TITLE
Error upgrading from Craft 3 + Navigation 1.4.31 directly to Craft 4 and Navigation 2.0.12

### ISSUE THREAD

**Issue by dustinwalker** [verbb/navigation#330]
### Describe the bug

We upgraded a Craft 3 site with 1.4.31 directly to Craft 4 and 2.0.12. In our case, that did not generate any rows in the navigation_navs_sites table. 

### Steps to reproduce

1. Upgrade to the latest Craft 3 and compatible Navigation plugin 
2. Run migrations 
3. Upgrade to the latest Craft 4 and Navigation 2.0.12
4. Run migrations
5. Jobs queue fails saving navigation with navigation not enabled for the site

### Craft CMS version

4.3.3

### Plugin version

2.0.12

### Multi-site?

No

### Additional context

I was able to fix this by reverting and locking the navigation plugin to 2.0.0 and running the migrations. No jobs errored out. There was a warning error visiting the plugin section in the admin, but I could go to and save the settings. That triggered saving a row to the navigation_navs_sites table. I could then upgrade to 2.0.12 and run the migrations without issue.

Happy to email you a database dump.

**Comment by engram-design** [comment]
Yeah, I've been trying to get to the bottom of this issue, but just can't seem to replicate it, as there's a migration there to handle creating those entries.

Any chance you could send your database from _before_ your Craft 4 upgrade? You can email to `web at verbb.io`

**Comment by dustinwalker** [comment]
@engram-design, you bet, should be in your inbox shortly.

**Comment by engram-design** [comment]
Okay, so that should be sorted in [2.0.13](https://github.com/verbb/navigation/releases/tag/2.0.13). What's strange though is that there's a [migration](https://github.com/verbb/navigation/blob/craft-4/src/migrations/m220902_000000_fix_empty_nav_sites.php) to handle this exact situation of no items in your `navigation_navs` database table, so not sure why that's not running and populating those rows...

**Comment by Diewy** [comment]
I'm running into the same issue, upgrading from `1.4.31` to `2.0.16` together with Craft 4 upgrade.

During the deployment the `php craft up` command is being runned, which includes all plugin's the migrations like `m220831_000000_fix_nav_sites` and `m221203_000000_fix_empty_nav_sites`.

When the project config is applied, I get the error:
```
error: The nav 'Footer' is not enabled for the site '1'
```

Any suggestions @engram-design ?

**Comment by engram-design** [comment]
@Diewy Would it be possible to get a copy of your database before the upgrade sent to `support@verbb.io`?

**Comment by Saboteur777** [comment]
@Diewy Follow these steps: https://github.com/verbb/navigation/issues/332#issuecomment-1411087544
