### ISSUE TITLE
Pass a navigation node from "passive" to "entries"

### ISSUE THREAD

**Issue by philippe-leeroy** [verbb/navigation#336]
### Describe the bug

When I try to pass a navigation node from "passive" to "entries" (or categories/assets etc.)

Craft CMS returns "Couldn't save draft". If I try to save anyway because I'm stubborn, it returns "Couldn't save node". 

And in the console, on the "network" tab preview, I have that :
```
{
    "elementId": [
        "Element ID is required."
    ],
    "linkedElementId": [
        "Linked Element ID is required."
    ]
}
```

So I checked in the database and apparently I have no elementId on my node in the navigation_nodes table.

![image](https://user-images.githubusercontent.com/114526245/207428883-9e71469c-46e0-4d84-a9e8-fac9d1933744.png)

### Steps to reproduce

1. Use a old navigation node that is set to "passive", click on the edit button
2. Try to switch it to "Entries"
3. Get a toast that says "Couldn't save draft"
4. Try to save anyway, another toast "Coudn't save node"

### Craft CMS version

4.3.5

### Plugin version

2.0.14

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [2.0.15](https://github.com/verbb/navigation/releases/tag/2.0.15)
