### ISSUE TITLE
Can't delete Navigation

### ISSUE THREAD

**Issue by daltonrooney** [verbb/navigation#339]
### Describe the bug

Trying to delete a Navigation, but I get the following error: 

[HTTP 404 – Not Found](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#404) – [yii\web\NotFoundHttpException](https://www.yiiframework.com/doc-2.0/yii-web-notfoundhttpexception.html)
Page not found.
↵
Caused by: Invalid Route – [yii\base\InvalidRouteException](https://www.yiiframework.com/doc-2.0/yii-base-invalidrouteexception.html)
Unable to resolve the request: navigation/navs/delete

`bypassProjectConfig` is set to false in my `navigation.php` config file.

I am able to manually edit the database to add a `dateDeleted` value for the Nav, which removes it from the CP.

### Steps to reproduce

1. Click "Edit Settings" next to Navigation
2. Click "Delete" buttun under "Save"

### Craft CMS version

4.3.6.1

### Plugin version

2.0.16

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get the fix early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.16",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
[2.0.17](https://github.com/verbb/navigation/releases/tag/2.0.17)
