### ISSUE TITLE
Set navigation to recently chosen site / locale

### ISSUE THREAD

**Issue by mdominguez** [verbb/navigation#34]
### Description
When you have been filling in a certain site/locale through through the Entries or Globals the most recent site / locale that you've edited gets loaded each time, but when you try to modify a navigation, the nav that gets loaded is for the first site (not the previously chosen one).

See this screencapture to make it more clear => [Link](https://cl.ly/23c58ef9b2df)

### Steps to reproduce

1. Create multiple sites (A, B)
2. Edit an entry for site B
3. Go to Navigation and edit one > Navigation for site A gets loaded while we we're previously editing entries for site B

### Additional info

- Plugin version: latest
- Craft version: latest

**Comment by engram-design** [comment]
Added in [1.0.11](https://github.com/verbb/navigation/releases/tag/1.0.11) (thanks to your PR).

**Comment by mdominguez** [comment]
Hey there! I've come across an error after updating to 1.0.11 and navigating to a navigation in the CP =>  [view screenshot](https://cl.ly/7de597b6fd24)

**Comment by engram-design** [comment]
Merged in [1.0.11](https://github.com/verbb/navigation/releases/tag/1.0.11).

**Comment by engram-design** [comment]
Thanks for the PR again, but going to make a few tweaks to this now, as I'm not a fan of the query string being appended everywhere, which causes issues such as this to occur.

**Comment by engram-design** [comment]
Fixed in [1.0.12](https://github.com/verbb/navigation/releases/tag/1.0.12).

**Comment by lemiwinkz** [comment]
> Thanks for the PR again, but going to make a few tweaks to this now, as I'm not a fan of the query string being appended everywhere, which causes issues such as this to occur.

Yup saw the mistake on the query string -__-. Using the handles is definitely a cleaner solution. Sorry about that! Strange this didn't show up in testing🤔
