### ISSUE TITLE
hasChildrenClass not adding class on render function

### ISSUE THREAD

**Issue by samroberts707** [verbb/navigation#340]
### Describe the bug

I'm using the `craft.navigation.render` function to load my nav. I've declared the `hasChildrenClass` as per the docs but the parent LI doesn't have the defined class.

Here is what my render function looks like: 

```
{{ craft.navigation.render('mainNav', {
     ulClass: 'nav-items',
     liClass: 'nav-item',
     aClass: 'nav-link',
     activeClass: 'nav-active',
     hasChildrenClass: 'nav-has-children',
}) }}
```

Here is a screenshot of what is rendered from browser inspection. (I've manually removed the HREF value)

![Screenshot 2023-01-17 at 13 28 53](https://user-images.githubusercontent.com/7763311/212911421-ae09cd34-8327-4c82-9003-21e9a79d3285.png)

### Steps to reproduce

1.  Create Navigation with Children
2. Render navigation in template using the .render function
3. 

### Craft CMS version

3.5.16

### Plugin version

1.4.21

### Multi-site?

No

**Comment by engram-design** [comment]
`hasChildrenClass` is only available in [Navigation 2](https://github.com/verbb/navigation/blob/craft-4/CHANGELOG.md#201---2022-05-18) for Craft 4.
