### ISSUE TITLE
On German installations after site switch accordions don't work

### ISSUE THREAD

**Issue by gglnx** [verbb/navigation#342]
### Describe the bug

After switching the site context, the accordions to add links to the navigation thrown an JavaScript exception:

<img width="435" alt="SCR-20230208-jk0" src="https://user-images.githubusercontent.com/23519/217538118-914344a6-9028-4204-9b41-677f8cda70c3.png">

Looks for me like an encoding issue because of German umlauts. After clean reload:

<img width="299" alt="SCR-20230208-jku" src="https://user-images.githubusercontent.com/23519/217538325-d0a1ae4e-53b8-48f2-99bd-741305d5bfac.png">

After AJAX site switch:

<img width="287" alt="SCR-20230208-jkz" src="https://user-images.githubusercontent.com/23519/217538388-000a5c42-cca5-4b6c-80c1-20ee97e113ef.png">

### Steps to reproduce

1. Switch to German for mighty Umlauts
2. Open navigation with at least two enabled sites
3. Edit navigation nodes
4. Switch site
5. Try to open an accordion with an Umlaut in the title

### Craft CMS version

4.3.6.1

### Plugin version

2.0.16

### Multi-site?

Yes

### Additional context

German as interface language selected

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.16",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
[2.0.17](https://github.com/verbb/navigation/releases/tag/2.0.17)
