### ISSUE TITLE
Upgrade to v2 issue (in Craft 4.x)

### ISSUE THREAD

**Issue by JonGoldmanPlaybill** [verbb/navigation#344]
### Describe the bug

If you do not update `node.hasChildren` to `node.hasDescendants` the former will be true if *any* node has children.  This is missing in the "upgrade caveats" docs, but also is now undocumented behavior.

### Steps to reproduce

1. 
2. 

### Craft CMS version

4.3.10

### Plugin version

2.0.16

### Multi-site?

No

**Comment by engram-design** [comment]
I don't believe `hasChildren` has ever been a property on a node - just wanted to confirm that? I did go back quite a way in both Craft and Navigation. `node.hasChildren` will throw an error on Craft 4.x.

**Comment by JonGoldmanPlaybill** [comment]
This was a miscommunication from one of my developers.  They thought they had copied the code we used in production for the update (the production code was `{% if node.children.count() %}`).   They typoed the update.

Just so you know `node.hasChildren` didn't toss an error, it evaluated to True.
