### ISSUE TITLE
Adding new items on long menus after scrolling shows an error notification

### ISSUE THREAD

**Issue by josdigital** [verbb/navigation#346]
### Describe the bug

On long menus that requires scrolling, after scrolling and adding a new item, the item is added but the interface doesn't get updated immediately and an error warning is shown.

After digging into the error I found that this is originated from [craft's BaseElementIndex.js updateElements method (line 1335)](https://github.com/craftcms/cms/blob/0c05ef5942de2db50c51b6a2e676f8137415bc36/src/web/assets/cp/src/js/BaseElementIndex.js#L1335) that is called from navigation.js with the addNodes method. 

The error is coming from `this.$main.offset().top` where `this.$main.offset()` is undefined.

### Steps to reproduce

1. Create a new menu
2. Add multiple items. The menu should be so long that scrolling the page is required to see the last item
3. Scroll down and check that the main craft header stay fixed
4. add a new item and save
5. a confirmation notification ("Node added.") alongside an error message ("A server error occurred.") will be displayed

![image](https://user-images.githubusercontent.com/128366984/226304331-5a219682-7fba-4a91-a572-a900b938f000.png)

Please check the issue on this gif:

![2023-03-20_10-28-56](https://user-images.githubusercontent.com/128366984/226300368-182a9d13-3734-4323-80e6-a96c6f69654c.gif)

### Craft CMS version

4.4.3

### Plugin version

2.0.16

### Multi-site?

No

### Additional context

Tested this error in a new fresh Craft 4 installation with only Navigation plugin installed.

**Comment by engram-design** [comment]
Thanks for the investigation, should be fixed in [2.0.17](https://github.com/verbb/navigation/releases/tag/2.0.17)
