### ISSUE TITLE
Query node type or typeLabel in Twig

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/navigation#347]
### What are you trying to do?

It seems this is possible according to the docs in GraphQL, but there's no node type query param for Twig.
I have created my own node and would like to fetch only these nodes so something like `craft.navigation.nodes().type("MyType").all()` or `typeLabel`.

### What's your proposed solution?

Add a `type` or `typeLabel` param.

**Comment by engram-design** [comment]
Looks like this is just missing from the docs. [Updated](https://verbb.io/craft-plugins/navigation/docs/getting-elements/node-queries#type)
