### ISSUE TITLE
Drag handles are not draggable

### ISSUE THREAD

**Issue by MattWilcox** [verbb/navigation#348]
### Describe the bug

The drag handles are not dragging.

https://youtu.be/xCjMv6G1T2Y to see what's happening.

### Steps to reproduce

Go into one of the Navigation menus and attempt to re-arrange any of the nodes.

### Craft CMS version

3.8.6

### Plugin version

1.4.31

### Multi-site?

Yes

### Additional context

"require": {
    "aelvan/imager": "^v2.4.0",
    "bertoost/craft-mailjet": "^1.2.3",
    "craftcms/cms": "^3.6.0",
    "craftcms/commerce": "^3.3.1",
    "craftcms/commerce-paypal-checkout": "^1.2.2.2",
    "craftcms/commerce-stripe": "^2.3.2.1",
    "craftcms/redactor": "^2.8.5",
    "nystudio107/craft-minify": "^1.2.10",
    "nystudio107/craft-retour": "^3.1.61",
    "nystudio107/craft-seomatic": "^3.3.28",
    "ostark/craft-async-queue": "^2.1.1",
    "putyourlightson/craft-sprig": "^1.2.0",
    "sebastianlenz/linkfield": "^1.0.25",
    "studioespresso/craft-dumper": "^2.0.0",
    "verbb/image-resizer": "^2.0.10",
    "verbb/navigation": "^1.4.10",
    "verbb/tablemaker": "^3.0",
    "vlucas/phpdotenv": "^3.4.0"
  },

**Comment by MattWilcox** [comment]
Just to add, I'm seeing this in Chrome and Firefox

**Comment by engram-design** [comment]
Any JS errors? Does this happen on a brand new navigation as well? Wondering if something related to the structure has been corrupted (creating a new navigation would create a new structure)

**Comment by MattWilcox** [comment]
No errors of any sort in Console, no. All of the network requests in the Network tab are 200 OK.

I've just created a new Navigation to test, and that breaks in the same way. I can't spot anything that's looking like a broken resource or broken bit of JS. I've checked that I'm not running uBlock or anything that might be interfering.

It's almost as though there's not any drag and drop JS loading / initialising.

<img width="1280" alt="Screenshot 2023-04-06 at 09 16 19" src="https://user-images.githubusercontent.com/814039/230316990-66e738ed-f735-413e-93db-3c40e59405e8.png">

**Comment by engram-design** [comment]
Ah, now I did just realise you were on Craft **3.8** and that indeed is the issue, and I can replicate that. Looks like something has changed between 3.7.x and 3.8.x. I can't find the source of the issue immediately, so it'll require some further digging.

For now, you can move elements by click-dragging on the node itself.

**Comment by marcusgaius** [comment]
@engram-design Hey, crawf, how's it going?
Just checking if there are some updates on this issue.
Thanks

**Comment by engram-design** [comment]
I've had to prioritise other tasks at the moment. Particularly as there's a workaround for this, and this is also for Craft 3 which is on its way out of priority support. I'll get to it!

**Comment by engram-design** [comment]
FYI, refer to my update on this https://github.com/craftcms/cms/issues/12896#issuecomment-1550675879 which was a fix for another issue apparently.

**Comment by engram-design** [comment]
Should be fixed in [Craft 3.8.12](https://github.com/craftcms/cms/releases/tag/3.8.12) (see https://github.com/craftcms/cms/pull/13234)
