### ISSUE TITLE
No "Advanced" settings when editing nodes.

### ISSUE THREAD

**Issue by beardedgingerdesigns** [verbb/navigation#351]
### Describe the bug

We upgraded from the craft 3 version to the craft 4 version. We are currently on 2.0.17. When we go to edit a node, whether new or existing, there are no advanced options that show up. The documentation references an "Advanced" tab but we are not seeing it.

![Screen Shot 2023-05-17 at 2 45 46 PM](https://github.com/verbb/navigation/assets/90393051/06dc48fb-3447-4e9d-adb0-be6300589a9a)

### Steps to reproduce

1. Upgrade plugin version from craft 3 to craft 4

### Craft CMS version

4.4.11

### Plugin version

2.0.17

### Multi-site?

No

**Comment by jaysunwalter123** [comment]
I'm having this same issue. There is now way to add attributes to each navigation node. How is it resolved?

**Comment by engram-design** [comment]
While Navigation should automatically create a new field layout going from Craft 3 to Craft 4, there's seemingly instances where this isn't happening. I haven't been able to hone in on what's causing this to reproduce the issue, but it can be solved by manually adding these fields and tabs to the field layout of a navigation.

![CleanShot 2024-08-21 at 09 38 31@2x](https://github.com/user-attachments/assets/9f410a8c-9444-4d92-ab2b-3dd9d92cae01)

Refer to the above screenshot for the Navigation settings and the field layout options available to you.
