### ISSUE TITLE
The default title for a site node is incorrect

### ISSUE THREAD

**Issue by MoritzLost** [verbb/navigation#358]
### Describe the bug

When creating a site node through the interface, the node always gets the title `Site` instead of the name of the selected site. This isn't very useful, since that title never really makes sense. A better default would be to use the site's name. Same as for entries, where the entry's `title` is used as the default node title.

See this video for demonstration:

https://github.com/verbb/navigation/assets/10146880/f8a55273-74cf-4b34-8a50-ac51801f7e3c

### Steps to reproduce

1. On a multisite, create a `Site` node in any navigation.

### Craft CMS version

4.4.15

### Plugin version

2.0.18

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/navigation:"dev-craft-4 as 2.0.18"`.

**Comment by MoritzLost** [comment]
@engram-design Thanks!

**Comment by engram-design** [comment]
Fixed in [2.0.19](https://github.com/verbb/navigation/releases/tag/2.0.19)
