### ISSUE TITLE
Add the attribute current to the node

### ISSUE THREAD

**Issue by Megafry** [verbb/navigation#361]
### What are you trying to do?

To Know if a node is the current one, I need to first make a query with help of `getActiveNode`.

```twig
{% set currentNodeId = craft.navigation.getActiveNode().id | default %}
...
class: [
  subNode.active ? 'is-active' : null,
  subNode.id == currentNodeId ? 'is-current' : null
]
```

### What's your proposed solution?

Add a new attribute `current` to all nodes identical to `active`.

### Additional context

Did I miss something in the documentation?

**Comment by engram-design** [comment]
Is there any reason why `node.active` is not suitable for your needs? I’m not sure what difference an active and current node is-
 - they should be the same?
 - 
 The active mode will be determined if the url you’re currently on matches the url of the node.

**Comment by Megafry** [comment]
Hi Josh
Thanks for your replay, the status `current` should indicate the page that the user is currently on.
Highlighting the current page differently is often necessary, especially with mega menus.
To set the right `aria-current` state would be greatly simplified. [aria-current - MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current)

For the following URL `page-a/page-a2` 
- *page A* `active` `aria-current="location"`
  - Page A1 
  - ***Page A2*** `active` `current` `aria-current="page"`
- page B

best regards

**Comment by engram-design** [comment]
Right, I suppose I see what you mean. In the case of a nested structure, we will mark parent nodes as active if a child is. Commonly for visual purposes to show an active state (your in Page A + Page A2). good call on `aria-current`, i actually wasn't aware of this.

You can use `node.getActive(false)` to not include children-active checks, which will effectively tell you if you're on that _current_ node.

I'll also add a `node.getCurrent()` which adds the `aria-current` attribute to the `render()` call.

To get this early, run `composer require verbb/navigation:"dev-craft-4 as 2.0.19"`.

**Comment by engram-design** [comment]
Added in [2.0.20](https://github.com/verbb/navigation/releases/tag/2.0.20)
