### ISSUE TITLE
Changes to asset fields aren't saved

### ISSUE THREAD

**Issue by d-karstens** [verbb/navigation#366]
### Describe the bug

Hi,

After updating to Craft 4.5 we've encountered an issue where changes to asset fields are not saved in a node - other fields seem to update normally

 I've recorded a short video demonstrating the issue on a fresh install with no other plugins

https://github.com/verbb/navigation/assets/21274925/4504e3b5-6dbf-404a-b029-5a718676f122

### Steps to reproduce

1. Add an asset field to a node
2. Upload an image to the field and save the node
3. Asset field changes are not saved

### Craft CMS version

4.5.0

### Plugin version

2.0.20

### Multi-site?

No

**Comment by engram-design** [comment]
Can't seem to replicate that on 4.4.x or 4.5.x at the moment. See the attached video. https://share.cleanshot.com/j0Tby398

Out of interest, can you inspect the network request to see if there's data for the asset field in the payload?

https://share.cleanshot.com/V7hHlXmq

**Comment by d-karstens** [comment]
I saw there were two network requests - the first with the data when the element is uploaded
`lfvndtwlgn[fields][test][]: 517`

![Screenshot 2023-08-25 at 1 55 45 pm](https://github.com/verbb/navigation/assets/21274925/5b2a3162-e1a4-4533-8b74-216824e1376b)

and the second when I save the node where the data is missing
![Screenshot 2023-08-25 at 1 55 53 pm](https://github.com/verbb/navigation/assets/21274925/fde7e075-7a69-4009-a35a-a4161645ec6b)

Not sure if that's the normal behavior though

**Comment by engram-design** [comment]
Alright, I can now replicate that. 

The second `save-draft` request is marked as cancelled. The first call will be as soon as the field is changed. That triggers the draft to be autosaved. The second is when you click the "Save" button, which is being marked as cancelled for me.

<img width="600" alt="image" src="https://github.com/verbb/navigation/assets/1221575/a47080e4-e848-49fa-8100-8ae660cf263d">

However, I see this exact behaviour in Craft 4.4.x, which is working, but not in Craft 4.5.x The payloads are identical. Looking into it.

**Comment by andrewhawkes** [comment]
Just ran into this myself, using plugin version `2.0.20` on Craft CMS `4.5.2`.
Note, that I'm not getting any console errors but I can see the xhr getting cancelled on the same action URL as above.

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/navigation:"dev-craft-4 as 2.0.20"`.

**Comment by engram-design** [comment]
Fixed in [2.0.21](https://github.com/verbb/navigation/releases/tag/2.0.21)
