### ISSUE TITLE
Multisite: only navigation from primary site shown

### ISSUE THREAD

**Issue by bartrylant** [verbb/navigation#37]
If you have multiple sites, and you have a user that can only edit one site (that is *not* the primary site), the navigation from the primary site is shown instead of the navigation from the site the user can edit.

So:
John can edit sitaA (primary) and siteB
John adds navigation for siteA and site B
Eric can only edit siteB
When Eric clicks on the navigation plugin, the navigation from siteA is shown

**Comment by engram-design** [comment]
Fixed in [1.0.12](https://github.com/verbb/navigation/releases/tag/1.0.12).
