### ISSUE TITLE
Support Markdown in navigation instructions

### ISSUE THREAD

**Issue by MoritzLost** [verbb/navigation#371]
### What are you trying to do?

This is a (hopefully) tiny feature request. We already have the `Instructions` field that allows us to add instructions for editors to the navigation screen. However, it lacks the ability to format text. This would be useful, as it would allow us, for example:

- Emphasize important instructions with **bold** or _italic_ text.
- Output a list of instructions as bullet points
- Add links to external resources

### What's your proposed solution?

Allowing Markdown content in the field and parsing the output as Markdown would enable basic formatting for the navigation instructions. It would also be backwards-compatible, since plain text still works as Markdown. Finally, it would bring the navigation instructions in line with the instructions field for built-in Craft fields, those already support Markdown.

**Comment by engram-design** [comment]
Short of adding an entire rich text editor field (which honestly adds probably too much overhead for just this setting), I think Markdown would be entirely appropriate.

Added for the next release. To get this early, run `composer require verbb/navigation:"dev-craft-4 as 2.0.21"`.

**Comment by MoritzLost** [comment]
@engram-design Just gave it a try, that's working great, thanks!

**Comment by engram-design** [comment]
Added in [2.0.22](https://github.com/verbb/navigation/releases/tag/2.0.22)
