### ISSUE TITLE
Error when editting a node

### ISSUE THREAD

**Issue by daafbleumink** [verbb/navigation#372]
### Describe the bug

I have an issue where, when I click "Edit" beside a note I get a blank slide-over and a message "A server error has occured". 
Now I've looked into the logs and found this error:

````
/Users/xx...')
#9 {main} {"memory":5385984,"exception":"[object] (TypeError(code: 0): craft\\web\\View::namespaceInputs(): Argument #1 ($html) must be of type callable|string, null given, called in /Users/xx/Herd/xx/vendor/craftcms/cms/src/web/View.php on line 1669 at /Users/xx/Herd/xx/vendor/craftcms/cms/src/web/View.php:1657)"
````

Could someone give me some pointers on how to solve this? I have no custom fields associated with the menu. This also happens when creating a brand new navigation.

### Steps to reproduce

I don't really have any steps for reproduction sadly. 

### Craft CMS version

Craft Solo 4.5.8

### Plugin version

2.0.21

### Multi-site?

No

**Comment by engram-design** [comment]
Looks like an issue in [Craft 4.5.8](https://github.com/craftcms/cms/issues/13867) and looks to be an issue upstream with them.

**Comment by daafbleumink** [comment]
> Looks like an issue in [Craft 4.5.8](https://github.com/craftcms/cms/issues/13867) and looks to be an issue upstream with them.

 @engram-design  Ah I see ... What would you suggest? Raise an issue in the Craft CMS repository?

**Comment by brandonkelly** [comment]
Craft 4.5.9 is out with a fix for this.
