### ISSUE TITLE
Changing country in multi site setup - select entry still links to content from previous site

### ISSUE THREAD

**Issue by jan-dh** [verbb/navigation#374]
### Describe the bug

When you change site in a multi-site setup, and press the "Add entry" button, the content you see is still from the previous site. 

### Steps to reproduce

1. Create multi-site setup
2. Link entries

### Craft CMS version

4.5.10

### Plugin version

2.0.22

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/navigation:"dev-craft-4 as 2.0.22"`.

**Comment by engram-design** [comment]
Fixed in [2.0.23](https://github.com/verbb/navigation/releases/tag/2.0.23)
