### ISSUE TITLE
Ability to edit "Open in new window" property for already created nodes

### ISSUE THREAD

**Issue by robinbisping** [verbb/navigation#375]
### What are you trying to do?

I would like to be able to change whether navigation links are opened in a new window for already created nodes.

### What's your proposed solution?

Add such an option to the slideout/sidebar of a navigation node.

**Comment by engram-design** [comment]
That's possible now. Just ensure that you add "New Window" to the Node Fields for the nav.

<img width="651" alt="Screenshot 2023-11-25 at 11 25 48 pm" src="https://github.com/verbb/navigation/assets/1221575/d5e04a15-60e3-4c10-9d43-c418c5b4ec77">

**Comment by robinbisping** [comment]
Alright, thanks!
