### ISSUE TITLE
Nodes become uneditable after saving

### ISSUE THREAD

**Issue by MoritzLost** [verbb/navigation#377]
### Describe the bug

I'm seeing an issue on multiple sites where you can only edit a node once. After saving the node once, the edit link doesn't appear again until you reload the page. See the following screen recording:

https://github.com/verbb/navigation/assets/10146880/b56553bf-b560-4141-85e2-58c6d8bbea0b

Not sure how long this has been the case, but I'm seeing the same behaviour in multiple sites using the latest plugin version.

### Steps to reproduce

1. Go to any navigation.
2. Edit and save any node.
3. Hover over the node again in the tree view.

### Craft CMS version

4.5.11.1

### Plugin version

2.0.22

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [2.0.23](https://github.com/verbb/navigation/releases/tag/2.0.23)
