### ISSUE TITLE
Craft 5 tests - verbb/base requires wrong version

### ISSUE THREAD

**Issue by davidwebca** [verbb/navigation#378]
### Describe the bug

Hi! I'm preparing to test upgrading a site for Craft 5 and I've been unable to install navigation because it requires verbb/base ^3.0.0-beta.1 instead ovfverbb/base dev-craft-5.

### Steps to reproduce

1. Spin a new Craft 5 project
2. run ```composer require verbb/navigation:dev-craft-5```
3. Notice the unsatisfiable constraint error

### Craft CMS version

5.0.0-alpha

### Plugin version

dev-craft-5

### Multi-site?

No

**Comment by engram-design** [comment]
Yep, our Craft 5 work is still very much a work in progress, with nothing tagged on purpose. We're waiting for Craft 5 to reach beta status (it's currently just a dev preview - not even an alpha). Likewise, they haven't even tagged a version for Craft 5 yet, so things are very much in flux still.

We'll get some beta versions tagged before the end of the year.

**Comment by engram-design** [comment]
Of course, no sooner I'd typed that the [Craft 5.0.0-alpha.1](https://github.com/craftcms/cms/releases/tag/5.0.0-alpha.1) was released! 😂

**Comment by davidwebca** [comment]
😂  Good gosh. I was working on updating an old project to 4 and also preparing a new project that will go live after Craft 5 releases so we decided to bite the bullet and start the project upfront with it. Good timing!

**Comment by samuelbirch** [comment]
Hey @engram-design, have you got any recommended way of installing your craft 5 compatible versions? - Would love to start testing things out.

**Comment by engram-design** [comment]
It's still a bit unstable (there's still plenty of changes going on in the alpha), but you can do:

```
composer require verbb/base:"dev-craft-5 as 3.0.0-beta.1"
composer require verbb/navigation:"dev-craft-5 as 3.0.0-beta.1"
```

**Comment by engram-design** [comment]
Updated in [3.0.0-beta.1](https://github.com/verbb/navigation/releases/tag/3.0.0-beta.1)
