### ISSUE TITLE
Option: UL attributes

### ISSUE THREAD

**Issue by sjelfull** [verbb/navigation#38]
### Description

Add config option for adding extra attributes on the main ul tag.

Context: I'm working on a site with a JS library that does something to the menu based on the `data-` attributes on it.

I realise `craft.navigation.nodes()` can help with this, but on the other hand, you then have to set the other attributes (new window, active class etc.) manually.

**Comment by engram-design** [comment]
Added in [1.0.11](https://github.com/verbb/navigation/releases/tag/1.0.11)!
