### ISSUE TITLE
Installed or No?

### ISSUE THREAD

**Issue by smockensturm** [verbb/navigation#380]
### Question

Database shows the tables. Composer shows the plugin is installed (2.0.24) All systems point to a successful installation.

But where is the plugin? The control panel system report has no mention of Navigation plugin. The list of plugins from settings does not show this plugin. I've run composer again and again. Thrown out the vendor folder (it's in there). Rebuilt the project config. What am I doing wrong?

I've got your base installed, your button box and super table.

Craft is 4.6.1 Everything is latest and greatest. PHP 8.2

**Comment by engram-design** [comment]
Strange. What does `php craft plugin/install navigation` produce?

**Comment by smockensturm** [comment]
I know.

`There aren’t any uninstalled plugins present.`

**Comment by smockensturm** [comment]
I got it. Composer platform. Sorry.
