### ISSUE TITLE
craft.navigation.render() doesn't use custom title

### ISSUE THREAD

**Issue by cmalven** [verbb/navigation#381]
### Describe the bug

I am using Navigation to link to our homepage multiple times, with each using `URL Suffix` to link to a unique #anchor. I've given each of these links a unique `Title`, but when I output them using `{{ craft.navigation.render('navPrimary', {}) }}` every link outputs with the title `Homepage`.

Is this the intended behavior?

<img width="903" alt="Screenshot 2024-01-19 at 14 30 47@2x" src="https://github.com/verbb/navigation/assets/610118/84621e48-3796-4a56-bf56-dca382c0ce11">

<img width="116" alt="Screenshot 2024-01-19 at 14 32 24@2x" src="https://github.com/verbb/navigation/assets/610118/2437330c-358c-409f-8421-b5930018640c">

### Steps to reproduce

1. Create a navigation with links to Entries
2. Give each of these entries a unique `Title`
3. Render the navigation using `craft.navigation.render()`

### Craft CMS version

4.5.10

### Plugin version

2.0.22

### Multi-site?

No

**Comment by engram-design** [comment]
That's odd, certainly not seeing that on my end 
<img width="937" alt="image" src="https://github.com/verbb/navigation/assets/1221575/5252000e-c6bd-43b1-a051-e653ad338352">

Does the same thing happen when manually rendering nodes?

```twig
{% set nodes = craft.navigation.nodes('navPrimary').all() %}

<ul>
    {% nav node in nodes %}
        <li>
            Title: {{ node.title }}<br>
        </li>
    {% endnav %}
</ul>
```

**Comment by cmalven** [comment]
@engram-design I get the same result using your code to loop through each node.

<img width="802" alt="Screenshot 2024-01-23 at 17 56 03@2x" src="https://github.com/verbb/navigation/assets/610118/2a21b171-f9fb-4818-ba6a-205fa57435dd">

**Comment by engram-design** [comment]
That's quite odd. I don't suppose you'd be able to share your database? Completely understand if you're not able to, but if you are, send it to `support@verbb.io` and hopefully I can reproduce that.

**Comment by cmalven** [comment]
Thanks @engram-design I've reached out to you at that email address.

**Comment by engram-design** [comment]
Thanks for sending that through! I can see the issue, in that you've only renamed the nodes for siteId 1 and not siteId 2, which is the primary site.

This is a screenshot of your primary site's navigation nodes

<img width="490" alt="image" src="https://github.com/verbb/navigation/assets/1221575/fe4a863b-68ae-4853-8382-0b6f01753e0d">

And in the content table it's more clearer:

<img width="715" alt="image" src="https://github.com/verbb/navigation/assets/1221575/7d302461-0300-4dc0-b9ca-c490e821bf7e">

I'm not actually sure if it's a bug that you have two identical sites, so maybe that's more the issue?

**Comment by cmalven** [comment]
@engram-design Yep that's definitely it! Thanks, I should've noticed that it was showing the site selection dropdown, but I have no idea how an additional site was created. Definitely wasn't intentional. Appreciate you taking a look.
