### ISSUE TITLE
Site / language switcher is broken in Navigation's breadcrumb [3.0] [Craft 5]

### ISSUE THREAD

**Issue by davidwebca** [verbb/navigation#388]
### Describe the bug

The multisite language switcher in the breadcrumbs is broken, only in Navigation's page so it seems like a Navigation bug.

### Steps to reproduce

1. Install the plugin and create a new navigation
2. Add a new site / language to Craft
3. Go to Navigation and notice the last element of the breadcrumb is broken 

It's not only visually broken, but the dropdown doesn't activate the language switching.

![screen1](https://github.com/verbb/navigation/assets/412352/58138f4b-ffcd-4077-a1f1-2bbfa934f4de)
![screen2](https://github.com/verbb/navigation/assets/412352/b8e35265-7117-415b-89be-c492340b9c72)

### Craft CMS version

5.0.0-beta.5

### Plugin version

3.0.0-beta.1

### Multi-site?

Yes

### Additional context

Here's the list of plugins I have in the same project right now.

    Name                   Handle                 Package Name                    Version                 Installed  Enabled
    ---------------------  ---------------------  ------------------------------  ----------------------  ---------  -------
    CKEditor               ckeditor               craftcms/ckeditor               4.0.0-beta.7            Yes        Yes
    Colorit                colorit                presseddigital/colorit          dev-master              Yes        Yes
    Entry GPS Coordinates  entry-gps-coordinates  nthmedia/entry-gps-coordinates  dev-master              Yes        Yes
    Field Manager          field-manager          verbb/field-manager             4.0.0-beta.1            Yes        Yes
    Formie                 formie                 verbb/formie                    3.0.0-beta.2            Yes        Yes
    Hyper                  hyper                  verbb/hyper                     2.0.0-beta.2            Yes        Yes
    Icon Picker            icon-picker            verbb/icon-picker               3.0.0-beta.2            Yes        Yes
    Navigation             navigation             verbb/navigation                3.0.0-beta.1            Yes        Yes
    oEmbed                 oembed                 wrav/oembed                     dev-feature/gql-params  Yes        Yes
    Route Map              route-map              nystudio107/craft-routemap      dev-craft-5             Yes        Yes
    SEOmatic               seomatic               nystudio107/craft-seomatic      dev-develop-v5          Yes        No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/navigation:"dev-craft-5 as 3.0.0-beta.1"`.

**Comment by davidwebca** [comment]
Great thanks! But I can see it's fixed in the navigation editing view, but not in the navigations listing view. 

Edit: I don't know if it's related, but the Cog toggle doesn't appear when selecting elements so it's impossible to delete anything at the moment.

**Comment by engram-design** [comment]
Missed that one, updated. Also put it in the breadcrumbs like other areas of the CP. Also fixed the action buttons not appearing. To get this early, run `composer require verbb/navigation:"dev-craft-5 as 3.0.0-beta.1"`.

**Comment by davidwebca** [comment]
You're amazing, thanks a lot!

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.2](https://github.com/verbb/navigation/releases/tag/3.0.0-beta.2)
