### ISSUE TITLE
Active item matching is case sensitive

### ISSUE THREAD

**Issue by svondervoort** [verbb/navigation#395]
### Describe the bug

It looks like the plugin determines the active item matching the items URL with the current page URL.
It also looks like it is case sensitive, because when I (accidentally) change the `PRIMARY_SITE_URL` to something with atleast one capitalised character there is not active match.

### Steps to reproduce

1. Create a Craft project with at least a homepage and another (single) entry
2. Add the homepage and entry to the navigation
3. Visit the entry in the frontend and check if the menu item is active
4. Change one character in the `PRIMARY_SITE_URL` to the same capital character
5. Reload the entry frontend page and now the item is not active anymore since it doesn't match.

### Craft CMS version

4.9.6

### Plugin version

2.0.27

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [2.0.28](https://github.com/verbb/navigation/releases/tag/2.0.28)
