### ISSUE TITLE
Add a condition rule for hierarchy levels

### ISSUE THREAD

**Issue by MoritzLost** [verbb/navigation#396]
### What are you trying to do?

I have some fields that I only want to display for root nodes (hierarchy level 1). In this case, the first level nodes are passives that each contain a mega menu structure. The mega menu includes some additional content (e.g. a headline, an image) that should be editable for the root nodes. However, all other hierarchy level should not show these fields, because they don't use them.

Nodes already support element condition rules, but there is no condition rule for the `level` property:

![All available options for element condition rules for nodes](https://github.com/verbb/navigation/assets/10146880/beba9e2c-7ec5-408e-b148-d7cf0f4581b6)

### What's your proposed solution?

Add a condition rule for the `level` where the field can be limited to only be visible for nodes at one or more specific levels. This would also address other use-cases. For example, in some situations it would be useful to only show a field for the second hierarchy level, or every level _but_ the first one, etc.

### Additional context

Quick mockup (wording could be better):

![Screenshot 2024-07-02 at 16 49 09](https://github.com/verbb/navigation/assets/10146880/e28b9744-bdcf-47fe-92f9-599e3e2f22d1)

![Screenshot 2024-07-02 at 16 49 26](https://github.com/verbb/navigation/assets/10146880/48ec95d3-7b19-48d0-994b-05db0f3736f6)

**Comment by engram-design** [comment]
What version of Navigation are you on? The `level` attribute is certainly available for me 
<img width="625" alt="image" src="https://github.com/verbb/navigation/assets/1221575/a5406971-5c60-4910-93ed-860a391a52a7">

**Comment by MoritzLost** [comment]
@engram-design Very curious 🤔
We're on the latest release 3.0.1, and Craft 5.2.1.

I've checked the source code, I can see the `NodeCondition` class that's registering `LevelConditionRule` and `TypeConditionRule`, but neither of those are showing up in the interface. Any ideas?

**Comment by engram-design** [comment]
Ah, I see there's an issue with it for Craft 5. Fixed for the next release. To get this early, run `composer require verbb/navigation:"dev-craft-5 as 3.0.1"`.

**Comment by MoritzLost** [comment]
@engram-design Works perfectly, thanks!

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/navigation/releases/tag/3.0.2)
