### ISSUE TITLE
Non-admin users can't see navigations

### ISSUE THREAD

**Issue by jorenvanhee** [verbb/navigation#397]
### Describe the bug

I created a user and gave it permissions to "Access Navigation". That user does see "Navigation" in the Craft CMS sidebar but non of the navigations are visible. Only the message "No navigations exist yet." appears.

<img width="618" alt="Screenshot 2024-07-02 at 22 28 16" src="https://github.com/verbb/navigation/assets/231202/1a8e1ce6-c48a-458e-914b-0386079ff212">

### Steps to reproduce

1. Check "Access Navigation" under "User Permissions"
2. Create a new user
3. Make sure you added a new navigation as well
4. Log in with that user and try to access "Navigation" from the sidebar

<img width="734" alt="Screenshot 2024-07-02 at 22 30 19" src="https://github.com/verbb/navigation/assets/231202/c058f92f-6a4f-40bc-9948-cb9804a4e780">

### Craft CMS version

5.2.0 (Team Edition)

### Plugin version

3.0.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
Under the Navigation heading, do you have any of the navigations set to "Manage"?

<img width="234" alt="image" src="https://github.com/verbb/navigation/assets/1221575/c6a07b51-6be0-4a05-ab32-32294127efe9">

**Comment by jorenvanhee** [comment]
I don't have the Navigation heading on the "User permissions" page.

**Comment by jorenvanhee** [comment]
I was able to narrow down the issue. After upgrading from Craft TEAM to Craft PRO, the Navigation section on the user permissions page appeared.

**Comment by engram-design** [comment]
Hmm, even for the Craft Team version those permissions seem to appear for me.

**Comment by jorenvanhee** [comment]
This was probably [fixed](https://github.com/verbb/navigation/commit/5e2211b7f2368b21a5437fee36f793debfc61c3a) then in 3.0.1, I was using 3.0.0. I think this ticket can be closed then :)
