### ISSUE TITLE
Drag and drop not respecting Max nodes per Level setting

### ISSUE THREAD

**Issue by EKBenI** [verbb/navigation#398]
### Describe the bug

Navigation: 2.0.28
Craft CMS: 4.10.5

Max nodes per level is set to 2 in the Navigation's settings:
![image](https://github.com/user-attachments/assets/5010f3f2-b968-42b6-8bbc-cab3cc7cef8e)

Nodes can still be dragged/dropped into the parent node more than the allowed limit:
![image](https://github.com/user-attachments/assets/52a787e1-f4f6-4e61-aae8-43a81b182799)

Attempting to drag the node back to the top level (or below another parent node) results in a server error message:
![image](https://github.com/user-attachments/assets/11d0fa9f-2006-4aa4-ad8e-e00589dc18cd)

The node then has to be deleted and recreated to be placed in the desired level/order.

Adding nodes using the dropdown menu respects the rules set in the settings - the issue is encountered with the drag/drop functionality. 

Please see: https://www.loom.com/share/32e4cc3703334f928290d3175193e024

### Steps to reproduce

1. Set a limit on the Max nodes per level setting in the Navigation's settings. 
2. Drag/drop node below a parent node that already has the maximum number of nodes.
3. Drag/drop the node to another location/level.

### Craft CMS version

4.10.5

### Plugin version

2.0.28

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/navigation:"dev-craft-4 as 2.0.28"`.

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/navigation/releases/tag/2.1.0)

**Comment by nicgoodman-em** [comment]
Wanted to reup this, this bug seems to be back in the latest version with the latest version of Craft 5.

**Comment by engram-design** [comment]
Seems to be respected for me with this error 
<img width="350" alt="image" src="https://github.com/user-attachments/assets/8233bf9c-906b-46e4-81b0-3947c1c1c1c5">

**Comment by nicgoodman-em** [comment]
> Seems to be respected for me with this error <img alt="image" width="350" src="https://private-user-images.githubusercontent.com/1221575/367464538-8233bf9c-906b-46e4-81b0-3947c1c1c1c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTk1NDMsIm5iZiI6MTcyNjQ5OTI0MywicGF0aCI6Ii8xMjIxNTc1LzM2NzQ2NDUzOC04MjMzYmY5Yy05MDZiLTQ2ZTQtODFiMC0zOTQ3YzFjMWMxYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTUwNzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NjZmVjMmJmNWE2Mzc2OTNiMjRkYjlmNzliMmFjOGZhMWYxNGQyZDRlZjZjZGRjZWQ5YjYzODY4NzBjMGMxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.43JKtYPBfsc_UoPceBHOr5pSSHsiVUaeel5xI0OdZtg">

Hmm, on my instance if I have level 1 set to only 1 node allowed, it will respect it when I try and add a node without a parent, but if I do select a parent, it will let me drag it back to level 1 but then will not let me drag it back to level 2.
