### ISSUE TITLE
CP - Edit node type

### ISSUE THREAD

**Issue by AlexShearcroft** [verbb/navigation#402]
### Describe the bug

Within the slideout when editing a node via the CP, changing the node type does not update the fields dynamically based on the chosen type. To display them you need to close the slide out and double-click the node to edit, this will then update and show the required fields allowing you to update and save.

### Steps to reproduce

1. Access your navigation via the CP
2. Create a node and for example set type as Custom URL
3. Edit the node and change type from Custom URL to Entries
4. Save - shows errors
5. Close
6. Edit node again and the type has updated to the one selected

### Craft CMS version

Craft Pro 5.2.10

### Plugin version

3.0.3

### Multi-site?

No

**Comment by engram-design** [comment]
Duplicate of https://github.com/verbb/navigation/issues/326
