### ISSUE TITLE
Site picker and status list shows sites that the navigation is not enabled for

### ISSUE THREAD

**Issue by MoritzLost** [verbb/navigation#407]
### Describe the bug

We have a navigation that is only enabled for some sites, but disabled for others:

![site-settings](https://github.com/user-attachments/assets/0a2f8fc8-452c-4883-8f80-951e9ded083e)

But in the author UI for that navigation, the sites dropdown shows _all_ sites, even the sites that the navigation is not enabled for:

![site-dropdown](https://github.com/user-attachments/assets/780d8985-38ca-442c-97d0-19a79b1c4d8b)

But switching to a site that the navigation is disabled for results in a 404 error:

> HTTP 404 – Not Found – yii\web\NotFoundHttpException
> Navigation not enabled for site: site_a

It would be better to only show sites that the navigation is enabled for in the dropdown, similar to entry form pages.

When editing a single node, the status in the sidebar also shows all sites:

![Screenshot 2024-10-10 at 14 57 54](https://github.com/user-attachments/assets/8123e9c8-6f3b-41d0-afb8-9a7b5dbef6be)

But the element isn't even propaged to `Site A` in this case, so this again should only show `Site B` and `Site C`.

### Steps to reproduce

1. Create multiple sites
2. Create a navigation that's only enabled for some sites
3. Go to the navigation edit page and check the dropdown, as well as the status for a single node

### Craft CMS version

5.4.5.1

### Plugin version

3.0.4

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/navigation:"dev-craft-5 as 3.0.4"`.

**Comment by MoritzLost** [comment]
@engram-design Thanks, just tested this on 3.0.5, works perfectly 👍
