### ISSUE TITLE
Bugfix on Query String.

### ISSUE THREAD

**Issue by mthomas88** [verbb/navigation#41]
### Description
There is a bug in the index.html template which creates an incorrect query string variable that makes craft 404 template not found.

### Steps to reproduce

1. Use version 1.0.11
2. Navigate to the index template.
3. Click on any link, you'll see the URL is <normalUrl>/build/1&storedSiteId=1
4. This is not a valid query string, hence Craft throws a 404.

### Additional info

- Plugin version: 1.0.11
- Craft version: 3.0.26.1

**Comment by mthomas88** [comment]
Created a PR for this, here: https://github.com/verbb/navigation/pull/40

**Comment by engram-design** [comment]
Fixed in [1.0.12](https://github.com/verbb/navigation/releases/tag/1.0.12).
