### ISSUE TITLE
Template Not Found 404 in CMS which renders the plugin unusable

### ISSUE THREAD

**Issue by mediabeastnz** [verbb/navigation#42]
### Description
Latest update 1.0.11 seems to throw a template 404 which renders the plugin unusable.

`Template not found: navigation/navs/build/1&storedSiteId=1`

### Steps to reproduce

1. Install plugin version 1.0.11
2. add navigation
3. Click on navigation to add entries

### Additional info

- Plugin version: 1.0.11
- Craft version: 3.0.26.1

**Comment by engram-design** [comment]
Yep, sorry about that, should be pushing a new version shortly.

**Comment by engram-design** [comment]
Fixed in [1.0.12](https://github.com/verbb/navigation/releases/tag/1.0.12).

**Comment by lxcodes** [comment]
Just in case someone else stumbles into this, I need to clear my caches in the CMS before the update worked.

Thanks for the fix team. 👍
