### ISSUE TITLE
Internal server error in CMS Navigation > Site when sites are disabled at Sections > Site Settings

### ISSUE THREAD

**Issue by divyan** [verbb/navigation#44]
### Description

There's an Internal server error (error log below) when you sites on a multisite installation and there's an entry created in all sites and you go a the disabled-site with the previously linked entry in the navigation plugin.

Log dump:
`[Error] Error: Call to a member function displayName() on null in /var/www/html/vendor/verbb/navigation/src/elements/Node.php:104
Stack trace:
#0 /var/www/html/vendor/verbb/navigation/src/elements/Node.php(95): verbb\navigation\elements\Node->getElement()
#1 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): verbb\navigation\elements\Node->init()
#2 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2225): yii\base\BaseObject->__construct(Array)
#3 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2151): craft\elements\db\ElementQuery->_createElement(Array)
#4 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1143): craft\elements\db\ElementQuery->_createElements(Array)
#5 /var/www/html/vendor/yiisoft/yii2/db/Query.php(238): craft\elements\db\ElementQuery->populate(Array)
#6 /var/www/html/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#7 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1172): craft\db\Query->all(NULL)
#8 /var/www/html/vendor/twig/twig/lib/Twig/Extension/Core.php(1619): craft\elements\db\ElementQuery->all()
#9 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(verbb\navigation\elements\db\NodeQuery), 'all', Array, 'method', false, false)
#10 /var/www/html/storage/runtime/compiled_templates/cf/cf59384e2c064b0f2713d36c11cf3b0456614a4f7e42c6df619ef4eb711e2a00.php(126): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(verbb\navigation\elements\db\NodeQuery), 'all', Array, 'method')
#11 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_db0daf1767ebd79700c0b1eccb4cd1c6f634764eb95a15c04ec0c9c60607fcbe->doDisplay(Array, Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#13 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#15 /var/www/html/storage/runtime/compiled_templates/6b/6b57e6f61ea23335197272c7ac0a0aa7d5137a3ad138a77008b8202d821f1d7a.php(28): craft\web\twig\Template->display(Array, Array)
#16 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_988a8365f2eec2b3a0e0ddf4f60d236e908bff01b816e23220ccd028994b5ae2->doDisplay(Array, Array)
#17 /var/www/html/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#18 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#19 /var/www/html/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#20 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#21 /var/www/html/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('index', Array)
#23 /var/www/html/vendor/craftcms/cms/src/web/View.php(378): craft\web\View->renderTemplate('index', Array)
#24 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate('index', Array)
#25 /var/www/html/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('index', Array)
#26 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#27 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#28 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#29 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('render', Array)
#30 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#31 /var/www/html/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('templates/rende...', Array)
#32 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#33 /var/www/html/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#34 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#35 /var/www/html/public_html/index.php(42): yii\base\Application->run()
#36 {main}
2018-10-08 10:35:31 [-][1][e0tjm7ava22taks0j22l65h262][info][application] $_GET = [
    'p' => 'locatie/den-haag'
]`

### Steps to reproduce

1. Create a multisite
2. Create an entry that's saved in all sites ( in a Channel for example 'pages' )
3. Create a navigation with an item linked to the entry in all sites.*
4. Go to Settings > Sections > Pages Channel settings.
5. Disable all other sites, except the primary.
6. Go back to the navigation. Now the primary site nav will work, but if you switch to a site you disabled previously, the error occurs.

*The probleem seems to occur even without even linking an entry (I removed the linked entry, before disabling some sites in the Channel settings and the same error at step 6 also occurs )

### Additional info

- Plugin version: 1.0.9
- Craft version: 3.0.26.1

**Comment by engram-design** [comment]
This was fixed in [1.0.10](https://github.com/verbb/navigation/commit/483733bb480ebe4441d231add41d9b3a454563b0)
