### ISSUE TITLE
FR: Import data from the A&M Nav table into verbb/navigation on a Craft 3 setup

### ISSUE THREAD

**Issue by lemiwinkz** [verbb/navigation#45]
We are using the plugin as a replacement for https://github.com/am-impact/amnav. Seeing as there is a lack of updates from their side we are going to use it for all upgrades to C3 that we have to do moving forward. As far as we can see there currently isnt a first-party solution to import the nav and corresponding nodes from a&m's solution to verbb's. 

We have been doing this by hand which is far from ideal.

Concretely: Would you be open to a PR that implements this as a first party solution via the settings screen in a one-click update 'style' implementation or is something like this being worked on already? 

P.S Obviously i also have something to make up for the mistake in #42 #41 #34 😂😋🤕 so i hope you'll be up for it!

**Comment by engram-design** [comment]
@lemiwinkz We're in the same boat using it as a replacement, so its certainly on the card. Consider this added to the list! You're more than welcome to submit a PR, but its something we've been wanting to implement as well (likely months away FYI).

**Comment by engram-design** [comment]
FYI, this has been added in [1.1.0](https://github.com/verbb/navigation/releases/tag/1.1.0). Access it via the plugin settings, or it'll do it automatically if it detects any of the AMNav db tables (a Craft 2 upgrade for instance).
