### ISSUE TITLE
BUG: Exception when navigating to the homepage

### ISSUE THREAD

**Issue by improved-software** [verbb/navigation#47]
### Description
Navigating to the homepage throws an exception **Trying to get property 'uri' of non-object**

Changing line 128 of \vendor\verbb\navigation\src\elements\Node.php
**from**
`if ($this->_elementUrl && $this->_elementUrl->uri === '__home__') {`
**to** 
`if ($this->_elementUrl && $this->_elementUrl === '__home__') {`

Fixes the issue. Page then loads and homepage nav item is set to active

### Steps to reproduce

1. Updated to version 1.0.13. 
2. Navigating to the home page throws the exception

### Additional info

- Plugin version: 1.0.13
- Craft version: 3.0.30.2

**Comment by engram-design** [comment]
Thanks for reporting this and sorry about that. Fixed in [1.0.14](https://github.com/verbb/navigation/releases/tag/1.0.14)
