### ISSUE TITLE
Plugin throwing error when entries are updated by the console

### ISSUE THREAD

**Issue by mtnorthrop** [verbb/navigation#48]
### Description
I use the Schematic plugin to update Sections using the console. When I try to do this now, an exception is thrown due to Navigation's `verbb\navigation\services\Nodes::onSaveElement()` method. It appears that the problem is due to the fact that `Request::getSegments()` method is called in order to determine whether a URL is active, but this method does not exist for console requests.

Here is the full stacktrace (Navigation's involvement starts on line `#8`):
```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getSegments()' in /var/www/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /var/www/vendor/verbb/navigation/src/elements/Node.php(123): yii\base\Component->__call('getSegments', Array)
#1 /var/www/vendor/yiisoft/yii2/base/Component.php(139): verbb\navigation\elements\Node->getActive()
#2 /var/www/vendor/craftcms/cms/src/base/Element.php(796): yii\base\Component->__get('active')
#3 /var/www/vendor/verbb/navigation/src/elements/db/NodeQuery.php(92): craft\base\Element->__get('active')
#4 /var/www/vendor/yiisoft/yii2/db/Query.php(238): verbb\navigation\elements\db\NodeQuery->populate(Array)
#5 /var/www/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#6 /var/www/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1172): craft\db\Query->all(NULL)
#7 /var/www/vendor/verbb/navigation/src/services/Nodes.php(55): craft\elements\db\ElementQuery->all()
#8 [internal function]: verbb\navigation\services\Nodes->onSaveElement(Object(craft\events\ElementEvent))

#9 /var/www/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(craft\events\ElementEvent))
#10 /var/www/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'beforeSaveEleme...', Object(craft\events\ElementEvent))
#11 /var/www/vendor/craftcms/cms/src/services/Elements.php(382): yii\base\Component->trigger('beforeSaveEleme...', Object(craft\events\ElementEvent))
#12 /var/www/vendor/craftcms/cms/src/services/Sections.php(1290): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#13 /var/www/vendor/craftcms/cms/src/services/Sections.php(635): craft\services\Sections->_onSaveSingle(Object(craft\models\Section), false, Array)
#14 /var/www/vendor/nerds-and-company/schematic/src/Converters/Models/Section.php(47): craft\services\Sections->saveSection(Object(craft\models\Section))
#15 /var/www/vendor/nerds-and-company/schematic/src/Mappers/ModelMapper.php(68): NerdsAndCompany\Schematic\Converters\Models\Section->saveRecord(Object(craft\models\Section), Array)
#16 /var/www/vendor/nerds-and-company/schematic/src/Controllers/ImportController.php(88): NerdsAndCompany\Schematic\Mappers\ModelMapper->import(Array, Array)
#17 /var/www/vendor/nerds-and-company/schematic/src/Controllers/ImportController.php(49): NerdsAndCompany\Schematic\Controllers\ImportController->importFromYaml(Array)
#18 [internal function]: NerdsAndCompany\Schematic\Controllers\ImportController->actionIndex()
#19 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#21 /var/www/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#22 /var/www/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#23 /var/www/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('schematic/impor...', Array)
#24 /var/www/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('schematic/impor...', Array)
#25 /var/www/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#26 /var/www/craft(22): yii\base\Application->run()
#27 {main}
```

This error seems to have been introduced somewhere between versions 1.0.13-1.0.15. I'm aware that the Schematic plugin is part of this issue, but it seems that the problem is due to Navigation not taking into consideration cases where elements are updated through the console, so this doesn't seem to be a problem _only_ when using the Schematic plugin.

Just to be clear, this error happens when trying to update a Single section through the console.

### Steps to reproduce

1. Export sections schema using Schematic
2. Import sections schema
3. See exception thrown

### Additional info

- Plugin version: 1.0.15 (maybe since 1.0.13?)
- Craft version: 3.0.31

**Comment by Osze** [comment]
Same problem here. Re-saving entries failes when saving a section.

Just got this answer after sending in a ticket to Craft about it:

Hi Oscaro,

From the stack trace in your logs, this looks to be a bug in the Navigation plugin you've got installed:

2018-11-14 11:23:25 [-][-][-][error][craft\queue\QueueLogBehavior::afterError]  [10680] Resaving Companies entries (attempt: 1) - Error (time: 0.029s): Calling unknown method: craft\console\Request::getSegments()
2018-11-14 11:23:25 [-][-][-][error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: craft\console\Request::getSegments() in /srv/users/craft/apps/mybetting-in/craft/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /srv/users/craft/apps/mybetting-in/craft/vendor/verbb/navigation/src/elements/Node.php(123): yii\base\Component->__call('getSegments', Array)
#1 /srv/users/craft/apps/mybetting-in/craft/vendor/yiisoft/yii2/base/Component.php(139): verbb\navigation\elements\Node->getActive()
#2 /srv/users/craft/apps/mybetting-in/craft/vendor/craftcms/cms/src/base/Element.php(796): yii\base\Component->__get('active')
#3 /srv/users/craft/apps/mybetting-in/craft/vendor/verbb/navigation/src/elements/db/NodeQuery.php(92): craft\base\Element->__get('active')
#4 /srv/users/craft/apps/mybetting-in/craft/vendor/yiisoft/yii2/db/Query.php(238): verbb\navigation\elements\db\NodeQuery->populate(Array)
#5 /srv/users/craft/apps/mybetting-in/craft/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#6 /srv/users/craft/apps/mybetting-in/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1172): craft\db\Query->all(NULL)
#7 /srv/users/craft/apps/mybetting-in/craft/vendor/verbb/navigation/src/services/Nodes.php(55): craft\elements\db\ElementQuery->all()


Looks similar to this one which someone has already opened an issue for: https://github.com/verbb/navigation/issues/48

-Brad

**Comment by engram-design** [comment]
Should be fixed in [1.0.16](https://github.com/verbb/navigation/releases/tag/1.0.16)

**Comment by Osze** [comment]
Not fixed on my end :(

I've updated the plugin to 1.0.16 but I still get same error message when saving a section:

Resaving Pages entries Failed 

In Queue Manager I get message:
Calling unknown method: craft\console\Request::getSegments()

{
    "elementType": "craft\\elements\\Entry",
    "criteria": {
        "siteId": "1",
        "sectionId": "33",
        "status": null,
        "enabledForSite": false
    },
    "description": "Resaving Pages entries"
}


When clicking "Try Again" it works. Don't know why it doesn't work from the start.

**Comment by engram-design** [comment]
I'm unable to replicate this. I'm testing by re-saving any section, the queue job to re-save elements fires and no errors reported? I'll give Queue Manager a go however...

**Comment by engram-design** [comment]
@Osze Actually, might have committed the wrong thing like an idiot...

Can you give https://github.com/verbb/navigation/releases/tag/1.0.16.1 a go?

**Comment by Osze** [comment]
It's fixed! With the new update it works as it should! 👍 
Thank you Josh!!
