### ISSUE TITLE
Entry nodes link to only 1 site's version

### ISSUE THREAD

**Issue by riasvdv** [verbb/navigation#49]
### Description
When selecting an entry, the url in each site stays the same, which causes nodes to link to a different site.

For example:
- Add a node to a contact page in site "FR" /fr/contact
- Look at nav in site "NL", should be /nl/contact but it stays /fr/contact

**Comment by sjelfull** [comment]
I'm not sure if my issue is the same, but here we go:

Node url's is empty in all sites except for the default one, and I think this happened after a recent upgrade.

**Comment by engram-design** [comment]
Should be fixed in [1.0.17.1](https://github.com/verbb/navigation/releases/tag/1.0.17.1)
