### ISSUE TITLE
Allow changing of node type without deleting and re-creating

### ISSUE THREAD

**Issue by cmalven** [verbb/navigation#52]
This is more of a feature request than a bug.

The inability to change the type of a node – for instance from `Entry` to `Custom URL` or vice versa – without deleting and re-creating it is a deal-breaker for me, especially given that you cannot delete a node without deleting all of it's children. This makes on-the-fly changes to taxonomy very cumbersome.

**Comment by engram-design** [comment]
Added [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0)
