### ISSUE TITLE
Allowing getActiveNode() to be filtered by .handle('navTitle')

### ISSUE THREAD

**Issue by kellyannmcnamara01** [verbb/navigation#53]
### Description
On our site we are using the navigation plugin for both the main navigation and the footer navigation. On top level pages (i.e. resources index) we are using the navigation plugin to populate a sub nav in a banner. We are successful in rendering the sub-nav when the active node is not in both the footer navigation and the main navigation. If the current active node is indeed in both navigations (i.e. resources index) we are unable to filter by the navigation handle resulting in the sub nav not appearing. 

We are looking for the ability to get the active node and if it is within the selected navigation handle then populate it, otherwise dont. 

### Steps to reproduce

1. getting the active node:
`{% set activeNode = craft.navigation.getActiveNode() %}`
2. getting the sub nav within a particluar handle that is a descendant of the active node
`{% set subNavigationNodes = craft.navigation.nodes().handle('mainNavigation').descendantOf(activeNode) %}`

### What we would love to see
Here's a snippet of what we think might be a good way to approach this, similar to how child nodes are rendered off of a specific navigation handle:
`craft.navigation.handle('navigationHandle').getActiveNode()`

### Additional info

- Plugin version: 1.0.18
- Craft version: 3.0.34

**Comment by engram-design** [comment]
Sure, so at the moment, the active node just sends back the single active node across all your navs site-wide - not an amazing solution.

You now have access to all the query params in this `getActiveNode()` call. For example:

```
{% set activeNode = craft.navigation.getActiveNode({ handle: 'mainNavigation' }) %}
```

**Comment by brettburwell** [comment]
I just bumped into this as well and was happy to find this solution. Works like a charm! 

You should consider [adding this to the docs](https://verbb.io/craft-plugins/navigation/docs/template-guides/rendering-nodes#craft-navigation-getActiveNode) when you get the chance, as I imagine it's a relatively common issue.
