### ISSUE TITLE
Add instructions to navigation

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#58]
Just like each field can have short instruction/description for content editors, menus should also have one.

**Comment by engram-design** [comment]
Just to clarify, this would be for the actual navigation, not the individual node? Added in [1.1.0](https://github.com/verbb/navigation/releases/tag/1.1.0)

**Comment by piotrpog** [comment]
@engram-design 
Yes, thats what i meant. Thanks for adding it!
