### ISSUE TITLE
Distinguish nodes that have alternative title

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#59]
This is something usefull for translators.

When nodes just use its entry/category title, translator doesnt have any business manipulating menus. But if node uses alternative title, he has to translate this title.

Lets think of large menu with multiple levels and hundreds of nodes. Translator would have to check each node to find out if it uses alternative title that needs to be translated. 

Some somple icon to distinguish such nodes from rest (along with manual nodes that also need to be translated) would make translator job easier.

**Comment by engram-design** [comment]
Added in [1.1.0](https://github.com/verbb/navigation/releases/tag/1.1.0)
