### ISSUE TITLE
Set alternative title and classes before adding node

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#60]
User can first set up "Open in new window" option before adding node, in right side column.
But to set up alternative title or css classes he has to first add node and than access settings of node. These settings should be possible to set up before creating node.

**Comment by engram-design** [comment]
This is actually just done for simplicity's sake - so there's not a heap of options straight away. I'll consider this however.

**Comment by engram-design** [comment]
Marking as 'wontfix' purely on the basis of keeping creating navigation nodes a simple process, keeping clients in mind.
