### ISSUE TITLE
Node type is unstyled during dragging

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#61]
During dragging, except node name we also see node type below it - its unstyled thought.

I propose one of two solutions - either make node type still styled while dragging, or just hide it while dragging.

**Comment by missmatsuko** [comment]
Same here, this is kind of what I'm seeing:
https://imgur.com/Z7RVM88

I think it's not supposed to be visible when dragging. 
I'm not sure what the purpose of displaying it it would be.

**Comment by engram-design** [comment]
Fixed in [1.1.0](https://github.com/verbb/navigation/releases/tag/1.1.0)
