### ISSUE TITLE
Listing type node

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#62]
I propose adding node that would function as not single entry/category page, but as list of all entries categories in specific section/category group.

**Comment by engram-design** [comment]
Agreed, will consider the best way to implement this!

**Comment by cscomfort** [comment]
I'm in favor of this as well but appreciate the challenge in architecting a universal solution. Given Craft's flexibility, there's no guarantee that a particular channel or category is going to list its entries in a known location. For example, with individual blog entries that have an Entry URI Format of `blog/{slug}`, it would be an assumption (however likely) to expect that the blog entries list resides at `/blog` (using a Template setting of `/templates/blog/index.html`). It's feasible that the site might be architected in such a way that the blog entries list resides at, say, `/latest-blogs`.

**Comment by engram-design** [comment]
I'm going to close this as of [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0) you can use custom [node types](https://verbb.io/craft-plugins/navigation/docs/developers/extending-elements#node-types). In this instance, you can create your own class for all manner of things. One such example would be to create a "section" node type, where you can pick a specific section - the implementation would be up to you.
