### ISSUE TITLE
Support Craft 3.1 Project Config

### ISSUE THREAD

**Issue by boboldehampsink** [verbb/navigation#64]
Any plans to support Craft 3.1 (and especially Project Config)?

**Comment by engram-design** [comment]
Definitely, in the next release!

**Comment by E2design** [comment]
When will the next release, that supports 3.1 becomes available?

**Comment by engram-design** [comment]
@E2design Just to be clear, Navigation works perfectly on 3.1, this FR is to add project config support for navigations (not navigation nodes), and will be done soon.

**Comment by boboldehampsink** [comment]
Any ETA yet?

**Comment by engram-design** [comment]
Added on the latest branch. Would you be able to give it a spin via `composer require verbb/navigation:dev-craft-3`?

**Comment by boboldehampsink** [comment]
Almost there - seeing the following error when going into a menu in the admin:

```
SQLSTATE[42704]: Undefined object: 7 ERROR: type "unsigned" does not exist
LINE 16: ..."."elementId" AND CAST("elements_sites"."slug" AS UNSIGNED) ...
```

Using PostgreSQL 10.7

**Comment by engram-design** [comment]
Added in [1.1.9](https://github.com/verbb/navigation/releases/tag/1.1.9)
