### ISSUE TITLE
Feature request: Navigation field type to select a created navigation

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/navigation#65]
### Description
We have a couple sites where we allow clients to select a navigation to display a sub nav on a given "Page" entry. It'd be awesome if we could allow them to choose from one of the Navigations they've created using this plugin.

**Comment by engram-design** [comment]
Agreed, will add this to our next todo items.

**Comment by aaronbushnell** [comment]
Thanks! For now I have a simple Module I’m using to supplement this but I’ll plan on swapping it out once this is in the core. Thanks for your work on this!

**Comment by engram-design** [comment]
Added in [1.1.0](https://github.com/verbb/navigation/releases/tag/1.1.0)

**Comment by aaronbushnell** [comment]
Thanks a ton, @engram-design!
