### ISSUE TITLE
Unable to add entries on MultiSite

### ISSUE THREAD

**Issue by dwhoban** [verbb/navigation#7]
### Description
When creating a new navigation in a multisite I am not able to add entries to a site other than the default site. No errors are flagged in the debug toolbar

### Steps to reproduce

1. Create new navigation
2. Add navigation for the default site
3. Switch to the second site
4. Click on add entry
5. Switch to entries for the second site in the modal
6. Select an entry and click select
7. No entry is added

### Additional info

- Plugin version: 1.0.2
- Craft version: 3.16.01

**Comment by engram-design** [comment]
I can't seem to replicate this. Can you have a look at this video to ensure I'm following your instructions correctly?

https://www.dropbox.com/s/i31zytdx701uwm3/Nav-sites.mp4?dl=0

**Comment by dwhoban** [comment]
Yeah, it's strange.

I created the default nav first...

The only difference I could see is that there are completely different sections between the two site.  Could that be it?

https://www.dropbox.com/s/6jzaew19zldx9d3/issue.mov?dl=0

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/navigation/releases/tag/1.0.3)
