### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#70]
Today i tried to install plugin on localhost to test new version a bit. Plugin was installed into vendor directory, but I cannot install in into craft. It just sits in plugins list with "not installed" label. When i tried to click "install", "Couldn’t install plugin." appears.

My system info:
PHP version	7.2.2
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.2.2
Craft edition & version	Craft Solo 3.1.8
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
Craft Commerce	2.0.4
Relations	1.0.1

**Comment by engram-design** [comment]
Would you be able to have a look at your web.log file to see if there's an error in there?

**Comment by engram-design** [comment]
Should be fixed in https://github.com/verbb/navigation/releases/tag/1.1.1, but let me know if not.

**Comment by DanSpratlingRally** [comment]
I'm getting this same error with Craft version 3.1.12 and plugin version 1.1.3

**Comment by engram-design** [comment]
@DanSpratlingRally Anything in your web.log that points to an error?

**Comment by DanSpratlingRally** [comment]
`$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [
        'error' => 1
    ]
    'bd62416aa8538ede709019a5e113eea5__auth_access' => [
        0 => 'editStructure:4'
    ]
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => '9'
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1550579245
    'error' => 'Couldn’t install plugin.'
]`

is there anything else that you might need?

**Comment by DanSpratlingRally** [comment]
This error might be better. same exists for navigation_nav table

`
2019-02-19 11:32:21 [-][9][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 1
2019-02-19 11:32:21 [-][9][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-02-19 11:32:21 [-][9][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-02-19 11:32:21 [-][9][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-02-19 11:32:21 [-][9][-][warning][craft\db\mysql\Schema::rollBackSavepoint] Tried to roll back a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: ROLLBACK TO SAVEPOINT LEVEL1
2019-02-19 11:32:21 [-][9][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.003s). Output:
    > create table {{%navigation_nodes}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'navigation_nodes' already exists
`

After deleting the plugin tables, installation works. We used a template database from a previous project, which i'd guess caused this issue but a clearer error (saying which tables were clashing) would be super helpful.

**Comment by engram-design** [comment]
I'm pretty sure we can't provide a more front-facing error, other than `Couldn’t install plugin`, but I'll look into it.

**Comment by E2design** [comment]
Having the same issue while upgrading from CRAFT 2.X with A&M nav installed to 3.15.

Removed both craft_navigation_X tables like the solution above  and reinstalling NAVIGATION but the issue persists.

**Comment by engram-design** [comment]
@E2design Were there any errors in your logs? You might also want to try https://github.com/verbb/navigation/releases/tag/1.1.6 where a potential error might've occurred
