### ISSUE TITLE
Add target node attribute

### ISSUE THREAD

**Issue by chasegiunta** [verbb/navigation#74]
Would be nice, as an alternative to doing
```
target="{{ item.newWindow ? '_blank' : '_self' }}"
```
we could do 
```
target="{{ node.target }}"
```
and it returned either `_blank` or `_self`

**Comment by engram-design** [comment]
I have considered this, but opening in a new window is more than just setting the target to `_blank` - at least it should be: https://medium.com/@ali.dev/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f

For an outgoing link, you'd want it to really produce a link like `target="_blank" rel="noopener noreferrer"`, which is tricky to assume using an attribute. We could certainly add this is our render function however.

**Comment by chasegiunta** [comment]
@engram-design hmmm, I've never heard of that security concern, and definitely seems like a valid concern in the context that he described: generating links from user-generated content or in cases where you cannot assume to linked page is safe.

I don't think either of those would apply to links I've put _in my own navigation_, though.
Could we assume that if I was adding a link to my own navigation, I'm vouching for it's safety?

**Comment by engram-design** [comment]
@chasegiunta That was my thinking just after I responded, will likely add it anyway!

**Comment by engram-design** [comment]
Ha - well looks like I'm already doing this for `node.link`, which is forward thinking of me!

Just added `node.target` in [1.1.5](https://github.com/verbb/navigation/releases/tag/1.1.5)
