### ISSUE TITLE
Add ability to get full nested array of nodes and their children

### ISSUE THREAD

**Issue by jakedohm** [verbb/navigation#75]
### Description

There's currently no way to get an array/object of the full nested navigation. The ability to do this would be super helpful for when you're trying to access/render your nav with JavaScript, or at least outside of twig.

**Current solution**: Here's a solution in Twig that works, but only for one level of nesting deep. This pattern could be applied recursively to build a full nav tree.

```twig
{% set mobileNav = [] %}
{% nav node in navLinks %}
  {% set children = [] %}
  {% if node.children %}
    {% for child in node.children %}
      {% set children = children | merge([child]) %}
    {% endfor %}
  {% endif %}
    
  {% set node = node | merge({
    children: children
  }) %}
  {% set mobileNav = mobileNav | merge([node]) %}
{% endnav %}
```

**Comment by engram-design** [comment]
Added in [1.1.8](https://github.com/verbb/navigation/releases/tag/1.1.8), using `craft.navigation.tree()`
