### ISSUE TITLE
Homepage node not active in latest 1.1.8

### ISSUE THREAD

**Issue by frontedbe** [verbb/navigation#76]
### Description

The node.active returns false on the homepage in the latest 1.1.8 version of the plugin.

### Steps to reproduce

1. Create homepage
2. Add this homepage as a node to a navigation
3. When looping through the nodes the node.active returns false for the homepage node which it shouldn't

### Additional info

- Plugin version: 1.1.8
- Craft version: 3.1.17.1

Thanks for looking into this!

**Comment by engram-design** [comment]
Pushed a fix for this, but could you confirm on the latest branch? Run `composer require verbb/navigation:dev-craft-3` to test it out.

**Comment by frontedbe** [comment]
Thanks Josh, I hereby confirm the fix!

**Comment by engram-design** [comment]
Fixed in [1.1.9](https://github.com/verbb/navigation/releases/tag/1.1.9)
