### ISSUE TITLE
DB error after update

### ISSUE THREAD

**Issue by ryanirelan** [verbb/navigation#77]
### Description
After updating to the latest, I get a database error.

`SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying = integer
LINE 12: ...Id" = "element_item_sites"."elementId" AND "slug" = "element...
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.`

I can send the full error privately, if helpful.

### Steps to reproduce

1. Update to 1.1.8 
2. Update to latest Craft

### Additional info

- Plugin version: 1.1.8
- Craft version: 3.1.17.2
- Database: PostgreSQL 11

**Comment by engram-design** [comment]
Pushed a fix for this, but could you confirm on the latest branch? Run `composer require verbb/navigation:dev-craft-3` to test it out.

**Comment by boboldehampsink** [comment]
Ah, this fix actually broke things for me on PostgreSQL. See also #64

**Comment by engram-design** [comment]
@boboldehampsink Could you give the latest a go now? `composer require verbb/navigation:dev-craft-3`

**Comment by engram-design** [comment]
Fixed in [1.1.9](https://github.com/verbb/navigation/releases/tag/1.1.9)
