### ISSUE TITLE
Disable navigation modification when 'allowAdminChanges' is set to false

### ISSUE THREAD

**Issue by thomasgoemaere** [verbb/navigation#78]
Hi all,

Since the 1.1.9 release the project config is supported, which is great. But I was wondering since the navigation settings are now stored in the project config it should not be possible anymore to adjust these settings (create, edit, delete, change order, ...) when 'allowAdminChanges' is set to false. So the project config doesn't get modified on production env. The only thing that needs to be possible is to modify the menu items belonging to the navigation element. Or am I missing something?

Kind regards,
Thomas

**Comment by engram-design** [comment]
Yep, great point, updated in [1.1.10](https://github.com/verbb/navigation/releases/tag/1.1.10)
