### ISSUE TITLE
Can't save a Custom URL node when site propagation is enabled.

### ISSUE THREAD

**Issue by pgrzyb** [verbb/navigation#79]
### Description
Saving a **Custom URL** node fails when **Propagate nodes across all enabled sites?** is enabled. Chrome console shows: **Failed to load resource: the server responded with a status of 500 () @ /index.php?p=admin/actions/navigation/nodes/save-node:1** 

web.log:
`2019-03-18 00:18:17 [-][5][-][error][TypeError] TypeError: Argument 1 passed to craft\services\Elements::getElementById() must be of the type int, null given, called in /home/vagrant/sites/craft3/vendor/verbb/navigation/src/elements/Node.php on line 313 and defined in /home/vagrant/sites/craft3/vendor/craftcms/cms/src/services/Elements.php:194`

### Steps to reproduce

1. Create a new nav with **Propagate nodes across all enabled sites?** enabled.
2. Try saving a **Custom URL** node

### Additional info

- Plugin version: 1.1.10
- Craft version: 3.1.18

**Comment by pgrzyb** [comment]
I guess thats kind of obvious, but just to make it clear - works just fine with **Propagate nodes across all enabled sites?** disabled. Does somewhat kill my multi-locale setup.

**Comment by engram-design** [comment]
Should be fixed in [1.1.11](https://github.com/verbb/navigation/releases/tag/1.1.11)
