### ISSUE TITLE
BUG: homepage always active

### ISSUE THREAD

**Issue by andrispraulitis** [verbb/navigation#8]
### Description

When adding homepage to the menu node.active is always true on homepage link

### Additional info

- Plugin version: 1.0.2
- Craft version: 3.16.01

**Comment by mdominguez** [comment]
Same here

**Comment by engram-design** [comment]
Fixed in the latest master, and will be rolled into the next release.

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/navigation/releases/tag/1.0.3)
