### ISSUE TITLE
Not an issue, more of a question : I'm not sure of the "read-only" behavior when `allowAdminChanges` is set to true

### ISSUE THREAD

**Issue by jesuismaxime** [verbb/navigation#81]
A client - or a webmaster - should be able to edit elements from existing navigations on production environment. 

The idea describes in issue #78 is not working. I'm not able, as an admin, to edit navigations content.

Craft 3.1.18
Navigation 1.1.10

**Comment by engram-design** [comment]
Should be fixed in [1.1.11](https://github.com/verbb/navigation/releases/tag/1.1.11)
