### ISSUE TITLE
FR: Navee Migration

### ISSUE THREAD

**Issue by theskyfloor** [verbb/navigation#84]
### Description

Would you consider writing a Navee migration? Have some sites I want to bring up to C3 but need to switch Navee to something.

**Comment by engram-design** [comment]
Yep, I'll add it to our list!

**Comment by theskyfloor** [comment]
Any progress on this? No rush, just curious!

**Comment by engram-design** [comment]
No further progress on this, I've never personally used Navee, so just need to get up to speed on how it manages things. There is a potentially upcoming project of ours that might require this, but no promises. Stay tuned!

**Comment by jsunsawyer** [comment]
Version 1.3.2 is showing `Navee Migration` in the settings panel. Tested just to see what would happen and the migration fails. I assume this isn't supposed to be showing up yet, right?

**Comment by engram-design** [comment]
It should be working, at least on a minimal level, just not supporting nested nav's yet. What was the error?

**Comment by jsunsawyer** [comment]
```
> Migrating nav `primaryNav` ...

'SQLSTATE[42S22]: Column not found: 1054 Unknown column \'navee_nodes.id\' in \'on clause\'
The SQL being executed was: SELECT *
FROM `fs_navee_nodes`
LEFT JOIN `fs_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `navee_nodes`.`id`
WHERE (`navigationId`=\'1\') AND (`siteId`=\'1\')'
```

**Comment by jsunsawyer** [comment]
@engram-design We have 4 Navs set up. The `primaryNav` is very basic. 4 links, with 1 being a custom url, and the rest being entries. No additional settings.

We do have a `sitemap` nav that uses a very basic nested setup.

**Comment by engram-design** [comment]
@jsunsawyer I know its been a while. but I have no idea what is going on with that error. It's saying it can't find the `id` column in `navee_nodes`, which is pretty concerning! If it's still an issue, send through your `navee` database tables.

But this should all be completed in [1.4.0](https://github.com/verbb/navigation/releases/tag/1.4.0)
