### ISSUE TITLE
FR: Ability to restrict number of items in a navigation

### ISSUE THREAD

**Issue by sergeifilippov** [verbb/navigation#85]
Sometimes, you need to save the client from themselves.

It would be great if you could be able to restrict number of menu item nodes in a given navigation.

eg. Header menu should only have upto 3 items. In admin, you would be able to set `3` as the maximum number of nodes for the navigation menu.

NB. Maybe this feature should be restrict navigations that are 1 level deep only.

**Comment by engram-design** [comment]
Added in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0)
