### ISSUE TITLE
Amnav migration not working

### ISSUE THREAD

**Issue by billymedia** [verbb/navigation#87]
### Description
Clicking on the migration button does nothing. There definitely are am nav menus and associated db tables. 

I poked around the code and its silently failing at this in migrations/AmNavPlugin.php

```
                if (Craft::$app->getElements()->saveElement($node)) {
                    $this->processedNodes[$AmNode['id']] = [
                        'oldParent' => $AmNode['parentId'],
                        'newNode' => $node->id,
                    ];
                }
```

### Steps to reproduce

1. Click on migrate

### Additional info

- Plugin version : 1.1.11
- Craft version: Craft CMS 3.1.24

**Comment by engram-design** [comment]
Would you be willing to share your amnav database tables? Happy if you'd like to over Discord (handle `crawf`)

**Comment by billymedia** [comment]
Ive contacted you in discord.

**Comment by engram-design** [comment]
I've just added a great deal more feedback in the `craft-3` branch. If you'd like to install via `composer require verbb/navigation:dev-craft-3` when clicking Migrate, it'll show you an output of the migration.

Note that the most common issue is that there'll be a `Integrity constraint violation` where it'll be trying to link an element (Entry, Category, etc) that doesn't exist anymore with our node. This just means that the original element is missing, or has been deleted.

Fortunately, it'll skip over these errors and process the rest of your navs/nodes now.

**Comment by billymedia** [comment]
Thanks @engram-design , I installed that version and it has now managed to create the menus but they were all empty, i.e. no nodes were created. There was no output to screen, and in storage/logs/web.log, there were entries for insert statements but the nodes table was empty and oddly there were no sql errors. e.g. ...

``2019-05-06 08:36:41 [-][1][ebb98b0c4fd7e9fc06d3788ae773f31b][info][yii\db\Command::execute] INSERT INTO `craft_navigation_nodes` (`id`, `elementId`, `navId`, `url`, `type`, `classes`, `newWindow`, `dateCreated`, `uid`, `dateUpdated`) VALUES (35665, 1740, 4, NULL, 'craft\\elements\\Entry', NULL, 0, '2019-05-06 13:36:41', 'a33f88d6-97ca-4942-a1f1-c293b23d8009', '2019-05-06 13:36:41')``

``2019-05-06 08:36:41 [-][1][ebb98b0c4fd7e9fc06d3788ae773f31b][profile begin][yii\db\Command::execute] INSERT INTO `craft_navigation_nodes` (`id`, `elementId`, `navId`, `url`, `type`, `classes`, `newWindow`, `dateCreated`, `uid`, `dateUpdated`) VALUES (35665, 1740, 4, NULL, 'craft\\elements\\Entry', NULL, 0, '2019-05-06 13:36:41', 'a33f88d6-97ca-4942-a1f1-c293b23d8009', '2019-05-06 13:36:41')``

``2019-05-06 08:36:41 [-][1][ebb98b0c4fd7e9fc06d3788ae773f31b][profile end][yii\db\Command::execute] INSERT INTO `craft_navigation_nodes` (`id`, `elementId`, `navId`, `url`, `type`, `classes`, `newWindow`, `dateCreated`, `uid`, `dateUpdated`) VALUES (35665, 1740, 4, NULL, 'craft\\elements\\Entry', NULL, 0, '2019-05-06 13:36:41', 'a33f88d6-97ca-4942-a1f1-c293b23d8009', '2019-05-06 13:36:41')
``

**Comment by engram-design** [comment]
So you went to Settings > Navigation and hit the "Migrate" button? It should show some output, even if it was successful? Happy to chat on Discord if that'd be easier?

**Comment by engram-design** [comment]
Closed, improved the output, but also sorted through Discord
