### ISSUE TITLE
FR: select active site when using multisite

### ISSUE THREAD

**Issue by bartrylant** [verbb/navigation#89]
When using Navigation with multiple sites, it would be nice if the last selected website (in Entries) would also be selected in Navigation.

The issue I have now is that I have clients who have multiple websites on one Craft install. Let's say Site A, Site B, Site C. Client goes to Entries and chooses Site C in the dropdown box on the top of the page. Makes some entries, edits some entries. Then the client clicks on Navigation to edit navigation for that site. However, the site select dropdown box on top, is set to the first site in the alphabet, in this case Site A. It would be better if site C was selected.

This might seem a minor thing, but I have a client who has multiple sites that have the same structure (entries-wise) but slightly different navigation structures. Many times they edit the wrong navigation, because in their head they have been busy with Site C all the time, and they forget to change the navigation dropdown from Site A to Site C.

**Comment by engram-design** [comment]
It should actually be doing that, so will investigate

**Comment by bartrylant** [comment]
I thought it would be fixed in the latest release, but it is not. What happens now is:

- selecting a site in the dropdown on the "navigation" page, and then going to entries = selected site is the same site as selected in navigation (as it should be)
- selecting a site in the dropdown on the "entries" page, and then going to navigation = selected site defaults to the first site (top item in the drop down list)

**Comment by bartrylant** [comment]
@engram-design Still not fixed...

**Comment by engram-design** [comment]
@bartrylant Could you potentially put a screen recording together? I can't reproduce it. See my below screen recording.

https://www.dropbox.com/s/ja941ozuhhjrk4m/sites.mov?dl=0

Only other thought is that maybe there's some JS errors?

**Comment by bartrylant** [comment]
Ah, there you have it. What I did was this: with your CP nav plugin, I made a new item in the sidebar because I only want users to be able to edit 1 menu (and not get the list of all available menu's first). I did this by making a link to https://www.________.nl/admin/navigation/navs/build/1/
It probably goes to the first site if no site is specified in the url. So it's my fault because I made a new item in the sidebar that goes directly to the edit mode, instead of going to the plugin's "homepage" (where you have to choose a menu) first.

However, that leaves me with another problem, because I can't do what I want if people have to choose a menu first:

1/ Same or related to this: https://github.com/verbb/navigation/issues/91
I don't want users to be able to edit or delete navigations. Just edit the menu itself, not the properties.

2/ It seems like users permissions don't do anything:
https://github.com/verbb/navigation/issues/95
