### ISSUE TITLE
Breadcrumbs?

### ISSUE THREAD

**Issue by jamielaughton** [verbb/navigation#9]
Is a simple breadcrumbs functionality on your roadmap at all for the near future? e.g. craft.navigation.breadcrumbs. Or should I just build it using the active item from each nav level?

**Comment by lxcodes** [comment]
https://github.com/lxcodes/Trails -- Essentially AmNav's breadcrumbs -- Had to create for a current project and just need to find time to clean up and publish properly.

**Comment by engram-design** [comment]
@lxcodes Nice one! This has also been added to Navigation through `craft.navigation.breadcrumbs()`.
