### ISSUE TITLE
FR: Hide parent assignment for Menus 1 Level deep

### ISSUE THREAD

**Issue by sergeifilippov** [verbb/navigation#90]
When a Menu level is set to 1:

<img width="612" alt="⚙_Header_Links_-_Richmond_Mall" src="https://user-images.githubusercontent.com/123676/58872917-36830880-8719-11e9-9d1d-fdbef88fa26e.png">

If would be great to hide the "Parent" assignment field:

<img width="373" alt="⚙_Header_Links_-_Richmond_Mall" src="https://user-images.githubusercontent.com/123676/58873009-67633d80-8719-11e9-9395-6c57df37bcbe.png">

Maybe something like this:

<img width="378" alt="⚙_Header_Links_-_Richmond_Mall" src="https://user-images.githubusercontent.com/123676/58873050-81048500-8719-11e9-8597-2be5f6dbb879.png">

**Comment by engram-design** [comment]
Fixed in [1.1.13](https://github.com/verbb/navigation/releases/tag/1.1.13)
