### ISSUE TITLE
FR: User permission to add/edit new nodes with no access to the Navigations entries

### ISSUE THREAD

**Issue by sergeifilippov** [verbb/navigation#91]
Currently, when the user has been assigned the "Access Navigation" permission, they can do the following:

- Add new Navigations
- Edit Navigations Settings
- Delete Navigations
- Add/Edit/Remove nodes in a Navigation

It would be great to restrict users ability to:
- Add new Navigations
- Edit Navigations Settings
- Delete Navigations

## Why?

This way you can grant the user only the ability to control the nodes of a given Navigation so the Navigations themselves would not be messed with.

<img width="1161" alt="⚙_Navigation___Menus_-_Richmond_Mall" src="https://user-images.githubusercontent.com/123676/58873482-90d09900-871a-11e9-9d32-81c522dc0e71.png">

**Comment by engram-design** [comment]
Added in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0)
