### ISSUE TITLE
Menu permissions don't have any effect

### ISSUE THREAD

**Issue by bartrylant** [verbb/navigation#95]
### Description
Changing user permissions on which navigations they can edit, doesn't work. Users can still edit all navigations, even the ones they don't have access to.

![Schermafbeelding 20](https://user-images.githubusercontent.com/1434451/60393975-6b6a5b80-9b1d-11e9-8029-219c5568d2b3.png)
![Schermafbeelding 21](https://user-images.githubusercontent.com/1434451/60393976-6e654c00-9b1d-11e9-9299-1e3525cfb5e3.png)

**Comment by engram-design** [comment]
Fixed in [1.1.13](https://github.com/verbb/navigation/releases/tag/1.1.13)

**Comment by engram-design** [comment]
Tweaked further in https://github.com/verbb/navigation/commit/e42e9eac154f45458f7529d1d1f7c8249765b81f
