### ISSUE TITLE
Nav items propagate to all sites even with propagation disabled

### ISSUE THREAD

**Issue by stevenvandemoortele** [verbb/navigation#96]
### Description
Navigation items are propagated to all sites even when Propagate nodes across all enabled sites is disabled.

### Steps to reproduce

1. Create new menu, set Propagate nodes across all enabled sites to disabled.
2. Add an item to the menu
3. Check other site, menu item will be there even though it shouldn't be. Deleting the item also deletes it for all sites.

### Additional info

- Plugin version: 1.1.12
- Craft version: 3.1.31.1

Video link:
https://share.getcloudapp.com/llumlgQp

**Comment by frontedbe** [comment]
Can confirm this!

**Comment by engram-design** [comment]
This was due to a Craft core change, but can you try the fix as per https://github.com/verbb/navigation/commit/d15417b86604791369d8b8f9234b342abbec3d35 by running `composer require verbb/navigation:dev-craft-3` to get it early to test.

**Comment by frontedbe** [comment]
@engram-design Yep seems to be fixed, but only when creating a new navigation.

**Comment by stevenvandemoortele** [comment]
Can also confirm dev branch works!

**Comment by sjelfull** [comment]
@engram-design possible for you to tag a release for this soon?

**Comment by engram-design** [comment]
Added in [1.1.13](https://github.com/verbb/navigation/releases/tag/1.1.13)
